/* About.c generated by valac 0.26.1, the Vala compiler
 * generated from About.vala, do not modify */

/* About.vala
 *
 * Copyright (C) 2009 - 2015 Jerry Casiano
 *
 * This file is part of Font Manager.
 *
 * Font Manager is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Font Manager is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Font Manager.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Author:
 *        Jerry Casiano <JerryCasiano@gmail.com>
*/

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib/gi18n-lib.h>
#include <stdio.h>
#include <gtk/gtk.h>




#define FONT_MANAGER_ABOUT_NAME _ ("Font Manager")
#define FONT_MANAGER_ABOUT_ICON "font-x-generic"
#define FONT_MANAGER_ABOUT_COMMENT _ ("Simple font management for GTK+ desktop environments")
#define FONT_MANAGER_ABOUT_VERSION "0.7.2"
#define FONT_MANAGER_ABOUT_HOMEPAGE "http://code.google.com/p/font-manager/"
#define FONT_MANAGER_ABOUT_COPYRIGHT "Copyright © 2009 - 2015 Jerry Casiano"
#define FONT_MANAGER_ABOUT_LICENSE _ ("\n" \
"    This program is free software: you can redistribute it and/or modi" \
"fy\n" \
"    it under the terms of the GNU General Public License as published " \
"by\n" \
"    the Free Software Foundation, either version 3 of the License, or\n" \
"    (at your option) any later version.\n" \
"\n" \
"    This program is distributed in the hope that it will be useful,\n" \
"    but WITHOUT ANY WARRANTY; without even the implied warranty of\n" \
"    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n" \
"    GNU General Public License for more details.\n" \
"\n" \
"    You should have received a copy of the GNU General Public License\n" \
"    along with this program.  If not, see <http://www.gnu.org/licenses" \
"/>.\n" \
"    ")
#define FONT_MANAGER_AUTHOR "Jerry Casiano <JerryCasiano@gmail.com>"
#define FONT_MANAGER_ABOUT_TRANSLATORS "translator-credits"
void font_manager_show_version (void);
void font_manager_show_about (void);
void font_manager_show_about_dialog (GtkWindow* parent);

const gchar* FONT_MANAGER_ABOUT_AUTHORS[2] = {FONT_MANAGER_AUTHOR, NULL};
const gchar* FONT_MANAGER_ABOUT_DOCUMENTERS[2] = {FONT_MANAGER_AUTHOR, NULL};
const gchar* FONT_MANAGER_ABOUT_ARTISTS[1] = {NULL};

void font_manager_show_version (void) {
	FILE* _tmp0_ = NULL;
	_tmp0_ = stdout;
	fprintf (_tmp0_, "%s %s\n", FONT_MANAGER_ABOUT_NAME, FONT_MANAGER_ABOUT_VERSION);
	return;
}


void font_manager_show_about (void) {
	FILE* _tmp0_ = NULL;
	_tmp0_ = stdout;
	fprintf (_tmp0_, "\n    %s - %s\n\n\t\t  %s\n%s\n", FONT_MANAGER_ABOUT_NAME, FONT_MANAGER_ABOUT_COMMENT, FONT_MANAGER_ABOUT_COPYRIGHT, FONT_MANAGER_ABOUT_LICENSE);
	return;
}


void font_manager_show_about_dialog (GtkWindow* parent) {
	GtkWindow* _tmp0_ = NULL;
	_tmp0_ = parent;
	gtk_show_about_dialog (_tmp0_, "program-name", FONT_MANAGER_ABOUT_NAME, "logo-icon-name", FONT_MANAGER_ABOUT_ICON, "version", FONT_MANAGER_ABOUT_VERSION, "copyright", FONT_MANAGER_ABOUT_COPYRIGHT, "comments", FONT_MANAGER_ABOUT_COMMENT, "website", FONT_MANAGER_ABOUT_HOMEPAGE, "authors", FONT_MANAGER_ABOUT_AUTHORS, "license", FONT_MANAGER_ABOUT_LICENSE, "translator-credits", FONT_MANAGER_ABOUT_TRANSLATORS, NULL, NULL);
	return;
}



