/* Main.c generated by valac 0.26.1, the Vala compiler
 * generated from Main.vala, do not modify */

/* Main.vala
 *
 * Copyright (C) 2009 - 2015 Jerry Casiano
 *
 * This file is part of Font Manager.
 *
 * Font Manager is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Font Manager is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Font Manager.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Author:
 *        Jerry Casiano <JerryCasiano@gmail.com>
*/

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gio/gio.h>
#include <stdlib.h>
#include <string.h>
#include <glib/gi18n-lib.h>
#include <gee.h>
#include <float.h>
#include <math.h>


#define FONT_MANAGER_TYPE_MAIN (font_manager_main_get_type ())
#define FONT_MANAGER_MAIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FONT_MANAGER_TYPE_MAIN, FontManagerMain))
#define FONT_MANAGER_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FONT_MANAGER_TYPE_MAIN, FontManagerMainClass))
#define FONT_MANAGER_IS_MAIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FONT_MANAGER_TYPE_MAIN))
#define FONT_MANAGER_IS_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FONT_MANAGER_TYPE_MAIN))
#define FONT_MANAGER_MAIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FONT_MANAGER_TYPE_MAIN, FontManagerMainClass))

typedef struct _FontManagerMain FontManagerMain;
typedef struct _FontManagerMainClass FontManagerMainClass;
typedef struct _FontManagerMainPrivate FontManagerMainPrivate;

#define FONT_MANAGER_TYPE_APPLICATION (font_manager_application_get_type ())
#define FONT_MANAGER_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FONT_MANAGER_TYPE_APPLICATION, FontManagerApplication))
#define FONT_MANAGER_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FONT_MANAGER_TYPE_APPLICATION, FontManagerApplicationClass))
#define FONT_MANAGER_IS_APPLICATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FONT_MANAGER_TYPE_APPLICATION))
#define FONT_MANAGER_IS_APPLICATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FONT_MANAGER_TYPE_APPLICATION))
#define FONT_MANAGER_APPLICATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FONT_MANAGER_TYPE_APPLICATION, FontManagerApplicationClass))

typedef struct _FontManagerApplication FontManagerApplication;
typedef struct _FontManagerApplicationClass FontManagerApplicationClass;

#define FONT_MANAGER_TYPE_DATABASE (font_manager_database_get_type ())
#define FONT_MANAGER_DATABASE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FONT_MANAGER_TYPE_DATABASE, FontManagerDatabase))
#define FONT_MANAGER_DATABASE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FONT_MANAGER_TYPE_DATABASE, FontManagerDatabaseClass))
#define FONT_MANAGER_IS_DATABASE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FONT_MANAGER_TYPE_DATABASE))
#define FONT_MANAGER_IS_DATABASE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FONT_MANAGER_TYPE_DATABASE))
#define FONT_MANAGER_DATABASE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FONT_MANAGER_TYPE_DATABASE, FontManagerDatabaseClass))

typedef struct _FontManagerDatabase FontManagerDatabase;
typedef struct _FontManagerDatabaseClass FontManagerDatabaseClass;

#define FONT_CONFIG_TYPE_MAIN (font_config_main_get_type ())
#define FONT_CONFIG_MAIN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FONT_CONFIG_TYPE_MAIN, FontConfigMain))
#define FONT_CONFIG_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FONT_CONFIG_TYPE_MAIN, FontConfigMainClass))
#define FONT_CONFIG_IS_MAIN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FONT_CONFIG_TYPE_MAIN))
#define FONT_CONFIG_IS_MAIN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FONT_CONFIG_TYPE_MAIN))
#define FONT_CONFIG_MAIN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FONT_CONFIG_TYPE_MAIN, FontConfigMainClass))

typedef struct _FontConfigMain FontConfigMain;
typedef struct _FontConfigMainClass FontConfigMainClass;

#define TYPE_CACHEABLE (cacheable_get_type ())
#define CACHEABLE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_CACHEABLE, Cacheable))
#define CACHEABLE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_CACHEABLE, CacheableClass))
#define IS_CACHEABLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_CACHEABLE))
#define IS_CACHEABLE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_CACHEABLE))
#define CACHEABLE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_CACHEABLE, CacheableClass))

typedef struct _Cacheable Cacheable;
typedef struct _CacheableClass CacheableClass;

#define FONT_MANAGER_TYPE_COLLECTIONS (font_manager_collections_get_type ())
#define FONT_MANAGER_COLLECTIONS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FONT_MANAGER_TYPE_COLLECTIONS, FontManagerCollections))
#define FONT_MANAGER_COLLECTIONS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FONT_MANAGER_TYPE_COLLECTIONS, FontManagerCollectionsClass))
#define FONT_MANAGER_IS_COLLECTIONS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FONT_MANAGER_TYPE_COLLECTIONS))
#define FONT_MANAGER_IS_COLLECTIONS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FONT_MANAGER_TYPE_COLLECTIONS))
#define FONT_MANAGER_COLLECTIONS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FONT_MANAGER_TYPE_COLLECTIONS, FontManagerCollectionsClass))

typedef struct _FontManagerCollections FontManagerCollections;
typedef struct _FontManagerCollectionsClass FontManagerCollectionsClass;

#define FONT_MANAGER_TYPE_CATEGORY_MODEL (font_manager_category_model_get_type ())
#define FONT_MANAGER_CATEGORY_MODEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FONT_MANAGER_TYPE_CATEGORY_MODEL, FontManagerCategoryModel))
#define FONT_MANAGER_CATEGORY_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FONT_MANAGER_TYPE_CATEGORY_MODEL, FontManagerCategoryModelClass))
#define FONT_MANAGER_IS_CATEGORY_MODEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FONT_MANAGER_TYPE_CATEGORY_MODEL))
#define FONT_MANAGER_IS_CATEGORY_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FONT_MANAGER_TYPE_CATEGORY_MODEL))
#define FONT_MANAGER_CATEGORY_MODEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FONT_MANAGER_TYPE_CATEGORY_MODEL, FontManagerCategoryModelClass))

typedef struct _FontManagerCategoryModel FontManagerCategoryModel;
typedef struct _FontManagerCategoryModelClass FontManagerCategoryModelClass;

#define FONT_MANAGER_TYPE_COLLECTION_MODEL (font_manager_collection_model_get_type ())
#define FONT_MANAGER_COLLECTION_MODEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FONT_MANAGER_TYPE_COLLECTION_MODEL, FontManagerCollectionModel))
#define FONT_MANAGER_COLLECTION_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FONT_MANAGER_TYPE_COLLECTION_MODEL, FontManagerCollectionModelClass))
#define FONT_MANAGER_IS_COLLECTION_MODEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FONT_MANAGER_TYPE_COLLECTION_MODEL))
#define FONT_MANAGER_IS_COLLECTION_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FONT_MANAGER_TYPE_COLLECTION_MODEL))
#define FONT_MANAGER_COLLECTION_MODEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FONT_MANAGER_TYPE_COLLECTION_MODEL, FontManagerCollectionModelClass))

typedef struct _FontManagerCollectionModel FontManagerCollectionModel;
typedef struct _FontManagerCollectionModelClass FontManagerCollectionModelClass;

#define FONT_MANAGER_TYPE_FONT_MODEL (font_manager_font_model_get_type ())
#define FONT_MANAGER_FONT_MODEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FONT_MANAGER_TYPE_FONT_MODEL, FontManagerFontModel))
#define FONT_MANAGER_FONT_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FONT_MANAGER_TYPE_FONT_MODEL, FontManagerFontModelClass))
#define FONT_MANAGER_IS_FONT_MODEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FONT_MANAGER_TYPE_FONT_MODEL))
#define FONT_MANAGER_IS_FONT_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FONT_MANAGER_TYPE_FONT_MODEL))
#define FONT_MANAGER_FONT_MODEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FONT_MANAGER_TYPE_FONT_MODEL, FontManagerFontModelClass))

typedef struct _FontManagerFontModel FontManagerFontModel;
typedef struct _FontManagerFontModelClass FontManagerFontModelClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

#define FONT_CONFIG_TYPE_FONT (font_config_font_get_type ())
#define FONT_CONFIG_FONT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FONT_CONFIG_TYPE_FONT, FontConfigFont))
#define FONT_CONFIG_FONT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FONT_CONFIG_TYPE_FONT, FontConfigFontClass))
#define FONT_CONFIG_IS_FONT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FONT_CONFIG_TYPE_FONT))
#define FONT_CONFIG_IS_FONT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FONT_CONFIG_TYPE_FONT))
#define FONT_CONFIG_FONT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FONT_CONFIG_TYPE_FONT, FontConfigFontClass))

typedef struct _FontConfigFont FontConfigFont;
typedef struct _FontConfigFontClass FontConfigFontClass;

#define FONT_CONFIG_TYPE_FAMILIES (font_config_families_get_type ())
#define FONT_CONFIG_FAMILIES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FONT_CONFIG_TYPE_FAMILIES, FontConfigFamilies))
#define FONT_CONFIG_FAMILIES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FONT_CONFIG_TYPE_FAMILIES, FontConfigFamiliesClass))
#define FONT_CONFIG_IS_FAMILIES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FONT_CONFIG_TYPE_FAMILIES))
#define FONT_CONFIG_IS_FAMILIES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FONT_CONFIG_TYPE_FAMILIES))
#define FONT_CONFIG_FAMILIES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FONT_CONFIG_TYPE_FAMILIES, FontConfigFamiliesClass))

typedef struct _FontConfigFamilies FontConfigFamilies;
typedef struct _FontConfigFamiliesClass FontConfigFamiliesClass;

#define FONT_MANAGER_TYPE_MAIN_WINDOW (font_manager_main_window_get_type ())
#define FONT_MANAGER_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FONT_MANAGER_TYPE_MAIN_WINDOW, FontManagerMainWindow))
#define FONT_MANAGER_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FONT_MANAGER_TYPE_MAIN_WINDOW, FontManagerMainWindowClass))
#define FONT_MANAGER_IS_MAIN_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FONT_MANAGER_TYPE_MAIN_WINDOW))
#define FONT_MANAGER_IS_MAIN_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FONT_MANAGER_TYPE_MAIN_WINDOW))
#define FONT_MANAGER_MAIN_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FONT_MANAGER_TYPE_MAIN_WINDOW, FontManagerMainWindowClass))

typedef struct _FontManagerMainWindow FontManagerMainWindow;
typedef struct _FontManagerMainWindowClass FontManagerMainWindowClass;

#define FONT_MANAGER_TYPE_FILTER (font_manager_filter_get_type ())
#define FONT_MANAGER_FILTER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FONT_MANAGER_TYPE_FILTER, FontManagerFilter))
#define FONT_MANAGER_FILTER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FONT_MANAGER_TYPE_FILTER, FontManagerFilterClass))
#define FONT_MANAGER_IS_FILTER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FONT_MANAGER_TYPE_FILTER))
#define FONT_MANAGER_IS_FILTER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FONT_MANAGER_TYPE_FILTER))
#define FONT_MANAGER_FILTER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FONT_MANAGER_TYPE_FILTER, FontManagerFilterClass))

typedef struct _FontManagerFilter FontManagerFilter;
typedef struct _FontManagerFilterClass FontManagerFilterClass;

#define FONT_CONFIG_TYPE_SELECTIONS (font_config_selections_get_type ())
#define FONT_CONFIG_SELECTIONS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FONT_CONFIG_TYPE_SELECTIONS, FontConfigSelections))
#define FONT_CONFIG_SELECTIONS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FONT_CONFIG_TYPE_SELECTIONS, FontConfigSelectionsClass))
#define FONT_CONFIG_IS_SELECTIONS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FONT_CONFIG_TYPE_SELECTIONS))
#define FONT_CONFIG_IS_SELECTIONS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FONT_CONFIG_TYPE_SELECTIONS))
#define FONT_CONFIG_SELECTIONS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FONT_CONFIG_TYPE_SELECTIONS, FontConfigSelectionsClass))

typedef struct _FontConfigSelections FontConfigSelections;
typedef struct _FontConfigSelectionsClass FontConfigSelectionsClass;

#define FONT_CONFIG_TYPE_REJECT (font_config_reject_get_type ())
#define FONT_CONFIG_REJECT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FONT_CONFIG_TYPE_REJECT, FontConfigReject))
#define FONT_CONFIG_REJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FONT_CONFIG_TYPE_REJECT, FontConfigRejectClass))
#define FONT_CONFIG_IS_REJECT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FONT_CONFIG_TYPE_REJECT))
#define FONT_CONFIG_IS_REJECT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FONT_CONFIG_TYPE_REJECT))
#define FONT_CONFIG_REJECT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FONT_CONFIG_TYPE_REJECT, FontConfigRejectClass))

typedef struct _FontConfigReject FontConfigReject;
typedef struct _FontConfigRejectClass FontConfigRejectClass;

#define FONT_MANAGER_TYPE_STATE (font_manager_state_get_type ())
#define FONT_MANAGER_STATE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FONT_MANAGER_TYPE_STATE, FontManagerState))
#define FONT_MANAGER_STATE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FONT_MANAGER_TYPE_STATE, FontManagerStateClass))
#define FONT_MANAGER_IS_STATE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FONT_MANAGER_TYPE_STATE))
#define FONT_MANAGER_IS_STATE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FONT_MANAGER_TYPE_STATE))
#define FONT_MANAGER_STATE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FONT_MANAGER_TYPE_STATE, FontManagerStateClass))

typedef struct _FontManagerState FontManagerState;
typedef struct _FontManagerStateClass FontManagerStateClass;

struct _FontManagerMain {
	GObject parent_instance;
	FontManagerMainPrivate * priv;
};

struct _FontManagerMainClass {
	GObjectClass parent_class;
};

struct _FontManagerMainPrivate {
	FontManagerApplication* _application;
	FontManagerDatabase* _database;
	GSettings* _settings;
	FontConfigMain* _fontconfig;
	FontManagerCollections* _collections;
	FontManagerCategoryModel* _category_model;
	FontManagerCollectionModel* _collection_model;
	FontManagerFontModel* _font_model;
	gboolean init_called;
	gboolean update_in_progress;
	gboolean queue_update;
};

typedef enum  {
	FONT_MANAGER_DATABASE_ERROR_ERROR,
	FONT_MANAGER_DATABASE_ERROR_BACKING,
	FONT_MANAGER_DATABASE_ERROR_MEMORY,
	FONT_MANAGER_DATABASE_ERROR_ABORT,
	FONT_MANAGER_DATABASE_ERROR_LIMITS,
	FONT_MANAGER_DATABASE_ERROR_TYPESPEC
} FontManagerDatabaseError;
#define FONT_MANAGER_DATABASE_ERROR font_manager_database_error_quark ()
typedef void (*ProgressCallback) (const gchar* message, gint processed, gint total, void* user_data);

static gpointer font_manager_main_parent_class = NULL;
static GOnce font_manager_main__instance;
static GOnce font_manager_main__instance = G_ONCE_INIT;

void font_manager_queue_reload (void);
static gboolean __lambda112_ (void);
GType font_manager_main_get_type (void) G_GNUC_CONST;
FontManagerMain* font_manager_main_get_instance (void);
void font_manager_main_update (FontManagerMain* self);
static gboolean ___lambda112__gsource_func (gpointer self);
GType font_manager_application_get_type (void) G_GNUC_CONST;
guint font_manager_application_register_object (void* object, GDBusConnection* connection, const gchar* path, GError** error);
GType font_manager_database_get_type (void) G_GNUC_CONST;
GType font_config_main_get_type (void) G_GNUC_CONST;
GType cacheable_get_type (void) G_GNUC_CONST;
GType font_manager_collections_get_type (void) G_GNUC_CONST;
GType font_manager_category_model_get_type (void) G_GNUC_CONST;
GType font_manager_collection_model_get_type (void) G_GNUC_CONST;
GType font_manager_font_model_get_type (void) G_GNUC_CONST;
#define FONT_MANAGER_MAIN_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), FONT_MANAGER_TYPE_MAIN, FontManagerMainPrivate))
enum  {
	FONT_MANAGER_MAIN_DUMMY_PROPERTY,
	FONT_MANAGER_MAIN_APPLICATION,
	FONT_MANAGER_MAIN_DATABASE,
	FONT_MANAGER_MAIN_SETTINGS,
	FONT_MANAGER_MAIN_FONTCONFIG,
	FONT_MANAGER_MAIN_COLLECTIONS,
	FONT_MANAGER_MAIN_CATEGORY_MODEL,
	FONT_MANAGER_MAIN_COLLECTION_MODEL,
	FONT_MANAGER_MAIN_FONT_MODEL
};
FontManagerMain* font_manager_main_new (void);
FontManagerMain* font_manager_main_construct (GType object_type);
void font_manager_main_init (FontManagerMain* self);
#define FONT_MANAGER_SCHEMA_ID "org.gnome.FontManager"
static void font_manager_main_set_settings (FontManagerMain* self, GSettings* value);
GQuark font_manager_database_error_quark (void);
FontManagerDatabase* font_manager_get_database (GError** error);
static void font_manager_main_set_database (FontManagerMain* self, FontManagerDatabase* value);
void font_manager_show_error_message (const gchar* message, GError* e, GtkWindow* parent);
FontManagerCollections* font_manager_load_collections (void);
static void font_manager_main_set_collections (FontManagerMain* self, FontManagerCollections* value);
FontConfigMain* font_config_main_new (void);
FontConfigMain* font_config_main_construct (GType object_type);
static void font_manager_main_set_fontconfig (FontManagerMain* self, FontConfigMain* value);
FontConfigMain* font_manager_main_get_fontconfig (FontManagerMain* self);
static void __lambda52_ (FontManagerMain* self, const gchar* m, gint p, gint t);
static void ___lambda52__font_config_main_progress (FontConfigMain* _sender, const gchar* message, gint processed, gint total, gpointer self);
static void __lambda53_ (FontManagerMain* self, GFile* f, GFileMonitorEvent ev);
static void ___lambda53__font_config_main_changed (FontConfigMain* _sender, GFile* file, GFileMonitorEvent event, gpointer self);
void font_config_main_init (FontConfigMain* self);
GType font_config_font_get_type (void) G_GNUC_CONST;
void font_manager_sync_fonts_table (FontManagerDatabase* db, GeeArrayList* installed_fonts, ProgressCallback progress, void* progress_target, GError** error);
FontManagerDatabase* font_manager_main_get_database (FontManagerMain* self);
GeeArrayList* font_config_list_fonts (const gchar* family_name);
static void ___lambda84_ (FontManagerMain* self, const gchar* m, gint p, gint t);
static void ____lambda84__progress_callback (const gchar* message, gint processed, gint total, gpointer self);
void font_manager_main_init_ui (FontManagerMain* self);
FontManagerCategoryModel* font_manager_category_model_new (void);
FontManagerCategoryModel* font_manager_category_model_construct (GType object_type);
void font_manager_main_set_category_model (FontManagerMain* self, FontManagerCategoryModel* value);
FontManagerCollectionModel* font_manager_collection_model_new (void);
FontManagerCollectionModel* font_manager_collection_model_construct (GType object_type);
void font_manager_main_set_collection_model (FontManagerMain* self, FontManagerCollectionModel* value);
FontManagerFontModel* font_manager_font_model_new (void);
FontManagerFontModel* font_manager_font_model_construct (GType object_type);
void font_manager_main_set_font_model (FontManagerMain* self, FontManagerFontModel* value);
FontManagerCategoryModel* font_manager_main_get_category_model (FontManagerMain* self);
void font_manager_category_model_set_database (FontManagerCategoryModel* self, FontManagerDatabase* value);
FontManagerCollectionModel* font_manager_main_get_collection_model (FontManagerMain* self);
FontManagerCollections* font_manager_main_get_collections (FontManagerMain* self);
void font_manager_collection_model_set_collections (FontManagerCollectionModel* self, FontManagerCollections* value);
FontManagerFontModel* font_manager_main_get_font_model (FontManagerMain* self);
GType font_config_families_get_type (void) G_GNUC_CONST;
FontConfigFamilies* font_config_main_get_families (FontConfigMain* self);
void font_manager_font_model_set_families (FontManagerFontModel* self, FontConfigFamilies* value);
static void font_manager_main_start_update (FontManagerMain* self);
FontManagerApplication* font_manager_main_get_application (FontManagerMain* self);
GType font_manager_main_window_get_type (void) G_GNUC_CONST;
FontManagerMainWindow* font_manager_application_get_main_window (FontManagerApplication* self);
void font_manager_main_window_unset_all_models (FontManagerMainWindow* self);
void font_manager_main_window_set_loading (FontManagerMainWindow* self, gboolean value);
static void font_manager_main_end_update (FontManagerMain* self);
static void ___lambda71_ (FontManagerMain* self, const gchar* m, gint p, gint t);
static void ____lambda71__progress_callback (const gchar* message, gint processed, gint total, gpointer self);
void font_manager_category_model_update (FontManagerCategoryModel* self);
GType font_manager_filter_get_type (void) G_GNUC_CONST;
void font_manager_font_model_update (FontManagerFontModel* self, FontManagerFilter* filter);
void font_manager_main_window_set_all_models (FontManagerMainWindow* self);
static gboolean ___lambda83_ (FontManagerMain* self);
static gboolean ____lambda83__gsource_func (gpointer self);
gboolean font_config_update_cache (void);
void font_config_main_async_update (FontConfigMain* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
gboolean font_config_main_async_update_finish (FontConfigMain* self, GAsyncResult* _res_, GError** error);
static void __lambda54_ (FontManagerMain* self, GObject* obj, GAsyncResult* res);
static void ___lambda54__gasync_ready_callback (GObject* source_object, GAsyncResult* res, gpointer self);
void font_manager_main_on_activate (FontManagerMain* self);
void font_manager_main_set_application (FontManagerMain* self, FontManagerApplication* value);
FontManagerMainWindow* font_manager_main_window_new (void);
FontManagerMainWindow* font_manager_main_window_construct (GType object_type);
void font_manager_application_set_main_window (FontManagerApplication* self, FontManagerMainWindow* value);
#define FONT_MANAGER_ABOUT_ICON "font-x-generic"
static void __lambda85_ (FontManagerMain* self, const gchar* m, gint p, gint t);
void font_manager_main_window_set_progress (FontManagerMainWindow* self, gdouble value);
void ensure_ui_update (void);
static void ___lambda85__font_manager_main_progress (FontManagerMain* _sender, const gchar* message, gint processed, gint total, gpointer self);
GType font_config_selections_get_type (void) G_GNUC_CONST;
GType font_config_reject_get_type (void) G_GNUC_CONST;
FontConfigReject* font_config_main_get_reject (FontConfigMain* self);
void font_manager_main_window_set_reject (FontManagerMainWindow* self, FontConfigReject* value);
GType font_manager_state_get_type (void) G_GNUC_CONST;
FontManagerState* font_manager_main_window_get_state (FontManagerMainWindow* self);
void font_manager_state_bind_settings (FontManagerState* self);
void font_manager_state_post_activate (FontManagerState* self);
static FontManagerMain* _font_manager_main_instance___lambda43_ (void);
static gpointer __font_manager_main_instance___lambda43__gthread_func (gpointer self);
GSettings* font_manager_main_get_settings (FontManagerMain* self);
static void g_cclosure_user_marshal_VOID__STRING_INT_INT (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data);
static void font_manager_main_finalize (GObject* obj);
static void _vala_font_manager_main_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_font_manager_main_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


static gboolean __lambda112_ (void) {
	gboolean result = FALSE;
	FontManagerMain* _tmp0_ = NULL;
	FontManagerMain* _tmp1_ = NULL;
	_tmp0_ = font_manager_main_get_instance ();
	_tmp1_ = _tmp0_;
	font_manager_main_update (_tmp1_);
	result = FALSE;
	return result;
}


static gboolean ___lambda112__gsource_func (gpointer self) {
	gboolean result;
	result = __lambda112_ ();
	return result;
}


void font_manager_queue_reload (void) {
	g_timeout_add_seconds_full (G_PRIORITY_DEFAULT, (guint) 3, ___lambda112__gsource_func, NULL, NULL);
	return;
}


FontManagerMain* font_manager_main_construct (GType object_type) {
	FontManagerMain * self = NULL;
	self = (FontManagerMain*) g_object_new (object_type, NULL);
	return self;
}


FontManagerMain* font_manager_main_new (void) {
	return font_manager_main_construct (FONT_MANAGER_TYPE_MAIN);
}


static void __lambda52_ (FontManagerMain* self, const gchar* m, gint p, gint t) {
	const gchar* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	_tmp0_ = m;
	_tmp1_ = p;
	_tmp2_ = t;
	g_signal_emit_by_name (self, "progress", _tmp0_, _tmp1_, _tmp2_);
}


static void ___lambda52__font_config_main_progress (FontConfigMain* _sender, const gchar* message, gint processed, gint total, gpointer self) {
	__lambda52_ ((FontManagerMain*) self, message, processed, total);
}


static void __lambda53_ (FontManagerMain* self, GFile* f, GFileMonitorEvent ev) {
	g_debug ("Main.vala:76: Change detected");
	font_manager_main_update (self);
}


static void ___lambda53__font_config_main_changed (FontConfigMain* _sender, GFile* file, GFileMonitorEvent event, gpointer self) {
	__lambda53_ ((FontManagerMain*) self, file, event);
}


static void ___lambda84_ (FontManagerMain* self, const gchar* m, gint p, gint t) {
	const gchar* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	_tmp0_ = m;
	_tmp1_ = p;
	_tmp2_ = t;
	g_signal_emit_by_name (self, "progress", _tmp0_, _tmp1_, _tmp2_);
}


static void ____lambda84__progress_callback (const gchar* message, gint processed, gint total, gpointer self) {
	___lambda84_ ((FontManagerMain*) self, message, processed, total);
}


void font_manager_main_init (FontManagerMain* self) {
	gboolean _tmp0_ = FALSE;
	GSettings* _tmp1_ = NULL;
	GSettings* _tmp2_ = NULL;
	FontManagerCollections* _tmp9_ = NULL;
	FontManagerCollections* _tmp10_ = NULL;
	FontConfigMain* _tmp11_ = NULL;
	FontConfigMain* _tmp12_ = NULL;
	FontConfigMain* _tmp13_ = NULL;
	FontConfigMain* _tmp14_ = NULL;
	FontConfigMain* _tmp15_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->init_called;
	if (_tmp0_) {
		return;
	}
	_tmp1_ = g_settings_new (FONT_MANAGER_SCHEMA_ID);
	_tmp2_ = _tmp1_;
	font_manager_main_set_settings (self, _tmp2_);
	_g_object_unref0 (_tmp2_);
	{
		FontManagerDatabase* _tmp3_ = NULL;
		FontManagerDatabase* _tmp4_ = NULL;
		_tmp4_ = font_manager_get_database (&_inner_error_);
		_tmp3_ = _tmp4_;
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			if (_inner_error_->domain == FONT_MANAGER_DATABASE_ERROR) {
				goto __catch24_font_manager_database_error;
			}
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
		font_manager_main_set_database (self, _tmp3_);
		_g_object_unref0 (_tmp3_);
	}
	goto __finally24;
	__catch24_font_manager_database_error:
	{
		GError* e = NULL;
		GError* _tmp5_ = NULL;
		const gchar* _tmp6_ = NULL;
		const gchar* _tmp7_ = NULL;
		GError* _tmp8_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp5_ = e;
		_tmp6_ = _tmp5_->message;
		g_critical ("Main.vala:69: Failed to initialize database : %s", _tmp6_);
		_tmp7_ = _ ("There was an error accessing the database");
		_tmp8_ = e;
		font_manager_show_error_message (_tmp7_, _tmp8_, NULL);
		_g_error_free0 (e);
	}
	__finally24:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp9_ = font_manager_load_collections ();
	_tmp10_ = _tmp9_;
	font_manager_main_set_collections (self, _tmp10_);
	_g_object_unref0 (_tmp10_);
	_tmp11_ = font_config_main_new ();
	_tmp12_ = _tmp11_;
	font_manager_main_set_fontconfig (self, _tmp12_);
	_g_object_unref0 (_tmp12_);
	_tmp13_ = self->priv->_fontconfig;
	g_signal_connect_object (_tmp13_, "progress", (GCallback) ___lambda52__font_config_main_progress, self, 0);
	_tmp14_ = self->priv->_fontconfig;
	g_signal_connect_object (_tmp14_, "changed", (GCallback) ___lambda53__font_config_main_changed, self, 0);
	_tmp15_ = self->priv->_fontconfig;
	font_config_main_init (_tmp15_);
	{
		FontManagerDatabase* _tmp16_ = NULL;
		GeeArrayList* _tmp17_ = NULL;
		GeeArrayList* _tmp18_ = NULL;
		_tmp16_ = self->priv->_database;
		_tmp17_ = font_config_list_fonts (NULL);
		_tmp18_ = _tmp17_;
		font_manager_sync_fonts_table (_tmp16_, _tmp18_, ____lambda84__progress_callback, self, &_inner_error_);
		_g_object_unref0 (_tmp18_);
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			if (_inner_error_->domain == FONT_MANAGER_DATABASE_ERROR) {
				goto __catch25_font_manager_database_error;
			}
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
	}
	goto __finally25;
	__catch25_font_manager_database_error:
	{
		GError* e = NULL;
		GError* _tmp19_ = NULL;
		const gchar* _tmp20_ = NULL;
		const gchar* _tmp21_ = NULL;
		GError* _tmp22_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp19_ = e;
		_tmp20_ = _tmp19_->message;
		g_critical ("Main.vala:83: Database synchronization failed : %s", _tmp20_);
		_tmp21_ = _ ("There was an error accessing the database");
		_tmp22_ = e;
		font_manager_show_error_message (_tmp21_, _tmp22_, NULL);
		_g_error_free0 (e);
	}
	__finally25:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	self->priv->init_called = TRUE;
	return;
}


void font_manager_main_init_ui (FontManagerMain* self) {
	gboolean _tmp0_ = FALSE;
	FontManagerCategoryModel* _tmp1_ = NULL;
	FontManagerCategoryModel* _tmp2_ = NULL;
	FontManagerCollectionModel* _tmp3_ = NULL;
	FontManagerCollectionModel* _tmp4_ = NULL;
	FontManagerFontModel* _tmp5_ = NULL;
	FontManagerFontModel* _tmp6_ = NULL;
	FontManagerCategoryModel* _tmp7_ = NULL;
	FontManagerDatabase* _tmp8_ = NULL;
	FontManagerCollectionModel* _tmp9_ = NULL;
	FontManagerCollections* _tmp10_ = NULL;
	FontManagerFontModel* _tmp11_ = NULL;
	FontConfigMain* _tmp12_ = NULL;
	FontConfigFamilies* _tmp13_ = NULL;
	FontConfigFamilies* _tmp14_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->init_called;
	if (!_tmp0_) {
		font_manager_main_init (self);
	}
	_tmp1_ = font_manager_category_model_new ();
	_tmp2_ = _tmp1_;
	font_manager_main_set_category_model (self, _tmp2_);
	_g_object_unref0 (_tmp2_);
	_tmp3_ = font_manager_collection_model_new ();
	_tmp4_ = _tmp3_;
	font_manager_main_set_collection_model (self, _tmp4_);
	_g_object_unref0 (_tmp4_);
	_tmp5_ = font_manager_font_model_new ();
	_tmp6_ = _tmp5_;
	font_manager_main_set_font_model (self, _tmp6_);
	_g_object_unref0 (_tmp6_);
	_tmp7_ = self->priv->_category_model;
	_tmp8_ = self->priv->_database;
	font_manager_category_model_set_database (_tmp7_, _tmp8_);
	_tmp9_ = self->priv->_collection_model;
	_tmp10_ = self->priv->_collections;
	font_manager_collection_model_set_collections (_tmp9_, _tmp10_);
	_tmp11_ = self->priv->_font_model;
	_tmp12_ = self->priv->_fontconfig;
	_tmp13_ = font_config_main_get_families (_tmp12_);
	_tmp14_ = _tmp13_;
	font_manager_font_model_set_families (_tmp11_, _tmp14_);
	return;
}


static void font_manager_main_start_update (FontManagerMain* self) {
	gboolean _tmp0_ = FALSE;
	FontManagerApplication* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp1_ = self->priv->_application;
	if (_tmp1_ != NULL) {
		FontManagerApplication* _tmp2_ = NULL;
		FontManagerMainWindow* _tmp3_ = NULL;
		FontManagerMainWindow* _tmp4_ = NULL;
		_tmp2_ = self->priv->_application;
		_tmp3_ = font_manager_application_get_main_window (_tmp2_);
		_tmp4_ = _tmp3_;
		_tmp0_ = _tmp4_ != NULL;
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		FontManagerApplication* _tmp5_ = NULL;
		FontManagerMainWindow* _tmp6_ = NULL;
		FontManagerMainWindow* _tmp7_ = NULL;
		FontManagerApplication* _tmp8_ = NULL;
		FontManagerMainWindow* _tmp9_ = NULL;
		FontManagerMainWindow* _tmp10_ = NULL;
		_tmp5_ = self->priv->_application;
		_tmp6_ = font_manager_application_get_main_window (_tmp5_);
		_tmp7_ = _tmp6_;
		font_manager_main_window_unset_all_models (_tmp7_);
		_tmp8_ = self->priv->_application;
		_tmp9_ = font_manager_application_get_main_window (_tmp8_);
		_tmp10_ = _tmp9_;
		font_manager_main_window_set_loading (_tmp10_, TRUE);
	}
	return;
}


static void ___lambda71_ (FontManagerMain* self, const gchar* m, gint p, gint t) {
	const gchar* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	_tmp0_ = m;
	_tmp1_ = p;
	_tmp2_ = t;
	g_signal_emit_by_name (self, "progress", _tmp0_, _tmp1_, _tmp2_);
}


static void ____lambda71__progress_callback (const gchar* message, gint processed, gint total, gpointer self) {
	___lambda71_ ((FontManagerMain*) self, message, processed, total);
}


static gboolean ___lambda83_ (FontManagerMain* self) {
	gboolean result = FALSE;
	font_manager_main_update (self);
	result = FALSE;
	return result;
}


static gboolean ____lambda83__gsource_func (gpointer self) {
	gboolean result;
	result = ___lambda83_ ((FontManagerMain*) self);
	return result;
}


static void font_manager_main_end_update (FontManagerMain* self) {
	gboolean _tmp7_ = FALSE;
	FontManagerApplication* _tmp8_ = NULL;
	gboolean _tmp20_ = FALSE;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	{
		FontManagerDatabase* _tmp0_ = NULL;
		GeeArrayList* _tmp1_ = NULL;
		GeeArrayList* _tmp2_ = NULL;
		_tmp0_ = self->priv->_database;
		_tmp1_ = font_config_list_fonts (NULL);
		_tmp2_ = _tmp1_;
		font_manager_sync_fonts_table (_tmp0_, _tmp2_, ____lambda71__progress_callback, self, &_inner_error_);
		_g_object_unref0 (_tmp2_);
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			if (_inner_error_->domain == FONT_MANAGER_DATABASE_ERROR) {
				goto __catch26_font_manager_database_error;
			}
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
	}
	goto __finally26;
	__catch26_font_manager_database_error:
	{
		GError* e = NULL;
		GError* _tmp3_ = NULL;
		const gchar* _tmp4_ = NULL;
		const gchar* _tmp5_ = NULL;
		GError* _tmp6_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp3_ = e;
		_tmp4_ = _tmp3_->message;
		g_critical ("Main.vala:114: Database synchronization failed : %s", _tmp4_);
		_tmp5_ = _ ("There was an error accessing the database");
		_tmp6_ = e;
		font_manager_show_error_message (_tmp5_, _tmp6_, NULL);
		_g_error_free0 (e);
	}
	__finally26:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
	_tmp8_ = self->priv->_application;
	if (_tmp8_ != NULL) {
		FontManagerApplication* _tmp9_ = NULL;
		FontManagerMainWindow* _tmp10_ = NULL;
		FontManagerMainWindow* _tmp11_ = NULL;
		_tmp9_ = self->priv->_application;
		_tmp10_ = font_manager_application_get_main_window (_tmp9_);
		_tmp11_ = _tmp10_;
		_tmp7_ = _tmp11_ != NULL;
	} else {
		_tmp7_ = FALSE;
	}
	if (_tmp7_) {
		FontManagerCategoryModel* _tmp12_ = NULL;
		FontManagerFontModel* _tmp13_ = NULL;
		FontManagerApplication* _tmp14_ = NULL;
		FontManagerMainWindow* _tmp15_ = NULL;
		FontManagerMainWindow* _tmp16_ = NULL;
		FontManagerApplication* _tmp17_ = NULL;
		FontManagerMainWindow* _tmp18_ = NULL;
		FontManagerMainWindow* _tmp19_ = NULL;
		_tmp12_ = self->priv->_category_model;
		font_manager_category_model_update (_tmp12_);
		_tmp13_ = self->priv->_font_model;
		font_manager_font_model_update (_tmp13_, NULL);
		_tmp14_ = self->priv->_application;
		_tmp15_ = font_manager_application_get_main_window (_tmp14_);
		_tmp16_ = _tmp15_;
		font_manager_main_window_set_loading (_tmp16_, FALSE);
		_tmp17_ = self->priv->_application;
		_tmp18_ = font_manager_application_get_main_window (_tmp17_);
		_tmp19_ = _tmp18_;
		font_manager_main_window_set_all_models (_tmp19_);
	}
	self->priv->update_in_progress = FALSE;
	_tmp20_ = self->priv->queue_update;
	if (_tmp20_) {
		g_idle_add_full (G_PRIORITY_DEFAULT_IDLE, ____lambda83__gsource_func, g_object_ref (self), g_object_unref);
	}
	return;
}


static void __lambda54_ (FontManagerMain* self, GObject* obj, GAsyncResult* res) {
	GError * _inner_error_ = NULL;
	g_return_if_fail (res != NULL);
	{
		FontConfigMain* _tmp0_ = NULL;
		GAsyncResult* _tmp1_ = NULL;
		font_manager_main_start_update (self);
		_tmp0_ = self->priv->_fontconfig;
		_tmp1_ = res;
		font_config_main_async_update_finish (_tmp0_, _tmp1_, &_inner_error_);
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			if (_inner_error_->domain == G_THREAD_ERROR) {
				goto __catch27_g_thread_error;
			}
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
		font_manager_main_end_update (self);
		g_debug ("Main.vala:148: Font configuration update complete");
	}
	goto __finally27;
	__catch27_g_thread_error:
	{
		GError* e = NULL;
		GError* _tmp2_ = NULL;
		const gchar* _tmp3_ = NULL;
		const gchar* _tmp4_ = NULL;
		GError* _tmp5_ = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		_tmp2_ = e;
		_tmp3_ = _tmp2_->message;
		g_critical ("Main.vala:150: Thread error : %s", _tmp3_);
		font_manager_main_end_update (self);
		_tmp4_ = _ ("Try restarting the application\n" \
"There was an error updating font information");
		_tmp5_ = e;
		font_manager_show_error_message (_tmp4_, _tmp5_, NULL);
		_g_error_free0 (e);
	}
	__finally27:
	if (G_UNLIKELY (_inner_error_ != NULL)) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return;
	}
}


static void ___lambda54__gasync_ready_callback (GObject* source_object, GAsyncResult* res, gpointer self) {
	__lambda54_ ((FontManagerMain*) self, source_object, res);
	g_object_unref (self);
}


void font_manager_main_update (FontManagerMain* self) {
	gboolean _tmp0_ = FALSE;
	gboolean _tmp1_ = FALSE;
	FontConfigMain* _tmp2_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->init_called;
	if (!_tmp0_) {
		font_manager_main_init (self);
		return;
	}
	_tmp1_ = self->priv->update_in_progress;
	if (_tmp1_) {
		self->priv->queue_update = TRUE;
		return;
	} else {
		self->priv->queue_update = FALSE;
	}
	self->priv->update_in_progress = TRUE;
	g_debug ("Main.vala:141: Updating font configuration");
	font_config_update_cache ();
	_tmp2_ = self->priv->_fontconfig;
	font_config_main_async_update (_tmp2_, ___lambda54__gasync_ready_callback, g_object_ref (self));
	return;
}


static void __lambda85_ (FontManagerMain* self, const gchar* m, gint p, gint t) {
	FontManagerApplication* _tmp0_ = NULL;
	FontManagerMainWindow* _tmp1_ = NULL;
	FontManagerMainWindow* _tmp2_ = NULL;
	gint _tmp3_ = 0;
	gint _tmp4_ = 0;
	_tmp0_ = self->priv->_application;
	_tmp1_ = font_manager_application_get_main_window (_tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = p;
	_tmp4_ = t;
	font_manager_main_window_set_progress (_tmp2_, (gdouble) (((gfloat) _tmp3_) / ((gfloat) _tmp4_)));
	ensure_ui_update ();
}


static void ___lambda85__font_manager_main_progress (FontManagerMain* _sender, const gchar* message, gint processed, gint total, gpointer self) {
	__lambda85_ ((FontManagerMain*) self, message, processed, total);
}


void font_manager_main_on_activate (FontManagerMain* self) {
	gboolean _tmp0_ = FALSE;
	FontManagerApplication* _tmp1_ = NULL;
	GApplication* _tmp8_ = NULL;
	FontManagerApplication* _tmp9_ = NULL;
	FontManagerMainWindow* _tmp10_ = NULL;
	FontManagerMainWindow* _tmp11_ = NULL;
	FontManagerApplication* _tmp12_ = NULL;
	FontManagerMainWindow* _tmp13_ = NULL;
	FontManagerMainWindow* _tmp14_ = NULL;
	FontManagerApplication* _tmp15_ = NULL;
	FontManagerApplication* _tmp16_ = NULL;
	FontManagerMainWindow* _tmp17_ = NULL;
	FontManagerMainWindow* _tmp18_ = NULL;
	FontManagerApplication* _tmp19_ = NULL;
	FontManagerMainWindow* _tmp20_ = NULL;
	FontManagerMainWindow* _tmp21_ = NULL;
	FontManagerApplication* _tmp22_ = NULL;
	FontManagerMainWindow* _tmp23_ = NULL;
	FontManagerMainWindow* _tmp24_ = NULL;
	FontManagerApplication* _tmp25_ = NULL;
	FontManagerMainWindow* _tmp26_ = NULL;
	FontManagerMainWindow* _tmp27_ = NULL;
	FontConfigMain* _tmp28_ = NULL;
	FontConfigReject* _tmp29_ = NULL;
	FontConfigReject* _tmp30_ = NULL;
	FontManagerApplication* _tmp31_ = NULL;
	FontManagerMainWindow* _tmp32_ = NULL;
	FontManagerMainWindow* _tmp33_ = NULL;
	FontManagerApplication* _tmp34_ = NULL;
	FontManagerMainWindow* _tmp35_ = NULL;
	FontManagerMainWindow* _tmp36_ = NULL;
	FontManagerApplication* _tmp37_ = NULL;
	FontManagerMainWindow* _tmp38_ = NULL;
	FontManagerMainWindow* _tmp39_ = NULL;
	FontManagerState* _tmp40_ = NULL;
	FontManagerState* _tmp41_ = NULL;
	FontManagerApplication* _tmp42_ = NULL;
	FontManagerMainWindow* _tmp43_ = NULL;
	FontManagerMainWindow* _tmp44_ = NULL;
	FontManagerState* _tmp45_ = NULL;
	FontManagerState* _tmp46_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp1_ = self->priv->_application;
	if (_tmp1_ != NULL) {
		FontManagerApplication* _tmp2_ = NULL;
		FontManagerMainWindow* _tmp3_ = NULL;
		FontManagerMainWindow* _tmp4_ = NULL;
		_tmp2_ = self->priv->_application;
		_tmp3_ = font_manager_application_get_main_window (_tmp2_);
		_tmp4_ = _tmp3_;
		_tmp0_ = _tmp4_ != NULL;
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		FontManagerApplication* _tmp5_ = NULL;
		FontManagerMainWindow* _tmp6_ = NULL;
		FontManagerMainWindow* _tmp7_ = NULL;
		_tmp5_ = self->priv->_application;
		_tmp6_ = font_manager_application_get_main_window (_tmp5_);
		_tmp7_ = _tmp6_;
		gtk_window_present ((GtkWindow*) _tmp7_);
		return;
	}
	font_manager_main_init (self);
	_tmp8_ = g_application_get_default ();
	font_manager_main_set_application (self, G_TYPE_CHECK_INSTANCE_CAST (_tmp8_, FONT_MANAGER_TYPE_APPLICATION, FontManagerApplication));
	_tmp9_ = self->priv->_application;
	_tmp10_ = font_manager_main_window_new ();
	g_object_ref_sink (_tmp10_);
	_tmp11_ = _tmp10_;
	font_manager_application_set_main_window (_tmp9_, _tmp11_);
	_g_object_unref0 (_tmp11_);
	_tmp12_ = self->priv->_application;
	_tmp13_ = font_manager_application_get_main_window (_tmp12_);
	_tmp14_ = _tmp13_;
	gtk_window_set_icon_name ((GtkWindow*) _tmp14_, FONT_MANAGER_ABOUT_ICON);
	_tmp15_ = self->priv->_application;
	_tmp16_ = self->priv->_application;
	_tmp17_ = font_manager_application_get_main_window (_tmp16_);
	_tmp18_ = _tmp17_;
	gtk_application_add_window ((GtkApplication*) _tmp15_, (GtkWindow*) _tmp18_);
	_tmp19_ = self->priv->_application;
	_tmp20_ = font_manager_application_get_main_window (_tmp19_);
	_tmp21_ = _tmp20_;
	font_manager_main_window_set_loading (_tmp21_, TRUE);
	_tmp22_ = self->priv->_application;
	_tmp23_ = font_manager_application_get_main_window (_tmp22_);
	_tmp24_ = _tmp23_;
	gtk_window_present ((GtkWindow*) _tmp24_);
	g_signal_connect_object (self, "progress", (GCallback) ___lambda85__font_manager_main_progress, self, 0);
	font_manager_main_init_ui (self);
	_tmp25_ = self->priv->_application;
	_tmp26_ = font_manager_application_get_main_window (_tmp25_);
	_tmp27_ = _tmp26_;
	_tmp28_ = self->priv->_fontconfig;
	_tmp29_ = font_config_main_get_reject (_tmp28_);
	_tmp30_ = _tmp29_;
	font_manager_main_window_set_reject (_tmp27_, _tmp30_);
	_tmp31_ = self->priv->_application;
	_tmp32_ = font_manager_application_get_main_window (_tmp31_);
	_tmp33_ = _tmp32_;
	font_manager_main_window_set_all_models (_tmp33_);
	_tmp34_ = self->priv->_application;
	_tmp35_ = font_manager_application_get_main_window (_tmp34_);
	_tmp36_ = _tmp35_;
	font_manager_main_window_set_loading (_tmp36_, FALSE);
	_tmp37_ = self->priv->_application;
	_tmp38_ = font_manager_application_get_main_window (_tmp37_);
	_tmp39_ = _tmp38_;
	_tmp40_ = font_manager_main_window_get_state (_tmp39_);
	_tmp41_ = _tmp40_;
	font_manager_state_bind_settings (_tmp41_);
	_tmp42_ = self->priv->_application;
	_tmp43_ = font_manager_application_get_main_window (_tmp42_);
	_tmp44_ = _tmp43_;
	_tmp45_ = font_manager_main_window_get_state (_tmp44_);
	_tmp46_ = _tmp45_;
	font_manager_state_post_activate (_tmp46_);
	return;
}


static FontManagerMain* _font_manager_main_instance___lambda43_ (void) {
	FontManagerMain* result = NULL;
	FontManagerMain* _tmp0_ = NULL;
	_tmp0_ = font_manager_main_new ();
	result = _tmp0_;
	return result;
}


static gpointer __font_manager_main_instance___lambda43__gthread_func (gpointer self) {
	gpointer result;
	result = _font_manager_main_instance___lambda43_ ();
	return result;
}


FontManagerMain* font_manager_main_get_instance (void) {
	FontManagerMain* result;
	gconstpointer _tmp0_ = NULL;
	_tmp0_ = g_once (&font_manager_main__instance, __font_manager_main_instance___lambda43__gthread_func, NULL);
	result = (FontManagerMain*) _tmp0_;
	return result;
}


FontManagerApplication* font_manager_main_get_application (FontManagerMain* self) {
	FontManagerApplication* result;
	FontManagerApplication* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_application;
	result = _tmp0_;
	return result;
}


void font_manager_main_set_application (FontManagerMain* self, FontManagerApplication* value) {
	FontManagerApplication* _tmp0_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_application = _tmp0_;
	g_object_notify ((GObject *) self, "application");
}


FontManagerDatabase* font_manager_main_get_database (FontManagerMain* self) {
	FontManagerDatabase* result;
	FontManagerDatabase* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_database;
	result = _tmp0_;
	return result;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void font_manager_main_set_database (FontManagerMain* self, FontManagerDatabase* value) {
	FontManagerDatabase* _tmp0_ = NULL;
	FontManagerDatabase* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_database);
	self->priv->_database = _tmp1_;
	g_object_notify ((GObject *) self, "database");
}


GSettings* font_manager_main_get_settings (FontManagerMain* self) {
	GSettings* result;
	GSettings* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_settings;
	result = _tmp0_;
	return result;
}


static void font_manager_main_set_settings (FontManagerMain* self, GSettings* value) {
	GSettings* _tmp0_ = NULL;
	GSettings* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_settings);
	self->priv->_settings = _tmp1_;
	g_object_notify ((GObject *) self, "settings");
}


FontConfigMain* font_manager_main_get_fontconfig (FontManagerMain* self) {
	FontConfigMain* result;
	FontConfigMain* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_fontconfig;
	result = _tmp0_;
	return result;
}


static void font_manager_main_set_fontconfig (FontManagerMain* self, FontConfigMain* value) {
	FontConfigMain* _tmp0_ = NULL;
	FontConfigMain* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_fontconfig);
	self->priv->_fontconfig = _tmp1_;
	g_object_notify ((GObject *) self, "fontconfig");
}


FontManagerCollections* font_manager_main_get_collections (FontManagerMain* self) {
	FontManagerCollections* result;
	FontManagerCollections* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_collections;
	result = _tmp0_;
	return result;
}


static void font_manager_main_set_collections (FontManagerMain* self, FontManagerCollections* value) {
	FontManagerCollections* _tmp0_ = NULL;
	FontManagerCollections* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_collections);
	self->priv->_collections = _tmp1_;
	g_object_notify ((GObject *) self, "collections");
}


FontManagerCategoryModel* font_manager_main_get_category_model (FontManagerMain* self) {
	FontManagerCategoryModel* result;
	FontManagerCategoryModel* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_category_model;
	result = _tmp0_;
	return result;
}


void font_manager_main_set_category_model (FontManagerMain* self, FontManagerCategoryModel* value) {
	FontManagerCategoryModel* _tmp0_ = NULL;
	FontManagerCategoryModel* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_category_model);
	self->priv->_category_model = _tmp1_;
	g_object_notify ((GObject *) self, "category-model");
}


FontManagerCollectionModel* font_manager_main_get_collection_model (FontManagerMain* self) {
	FontManagerCollectionModel* result;
	FontManagerCollectionModel* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_collection_model;
	result = _tmp0_;
	return result;
}


void font_manager_main_set_collection_model (FontManagerMain* self, FontManagerCollectionModel* value) {
	FontManagerCollectionModel* _tmp0_ = NULL;
	FontManagerCollectionModel* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_collection_model);
	self->priv->_collection_model = _tmp1_;
	g_object_notify ((GObject *) self, "collection-model");
}


FontManagerFontModel* font_manager_main_get_font_model (FontManagerMain* self) {
	FontManagerFontModel* result;
	FontManagerFontModel* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_font_model;
	result = _tmp0_;
	return result;
}


void font_manager_main_set_font_model (FontManagerMain* self, FontManagerFontModel* value) {
	FontManagerFontModel* _tmp0_ = NULL;
	FontManagerFontModel* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_font_model);
	self->priv->_font_model = _tmp1_;
	g_object_notify ((GObject *) self, "font-model");
}


static void g_cclosure_user_marshal_VOID__STRING_INT_INT (GClosure * closure, GValue * return_value, guint n_param_values, const GValue * param_values, gpointer invocation_hint, gpointer marshal_data) {
	typedef void (*GMarshalFunc_VOID__STRING_INT_INT) (gpointer data1, const char* arg_1, gint arg_2, gint arg_3, gpointer data2);
	register GMarshalFunc_VOID__STRING_INT_INT callback;
	register GCClosure * cc;
	register gpointer data1;
	register gpointer data2;
	cc = (GCClosure *) closure;
	g_return_if_fail (n_param_values == 4);
	if (G_CCLOSURE_SWAP_DATA (closure)) {
		data1 = closure->data;
		data2 = param_values->data[0].v_pointer;
	} else {
		data1 = param_values->data[0].v_pointer;
		data2 = closure->data;
	}
	callback = (GMarshalFunc_VOID__STRING_INT_INT) (marshal_data ? marshal_data : cc->callback);
	callback (data1, g_value_get_string (param_values + 1), g_value_get_int (param_values + 2), g_value_get_int (param_values + 3), data2);
}


static void font_manager_main_class_init (FontManagerMainClass * klass) {
	font_manager_main_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (FontManagerMainPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_font_manager_main_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_font_manager_main_set_property;
	G_OBJECT_CLASS (klass)->finalize = font_manager_main_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), FONT_MANAGER_MAIN_APPLICATION, g_param_spec_object ("application", "application", "application", FONT_MANAGER_TYPE_APPLICATION, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), FONT_MANAGER_MAIN_DATABASE, g_param_spec_object ("database", "database", "database", FONT_MANAGER_TYPE_DATABASE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), FONT_MANAGER_MAIN_SETTINGS, g_param_spec_object ("settings", "settings", "settings", G_TYPE_SETTINGS, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), FONT_MANAGER_MAIN_FONTCONFIG, g_param_spec_object ("fontconfig", "fontconfig", "fontconfig", FONT_CONFIG_TYPE_MAIN, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), FONT_MANAGER_MAIN_COLLECTIONS, g_param_spec_object ("collections", "collections", "collections", FONT_MANAGER_TYPE_COLLECTIONS, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), FONT_MANAGER_MAIN_CATEGORY_MODEL, g_param_spec_object ("category-model", "category-model", "category-model", FONT_MANAGER_TYPE_CATEGORY_MODEL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), FONT_MANAGER_MAIN_COLLECTION_MODEL, g_param_spec_object ("collection-model", "collection-model", "collection-model", FONT_MANAGER_TYPE_COLLECTION_MODEL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), FONT_MANAGER_MAIN_FONT_MODEL, g_param_spec_object ("font-model", "font-model", "font-model", FONT_MANAGER_TYPE_FONT_MODEL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_signal_new ("progress", FONT_MANAGER_TYPE_MAIN, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_user_marshal_VOID__STRING_INT_INT, G_TYPE_NONE, 3, G_TYPE_STRING, G_TYPE_INT, G_TYPE_INT);
}


static void font_manager_main_instance_init (FontManagerMain * self) {
	self->priv = FONT_MANAGER_MAIN_GET_PRIVATE (self);
	self->priv->init_called = FALSE;
	self->priv->update_in_progress = FALSE;
	self->priv->queue_update = FALSE;
}


static void font_manager_main_finalize (GObject* obj) {
	FontManagerMain * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, FONT_MANAGER_TYPE_MAIN, FontManagerMain);
	_g_object_unref0 (self->priv->_database);
	_g_object_unref0 (self->priv->_settings);
	_g_object_unref0 (self->priv->_fontconfig);
	_g_object_unref0 (self->priv->_collections);
	_g_object_unref0 (self->priv->_category_model);
	_g_object_unref0 (self->priv->_collection_model);
	_g_object_unref0 (self->priv->_font_model);
	G_OBJECT_CLASS (font_manager_main_parent_class)->finalize (obj);
}


GType font_manager_main_get_type (void) {
	static volatile gsize font_manager_main_type_id__volatile = 0;
	if (g_once_init_enter (&font_manager_main_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (FontManagerMainClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) font_manager_main_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (FontManagerMain), 0, (GInstanceInitFunc) font_manager_main_instance_init, NULL };
		GType font_manager_main_type_id;
		font_manager_main_type_id = g_type_register_static (G_TYPE_OBJECT, "FontManagerMain", &g_define_type_info, 0);
		g_once_init_leave (&font_manager_main_type_id__volatile, font_manager_main_type_id);
	}
	return font_manager_main_type_id__volatile;
}


static void _vala_font_manager_main_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	FontManagerMain * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, FONT_MANAGER_TYPE_MAIN, FontManagerMain);
	switch (property_id) {
		case FONT_MANAGER_MAIN_APPLICATION:
		g_value_set_object (value, font_manager_main_get_application (self));
		break;
		case FONT_MANAGER_MAIN_DATABASE:
		g_value_set_object (value, font_manager_main_get_database (self));
		break;
		case FONT_MANAGER_MAIN_SETTINGS:
		g_value_set_object (value, font_manager_main_get_settings (self));
		break;
		case FONT_MANAGER_MAIN_FONTCONFIG:
		g_value_set_object (value, font_manager_main_get_fontconfig (self));
		break;
		case FONT_MANAGER_MAIN_COLLECTIONS:
		g_value_set_object (value, font_manager_main_get_collections (self));
		break;
		case FONT_MANAGER_MAIN_CATEGORY_MODEL:
		g_value_set_object (value, font_manager_main_get_category_model (self));
		break;
		case FONT_MANAGER_MAIN_COLLECTION_MODEL:
		g_value_set_object (value, font_manager_main_get_collection_model (self));
		break;
		case FONT_MANAGER_MAIN_FONT_MODEL:
		g_value_set_object (value, font_manager_main_get_font_model (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_font_manager_main_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	FontManagerMain * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, FONT_MANAGER_TYPE_MAIN, FontManagerMain);
	switch (property_id) {
		case FONT_MANAGER_MAIN_APPLICATION:
		font_manager_main_set_application (self, g_value_get_object (value));
		break;
		case FONT_MANAGER_MAIN_DATABASE:
		font_manager_main_set_database (self, g_value_get_object (value));
		break;
		case FONT_MANAGER_MAIN_SETTINGS:
		font_manager_main_set_settings (self, g_value_get_object (value));
		break;
		case FONT_MANAGER_MAIN_FONTCONFIG:
		font_manager_main_set_fontconfig (self, g_value_get_object (value));
		break;
		case FONT_MANAGER_MAIN_COLLECTIONS:
		font_manager_main_set_collections (self, g_value_get_object (value));
		break;
		case FONT_MANAGER_MAIN_CATEGORY_MODEL:
		font_manager_main_set_category_model (self, g_value_get_object (value));
		break;
		case FONT_MANAGER_MAIN_COLLECTION_MODEL:
		font_manager_main_set_collection_model (self, g_value_get_object (value));
		break;
		case FONT_MANAGER_MAIN_FONT_MODEL:
		font_manager_main_set_font_model (self, g_value_get_object (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



