make:	lcd1 lcd2 lcd3

lcd1:	lcd1602_1.c
		gcc lcd1602_1.c -o lcd1 -lwiringPiDev -lwiringPi

lcd2:	lcd1602_2.c
		gcc lcd1602_2.c -o lcd2 -lwiringPiDev -lwiringPi

lcd3:	lcd3.c
		gcc lcd3.c -o lcd3 -lwiringPiDev -lwiringPi
