/* SideBar.c generated by valac 0.26.1, the Vala compiler
 * generated from SideBar.vala, do not modify */

/* SideBar.vala
 *
 * Copyright (C) 2009 - 2015 Jerry Casiano
 *
 * This file is part of Font Manager.
 *
 * Font Manager is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Font Manager is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Font Manager.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Author:
 *        Jerry Casiano <JerryCasiano@gmail.com>
*/

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <stdlib.h>
#include <string.h>


#define FONT_MANAGER_TYPE_SIDE_BAR (font_manager_side_bar_get_type ())
#define FONT_MANAGER_SIDE_BAR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FONT_MANAGER_TYPE_SIDE_BAR, FontManagerSideBar))
#define FONT_MANAGER_SIDE_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FONT_MANAGER_TYPE_SIDE_BAR, FontManagerSideBarClass))
#define FONT_MANAGER_IS_SIDE_BAR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FONT_MANAGER_TYPE_SIDE_BAR))
#define FONT_MANAGER_IS_SIDE_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FONT_MANAGER_TYPE_SIDE_BAR))
#define FONT_MANAGER_SIDE_BAR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FONT_MANAGER_TYPE_SIDE_BAR, FontManagerSideBarClass))

typedef struct _FontManagerSideBar FontManagerSideBar;
typedef struct _FontManagerSideBarClass FontManagerSideBarClass;
typedef struct _FontManagerSideBarPrivate FontManagerSideBarPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define FONT_MANAGER_TYPE_MAIN_SIDE_BAR (font_manager_main_side_bar_get_type ())
#define FONT_MANAGER_MAIN_SIDE_BAR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FONT_MANAGER_TYPE_MAIN_SIDE_BAR, FontManagerMainSideBar))
#define FONT_MANAGER_MAIN_SIDE_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FONT_MANAGER_TYPE_MAIN_SIDE_BAR, FontManagerMainSideBarClass))
#define FONT_MANAGER_IS_MAIN_SIDE_BAR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FONT_MANAGER_TYPE_MAIN_SIDE_BAR))
#define FONT_MANAGER_IS_MAIN_SIDE_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FONT_MANAGER_TYPE_MAIN_SIDE_BAR))
#define FONT_MANAGER_MAIN_SIDE_BAR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FONT_MANAGER_TYPE_MAIN_SIDE_BAR, FontManagerMainSideBarClass))

typedef struct _FontManagerMainSideBar FontManagerMainSideBar;
typedef struct _FontManagerMainSideBarClass FontManagerMainSideBarClass;

#define FONT_MANAGER_TYPE_CHARACTER_MAP_SIDE_BAR (font_manager_character_map_side_bar_get_type ())
#define FONT_MANAGER_CHARACTER_MAP_SIDE_BAR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FONT_MANAGER_TYPE_CHARACTER_MAP_SIDE_BAR, FontManagerCharacterMapSideBar))
#define FONT_MANAGER_CHARACTER_MAP_SIDE_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FONT_MANAGER_TYPE_CHARACTER_MAP_SIDE_BAR, FontManagerCharacterMapSideBarClass))
#define FONT_MANAGER_IS_CHARACTER_MAP_SIDE_BAR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FONT_MANAGER_TYPE_CHARACTER_MAP_SIDE_BAR))
#define FONT_MANAGER_IS_CHARACTER_MAP_SIDE_BAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FONT_MANAGER_TYPE_CHARACTER_MAP_SIDE_BAR))
#define FONT_MANAGER_CHARACTER_MAP_SIDE_BAR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FONT_MANAGER_TYPE_CHARACTER_MAP_SIDE_BAR, FontManagerCharacterMapSideBarClass))

typedef struct _FontManagerCharacterMapSideBar FontManagerCharacterMapSideBar;
typedef struct _FontManagerCharacterMapSideBarClass FontManagerCharacterMapSideBarClass;

#define FONT_MANAGER_TYPE_CATEGORY_MODEL (font_manager_category_model_get_type ())
#define FONT_MANAGER_CATEGORY_MODEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FONT_MANAGER_TYPE_CATEGORY_MODEL, FontManagerCategoryModel))
#define FONT_MANAGER_CATEGORY_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FONT_MANAGER_TYPE_CATEGORY_MODEL, FontManagerCategoryModelClass))
#define FONT_MANAGER_IS_CATEGORY_MODEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FONT_MANAGER_TYPE_CATEGORY_MODEL))
#define FONT_MANAGER_IS_CATEGORY_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FONT_MANAGER_TYPE_CATEGORY_MODEL))
#define FONT_MANAGER_CATEGORY_MODEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FONT_MANAGER_TYPE_CATEGORY_MODEL, FontManagerCategoryModelClass))

typedef struct _FontManagerCategoryModel FontManagerCategoryModel;
typedef struct _FontManagerCategoryModelClass FontManagerCategoryModelClass;

#define FONT_MANAGER_TYPE_CATEGORY_TREE (font_manager_category_tree_get_type ())
#define FONT_MANAGER_CATEGORY_TREE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FONT_MANAGER_TYPE_CATEGORY_TREE, FontManagerCategoryTree))
#define FONT_MANAGER_CATEGORY_TREE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FONT_MANAGER_TYPE_CATEGORY_TREE, FontManagerCategoryTreeClass))
#define FONT_MANAGER_IS_CATEGORY_TREE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FONT_MANAGER_TYPE_CATEGORY_TREE))
#define FONT_MANAGER_IS_CATEGORY_TREE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FONT_MANAGER_TYPE_CATEGORY_TREE))
#define FONT_MANAGER_CATEGORY_TREE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FONT_MANAGER_TYPE_CATEGORY_TREE, FontManagerCategoryTreeClass))

typedef struct _FontManagerCategoryTree FontManagerCategoryTree;
typedef struct _FontManagerCategoryTreeClass FontManagerCategoryTreeClass;

#define FONT_MANAGER_TYPE_COLLECTION_MODEL (font_manager_collection_model_get_type ())
#define FONT_MANAGER_COLLECTION_MODEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FONT_MANAGER_TYPE_COLLECTION_MODEL, FontManagerCollectionModel))
#define FONT_MANAGER_COLLECTION_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FONT_MANAGER_TYPE_COLLECTION_MODEL, FontManagerCollectionModelClass))
#define FONT_MANAGER_IS_COLLECTION_MODEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FONT_MANAGER_TYPE_COLLECTION_MODEL))
#define FONT_MANAGER_IS_COLLECTION_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FONT_MANAGER_TYPE_COLLECTION_MODEL))
#define FONT_MANAGER_COLLECTION_MODEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FONT_MANAGER_TYPE_COLLECTION_MODEL, FontManagerCollectionModelClass))

typedef struct _FontManagerCollectionModel FontManagerCollectionModel;
typedef struct _FontManagerCollectionModelClass FontManagerCollectionModelClass;

#define FONT_MANAGER_TYPE_COLLECTION_TREE (font_manager_collection_tree_get_type ())
#define FONT_MANAGER_COLLECTION_TREE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FONT_MANAGER_TYPE_COLLECTION_TREE, FontManagerCollectionTree))
#define FONT_MANAGER_COLLECTION_TREE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FONT_MANAGER_TYPE_COLLECTION_TREE, FontManagerCollectionTreeClass))
#define FONT_MANAGER_IS_COLLECTION_TREE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FONT_MANAGER_TYPE_COLLECTION_TREE))
#define FONT_MANAGER_IS_COLLECTION_TREE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FONT_MANAGER_TYPE_COLLECTION_TREE))
#define FONT_MANAGER_COLLECTION_TREE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FONT_MANAGER_TYPE_COLLECTION_TREE, FontManagerCollectionTreeClass))

typedef struct _FontManagerCollectionTree FontManagerCollectionTree;
typedef struct _FontManagerCollectionTreeClass FontManagerCollectionTreeClass;

struct _FontManagerSideBar {
	GtkOverlay parent_instance;
	FontManagerSideBarPrivate * priv;
	GtkStack* stack;
};

struct _FontManagerSideBarClass {
	GtkOverlayClass parent_class;
};

struct _FontManagerSideBarPrivate {
	gboolean _loading;
	GtkSpinner* spinner;
	GtkBox* box;
};


static gpointer font_manager_side_bar_parent_class = NULL;

GType font_manager_side_bar_get_type (void) G_GNUC_CONST;
#define FONT_MANAGER_SIDE_BAR_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), FONT_MANAGER_TYPE_SIDE_BAR, FontManagerSideBarPrivate))
enum  {
	FONT_MANAGER_SIDE_BAR_DUMMY_PROPERTY,
	FONT_MANAGER_SIDE_BAR_MODE,
	FONT_MANAGER_SIDE_BAR_STANDARD,
	FONT_MANAGER_SIDE_BAR_CHARACTER_MAP,
	FONT_MANAGER_SIDE_BAR_CATEGORY_MODEL,
	FONT_MANAGER_SIDE_BAR_COLLECTION_MODEL,
	FONT_MANAGER_SIDE_BAR_LOADING
};
FontManagerSideBar* font_manager_side_bar_new (void);
FontManagerSideBar* font_manager_side_bar_construct (GType object_type);
static void __lambda39_ (FontManagerSideBar* self);
static void ___lambda39__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
static void font_manager_side_bar_real_show (GtkWidget* base);
void font_manager_side_bar_add_view (FontManagerSideBar* self, GtkWidget* sidebar_view, const gchar* name);
const gchar* font_manager_side_bar_get_mode (FontManagerSideBar* self);
void font_manager_side_bar_set_mode (FontManagerSideBar* self, const gchar* value);
GType font_manager_main_side_bar_get_type (void) G_GNUC_CONST;
FontManagerMainSideBar* font_manager_side_bar_get_standard (FontManagerSideBar* self);
GType font_manager_character_map_side_bar_get_type (void) G_GNUC_CONST;
FontManagerCharacterMapSideBar* font_manager_side_bar_get_character_map (FontManagerSideBar* self);
GType font_manager_category_model_get_type (void) G_GNUC_CONST;
FontManagerCategoryModel* font_manager_side_bar_get_category_model (FontManagerSideBar* self);
GType font_manager_category_tree_get_type (void) G_GNUC_CONST;
FontManagerCategoryTree* font_manager_main_side_bar_get_category_tree (FontManagerMainSideBar* self);
FontManagerCategoryModel* font_manager_category_tree_get_model (FontManagerCategoryTree* self);
void font_manager_side_bar_set_category_model (FontManagerSideBar* self, FontManagerCategoryModel* value);
void font_manager_category_tree_set_model (FontManagerCategoryTree* self, FontManagerCategoryModel* value);
GType font_manager_collection_model_get_type (void) G_GNUC_CONST;
FontManagerCollectionModel* font_manager_side_bar_get_collection_model (FontManagerSideBar* self);
GType font_manager_collection_tree_get_type (void) G_GNUC_CONST;
FontManagerCollectionTree* font_manager_main_side_bar_get_collection_tree (FontManagerMainSideBar* self);
FontManagerCollectionModel* font_manager_collection_tree_get_model (FontManagerCollectionTree* self);
void font_manager_side_bar_set_collection_model (FontManagerSideBar* self, FontManagerCollectionModel* value);
void font_manager_collection_tree_set_model (FontManagerCollectionTree* self, FontManagerCollectionModel* value);
gboolean font_manager_side_bar_get_loading (FontManagerSideBar* self);
void font_manager_side_bar_set_loading (FontManagerSideBar* self, gboolean value);
static void font_manager_side_bar_finalize (GObject* obj);
static void _vala_font_manager_side_bar_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_font_manager_side_bar_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


static void __lambda39_ (FontManagerSideBar* self) {
	GtkStack* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	_tmp0_ = self->stack;
	_tmp1_ = gtk_stack_get_visible_child_name (_tmp0_);
	if (g_strcmp0 (_tmp1_, "Default") == 0) {
		GtkStack* _tmp2_ = NULL;
		_tmp2_ = self->stack;
		gtk_stack_set_transition_type (_tmp2_, GTK_STACK_TRANSITION_TYPE_UNDER_LEFT);
	} else {
		GtkStack* _tmp3_ = NULL;
		_tmp3_ = self->stack;
		gtk_stack_set_transition_type (_tmp3_, GTK_STACK_TRANSITION_TYPE_OVER_RIGHT);
	}
}


static void ___lambda39__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
	__lambda39_ ((FontManagerSideBar*) self);
}


FontManagerSideBar* font_manager_side_bar_construct (GType object_type) {
	FontManagerSideBar * self = NULL;
	GtkStack* _tmp0_ = NULL;
	GtkStack* _tmp1_ = NULL;
	GtkStack* _tmp2_ = NULL;
	GtkBox* _tmp3_ = NULL;
	GtkBox* _tmp4_ = NULL;
	GtkBox* _tmp5_ = NULL;
	GtkStack* _tmp6_ = NULL;
	GtkSpinner* _tmp7_ = NULL;
	GtkSpinner* _tmp8_ = NULL;
	GtkSpinner* _tmp9_ = NULL;
	GtkSpinner* _tmp10_ = NULL;
	GtkBox* _tmp11_ = NULL;
	GtkSpinner* _tmp12_ = NULL;
	GtkStyleContext* _tmp13_ = NULL;
	GtkSpinner* _tmp14_ = NULL;
	GtkStyleContext* _tmp15_ = NULL;
	GtkStack* _tmp16_ = NULL;
	self = (FontManagerSideBar*) g_object_new (object_type, NULL);
	_tmp0_ = (GtkStack*) gtk_stack_new ();
	g_object_ref_sink (_tmp0_);
	_g_object_unref0 (self->stack);
	self->stack = _tmp0_;
	_tmp1_ = self->stack;
	gtk_stack_set_transition_duration (_tmp1_, (guint) 420);
	_tmp2_ = self->stack;
	gtk_stack_set_transition_type (_tmp2_, GTK_STACK_TRANSITION_TYPE_UNDER_LEFT);
	_tmp3_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_HORIZONTAL, 0);
	g_object_ref_sink (_tmp3_);
	_g_object_unref0 (self->priv->box);
	self->priv->box = _tmp3_;
	_tmp4_ = self->priv->box;
	g_object_set ((GtkWidget*) _tmp4_, "expand", TRUE, NULL);
	_tmp5_ = self->priv->box;
	_tmp6_ = self->stack;
	gtk_box_pack_start (_tmp5_, (GtkWidget*) _tmp6_, TRUE, TRUE, (guint) 0);
	_tmp7_ = (GtkSpinner*) gtk_spinner_new ();
	g_object_ref_sink (_tmp7_);
	_g_object_unref0 (self->priv->spinner);
	self->priv->spinner = _tmp7_;
	_tmp8_ = self->priv->spinner;
	gtk_widget_set_halign ((GtkWidget*) _tmp8_, GTK_ALIGN_CENTER);
	_tmp9_ = self->priv->spinner;
	gtk_widget_set_valign ((GtkWidget*) _tmp9_, GTK_ALIGN_CENTER);
	_tmp10_ = self->priv->spinner;
	gtk_widget_set_size_request ((GtkWidget*) _tmp10_, 48, 48);
	_tmp11_ = self->priv->box;
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) _tmp11_);
	_tmp12_ = self->priv->spinner;
	gtk_overlay_add_overlay ((GtkOverlay*) self, (GtkWidget*) _tmp12_);
	_tmp13_ = gtk_widget_get_style_context ((GtkWidget*) self);
	gtk_style_context_add_class (_tmp13_, GTK_STYLE_CLASS_SIDEBAR);
	_tmp14_ = self->priv->spinner;
	_tmp15_ = gtk_widget_get_style_context ((GtkWidget*) _tmp14_);
	gtk_style_context_add_class (_tmp15_, GTK_STYLE_CLASS_SIDEBAR);
	_tmp16_ = self->stack;
	g_signal_connect_object ((GObject*) _tmp16_, "notify::visible-child-name", (GCallback) ___lambda39__g_object_notify, self, 0);
	return self;
}


FontManagerSideBar* font_manager_side_bar_new (void) {
	return font_manager_side_bar_construct (FONT_MANAGER_TYPE_SIDE_BAR);
}


static void font_manager_side_bar_real_show (GtkWidget* base) {
	FontManagerSideBar * self;
	GtkStack* _tmp0_ = NULL;
	GtkBox* _tmp1_ = NULL;
	self = (FontManagerSideBar*) base;
	_tmp0_ = self->stack;
	gtk_widget_show ((GtkWidget*) _tmp0_);
	_tmp1_ = self->priv->box;
	gtk_widget_show ((GtkWidget*) _tmp1_);
	GTK_WIDGET_CLASS (font_manager_side_bar_parent_class)->show ((GtkWidget*) G_TYPE_CHECK_INSTANCE_CAST (self, gtk_overlay_get_type (), GtkOverlay));
	return;
}


void font_manager_side_bar_add_view (FontManagerSideBar* self, GtkWidget* sidebar_view, const gchar* name) {
	GtkStack* _tmp0_ = NULL;
	GtkWidget* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	GtkWidget* _tmp3_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (sidebar_view != NULL);
	g_return_if_fail (name != NULL);
	_tmp0_ = self->stack;
	_tmp1_ = sidebar_view;
	_tmp2_ = name;
	gtk_stack_add_named (_tmp0_, _tmp1_, _tmp2_);
	_tmp3_ = sidebar_view;
	gtk_widget_show (_tmp3_);
	return;
}


const gchar* font_manager_side_bar_get_mode (FontManagerSideBar* self) {
	const gchar* result;
	GtkStack* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->stack;
	_tmp1_ = gtk_stack_get_visible_child_name (_tmp0_);
	result = _tmp1_;
	return result;
}


void font_manager_side_bar_set_mode (FontManagerSideBar* self, const gchar* value) {
	GtkStack* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->stack;
	_tmp1_ = value;
	gtk_stack_set_visible_child_name (_tmp0_, _tmp1_);
	g_object_notify ((GObject *) self, "mode");
}


FontManagerMainSideBar* font_manager_side_bar_get_standard (FontManagerSideBar* self) {
	FontManagerMainSideBar* result;
	GtkStack* _tmp0_ = NULL;
	GtkWidget* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->stack;
	_tmp1_ = gtk_stack_get_child_by_name (_tmp0_, "Default");
	result = G_TYPE_CHECK_INSTANCE_CAST (_tmp1_, FONT_MANAGER_TYPE_MAIN_SIDE_BAR, FontManagerMainSideBar);
	return result;
}


FontManagerCharacterMapSideBar* font_manager_side_bar_get_character_map (FontManagerSideBar* self) {
	FontManagerCharacterMapSideBar* result;
	GtkStack* _tmp0_ = NULL;
	GtkWidget* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->stack;
	_tmp1_ = gtk_stack_get_child_by_name (_tmp0_, "Character Map");
	result = G_TYPE_CHECK_INSTANCE_CAST (_tmp1_, FONT_MANAGER_TYPE_CHARACTER_MAP_SIDE_BAR, FontManagerCharacterMapSideBar);
	return result;
}


FontManagerCategoryModel* font_manager_side_bar_get_category_model (FontManagerSideBar* self) {
	FontManagerCategoryModel* result;
	FontManagerMainSideBar* _tmp0_ = NULL;
	FontManagerMainSideBar* _tmp1_ = NULL;
	FontManagerCategoryTree* _tmp2_ = NULL;
	FontManagerCategoryTree* _tmp3_ = NULL;
	FontManagerCategoryModel* _tmp4_ = NULL;
	FontManagerCategoryModel* _tmp5_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = font_manager_side_bar_get_standard (self);
	_tmp1_ = _tmp0_;
	_tmp2_ = font_manager_main_side_bar_get_category_tree (_tmp1_);
	_tmp3_ = _tmp2_;
	_tmp4_ = font_manager_category_tree_get_model (_tmp3_);
	_tmp5_ = _tmp4_;
	result = _tmp5_;
	return result;
}


void font_manager_side_bar_set_category_model (FontManagerSideBar* self, FontManagerCategoryModel* value) {
	FontManagerMainSideBar* _tmp0_ = NULL;
	FontManagerMainSideBar* _tmp1_ = NULL;
	FontManagerCategoryTree* _tmp2_ = NULL;
	FontManagerCategoryTree* _tmp3_ = NULL;
	FontManagerCategoryModel* _tmp4_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = font_manager_side_bar_get_standard (self);
	_tmp1_ = _tmp0_;
	_tmp2_ = font_manager_main_side_bar_get_category_tree (_tmp1_);
	_tmp3_ = _tmp2_;
	_tmp4_ = value;
	font_manager_category_tree_set_model (_tmp3_, _tmp4_);
	g_object_notify ((GObject *) self, "category-model");
}


FontManagerCollectionModel* font_manager_side_bar_get_collection_model (FontManagerSideBar* self) {
	FontManagerCollectionModel* result;
	FontManagerMainSideBar* _tmp0_ = NULL;
	FontManagerMainSideBar* _tmp1_ = NULL;
	FontManagerCollectionTree* _tmp2_ = NULL;
	FontManagerCollectionTree* _tmp3_ = NULL;
	FontManagerCollectionModel* _tmp4_ = NULL;
	FontManagerCollectionModel* _tmp5_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = font_manager_side_bar_get_standard (self);
	_tmp1_ = _tmp0_;
	_tmp2_ = font_manager_main_side_bar_get_collection_tree (_tmp1_);
	_tmp3_ = _tmp2_;
	_tmp4_ = font_manager_collection_tree_get_model (_tmp3_);
	_tmp5_ = _tmp4_;
	result = _tmp5_;
	return result;
}


void font_manager_side_bar_set_collection_model (FontManagerSideBar* self, FontManagerCollectionModel* value) {
	FontManagerMainSideBar* _tmp0_ = NULL;
	FontManagerMainSideBar* _tmp1_ = NULL;
	FontManagerCollectionTree* _tmp2_ = NULL;
	FontManagerCollectionTree* _tmp3_ = NULL;
	FontManagerCollectionModel* _tmp4_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = font_manager_side_bar_get_standard (self);
	_tmp1_ = _tmp0_;
	_tmp2_ = font_manager_main_side_bar_get_collection_tree (_tmp1_);
	_tmp3_ = _tmp2_;
	_tmp4_ = value;
	font_manager_collection_tree_set_model (_tmp3_, _tmp4_);
	g_object_notify ((GObject *) self, "collection-model");
}


gboolean font_manager_side_bar_get_loading (FontManagerSideBar* self) {
	gboolean result;
	gboolean _tmp0_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_loading;
	result = _tmp0_;
	return result;
}


void font_manager_side_bar_set_loading (FontManagerSideBar* self, gboolean value) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	if (_tmp0_) {
		GtkSpinner* _tmp1_ = NULL;
		GtkSpinner* _tmp2_ = NULL;
		_tmp1_ = self->priv->spinner;
		gtk_spinner_start (_tmp1_);
		_tmp2_ = self->priv->spinner;
		gtk_widget_show ((GtkWidget*) _tmp2_);
	} else {
		GtkSpinner* _tmp3_ = NULL;
		GtkSpinner* _tmp4_ = NULL;
		_tmp3_ = self->priv->spinner;
		gtk_widget_hide ((GtkWidget*) _tmp3_);
		_tmp4_ = self->priv->spinner;
		gtk_spinner_stop (_tmp4_);
	}
	g_object_notify ((GObject *) self, "loading");
}


static void font_manager_side_bar_class_init (FontManagerSideBarClass * klass) {
	font_manager_side_bar_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (FontManagerSideBarPrivate));
	((GtkWidgetClass *) klass)->show = font_manager_side_bar_real_show;
	G_OBJECT_CLASS (klass)->get_property = _vala_font_manager_side_bar_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_font_manager_side_bar_set_property;
	G_OBJECT_CLASS (klass)->finalize = font_manager_side_bar_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), FONT_MANAGER_SIDE_BAR_MODE, g_param_spec_string ("mode", "mode", "mode", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), FONT_MANAGER_SIDE_BAR_STANDARD, g_param_spec_object ("standard", "standard", "standard", FONT_MANAGER_TYPE_MAIN_SIDE_BAR, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), FONT_MANAGER_SIDE_BAR_CHARACTER_MAP, g_param_spec_object ("character-map", "character-map", "character-map", FONT_MANAGER_TYPE_CHARACTER_MAP_SIDE_BAR, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), FONT_MANAGER_SIDE_BAR_CATEGORY_MODEL, g_param_spec_object ("category-model", "category-model", "category-model", FONT_MANAGER_TYPE_CATEGORY_MODEL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), FONT_MANAGER_SIDE_BAR_COLLECTION_MODEL, g_param_spec_object ("collection-model", "collection-model", "collection-model", FONT_MANAGER_TYPE_COLLECTION_MODEL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), FONT_MANAGER_SIDE_BAR_LOADING, g_param_spec_boolean ("loading", "loading", "loading", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void font_manager_side_bar_instance_init (FontManagerSideBar * self) {
	self->priv = FONT_MANAGER_SIDE_BAR_GET_PRIVATE (self);
	self->priv->_loading = FALSE;
}


static void font_manager_side_bar_finalize (GObject* obj) {
	FontManagerSideBar * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, FONT_MANAGER_TYPE_SIDE_BAR, FontManagerSideBar);
	_g_object_unref0 (self->stack);
	_g_object_unref0 (self->priv->spinner);
	_g_object_unref0 (self->priv->box);
	G_OBJECT_CLASS (font_manager_side_bar_parent_class)->finalize (obj);
}


GType font_manager_side_bar_get_type (void) {
	static volatile gsize font_manager_side_bar_type_id__volatile = 0;
	if (g_once_init_enter (&font_manager_side_bar_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (FontManagerSideBarClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) font_manager_side_bar_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (FontManagerSideBar), 0, (GInstanceInitFunc) font_manager_side_bar_instance_init, NULL };
		GType font_manager_side_bar_type_id;
		font_manager_side_bar_type_id = g_type_register_static (gtk_overlay_get_type (), "FontManagerSideBar", &g_define_type_info, 0);
		g_once_init_leave (&font_manager_side_bar_type_id__volatile, font_manager_side_bar_type_id);
	}
	return font_manager_side_bar_type_id__volatile;
}


static void _vala_font_manager_side_bar_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	FontManagerSideBar * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, FONT_MANAGER_TYPE_SIDE_BAR, FontManagerSideBar);
	switch (property_id) {
		case FONT_MANAGER_SIDE_BAR_MODE:
		g_value_set_string (value, font_manager_side_bar_get_mode (self));
		break;
		case FONT_MANAGER_SIDE_BAR_STANDARD:
		g_value_set_object (value, font_manager_side_bar_get_standard (self));
		break;
		case FONT_MANAGER_SIDE_BAR_CHARACTER_MAP:
		g_value_set_object (value, font_manager_side_bar_get_character_map (self));
		break;
		case FONT_MANAGER_SIDE_BAR_CATEGORY_MODEL:
		g_value_set_object (value, font_manager_side_bar_get_category_model (self));
		break;
		case FONT_MANAGER_SIDE_BAR_COLLECTION_MODEL:
		g_value_set_object (value, font_manager_side_bar_get_collection_model (self));
		break;
		case FONT_MANAGER_SIDE_BAR_LOADING:
		g_value_set_boolean (value, font_manager_side_bar_get_loading (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_font_manager_side_bar_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	FontManagerSideBar * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, FONT_MANAGER_TYPE_SIDE_BAR, FontManagerSideBar);
	switch (property_id) {
		case FONT_MANAGER_SIDE_BAR_MODE:
		font_manager_side_bar_set_mode (self, g_value_get_string (value));
		break;
		case FONT_MANAGER_SIDE_BAR_CATEGORY_MODEL:
		font_manager_side_bar_set_category_model (self, g_value_get_object (value));
		break;
		case FONT_MANAGER_SIDE_BAR_COLLECTION_MODEL:
		font_manager_side_bar_set_collection_model (self, g_value_get_object (value));
		break;
		case FONT_MANAGER_SIDE_BAR_LOADING:
		font_manager_side_bar_set_loading (self, g_value_get_boolean (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



