/* LabeledSpinButton.c generated by valac 0.26.1, the Vala compiler
 * generated from LabeledSpinButton.vala, do not modify */

/* LabeledSpinButton.vala
 *
 * Copyright (C) 2009 - 2015 Jerry Casiano
 *
 * This file is part of Font Manager.
 *
 * Font Manager is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Font Manager is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Font Manager.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Author:
 *        Jerry Casiano <JerryCasiano@gmail.com>
*/

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <float.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>


#define TYPE_LABELED_SPIN_BUTTON (labeled_spin_button_get_type ())
#define LABELED_SPIN_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_LABELED_SPIN_BUTTON, LabeledSpinButton))
#define LABELED_SPIN_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_LABELED_SPIN_BUTTON, LabeledSpinButtonClass))
#define IS_LABELED_SPIN_BUTTON(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_LABELED_SPIN_BUTTON))
#define IS_LABELED_SPIN_BUTTON_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_LABELED_SPIN_BUTTON))
#define LABELED_SPIN_BUTTON_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_LABELED_SPIN_BUTTON, LabeledSpinButtonClass))

typedef struct _LabeledSpinButton LabeledSpinButton;
typedef struct _LabeledSpinButtonClass LabeledSpinButtonClass;
typedef struct _LabeledSpinButtonPrivate LabeledSpinButtonPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _LabeledSpinButton {
	GtkGrid parent_instance;
	LabeledSpinButtonPrivate * priv;
};

struct _LabeledSpinButtonClass {
	GtkGridClass parent_class;
};

struct _LabeledSpinButtonPrivate {
	gdouble _value;
	GtkLabel* label;
	GtkSpinButton* spin;
};


static gpointer labeled_spin_button_parent_class = NULL;

GType labeled_spin_button_get_type (void) G_GNUC_CONST;
#define LABELED_SPIN_BUTTON_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_LABELED_SPIN_BUTTON, LabeledSpinButtonPrivate))
enum  {
	LABELED_SPIN_BUTTON_DUMMY_PROPERTY,
	LABELED_SPIN_BUTTON_VALUE
};
LabeledSpinButton* labeled_spin_button_new (const gchar* label, gdouble min, gdouble max, gdouble step);
LabeledSpinButton* labeled_spin_button_construct (GType object_type, const gchar* label, gdouble min, gdouble max, gdouble step);
static void labeled_spin_button_real_show (GtkWidget* base);
gdouble labeled_spin_button_get_value (LabeledSpinButton* self);
void labeled_spin_button_set_value (LabeledSpinButton* self, gdouble value);
static void labeled_spin_button_finalize (GObject* obj);
static void _vala_labeled_spin_button_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_labeled_spin_button_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


LabeledSpinButton* labeled_spin_button_construct (GType object_type, const gchar* label, gdouble min, gdouble max, gdouble step) {
	LabeledSpinButton * self = NULL;
	const gchar* _tmp0_ = NULL;
	GtkLabel* _tmp1_ = NULL;
	GtkLabel* _tmp2_ = NULL;
	GtkLabel* _tmp3_ = NULL;
	gdouble _tmp4_ = 0.0;
	gdouble _tmp5_ = 0.0;
	gdouble _tmp6_ = 0.0;
	GtkSpinButton* _tmp7_ = NULL;
	GtkLabel* _tmp8_ = NULL;
	GtkSpinButton* _tmp9_ = NULL;
	GtkSpinButton* _tmp10_ = NULL;
	g_return_val_if_fail (label != NULL, NULL);
	self = (LabeledSpinButton*) g_object_new (object_type, NULL);
	g_object_set ((GtkWidget*) self, "margin", 12, NULL);
	_tmp0_ = label;
	_tmp1_ = (GtkLabel*) gtk_label_new (_tmp0_);
	g_object_ref_sink (_tmp1_);
	_g_object_unref0 (self->priv->label);
	self->priv->label = _tmp1_;
	_tmp2_ = self->priv->label;
	gtk_widget_set_hexpand ((GtkWidget*) _tmp2_, TRUE);
	_tmp3_ = self->priv->label;
	gtk_widget_set_halign ((GtkWidget*) _tmp3_, GTK_ALIGN_START);
	_tmp4_ = min;
	_tmp5_ = max;
	_tmp6_ = step;
	_tmp7_ = (GtkSpinButton*) gtk_spin_button_new_with_range (_tmp4_, _tmp5_, _tmp6_);
	g_object_ref_sink (_tmp7_);
	_g_object_unref0 (self->priv->spin);
	self->priv->spin = _tmp7_;
	_tmp8_ = self->priv->label;
	gtk_grid_attach ((GtkGrid*) self, (GtkWidget*) _tmp8_, 0, 0, 2, 1);
	_tmp9_ = self->priv->spin;
	gtk_grid_attach ((GtkGrid*) self, (GtkWidget*) _tmp9_, 2, 0, 1, 1);
	_tmp10_ = self->priv->spin;
	g_object_bind_property_with_closures ((GObject*) self, "value", (GObject*) _tmp10_, "value", G_BINDING_BIDIRECTIONAL | G_BINDING_SYNC_CREATE, (GClosure*) ((NULL == NULL) ? NULL : g_cclosure_new ((GCallback) NULL, NULL, NULL)), (GClosure*) ((NULL == NULL) ? NULL : g_cclosure_new ((GCallback) NULL, NULL, NULL)));
	return self;
}


LabeledSpinButton* labeled_spin_button_new (const gchar* label, gdouble min, gdouble max, gdouble step) {
	return labeled_spin_button_construct (TYPE_LABELED_SPIN_BUTTON, label, min, max, step);
}


static void labeled_spin_button_real_show (GtkWidget* base) {
	LabeledSpinButton * self;
	GtkLabel* _tmp0_ = NULL;
	GtkSpinButton* _tmp1_ = NULL;
	self = (LabeledSpinButton*) base;
	_tmp0_ = self->priv->label;
	gtk_widget_show ((GtkWidget*) _tmp0_);
	_tmp1_ = self->priv->spin;
	gtk_widget_show ((GtkWidget*) _tmp1_);
	GTK_WIDGET_CLASS (labeled_spin_button_parent_class)->show ((GtkWidget*) G_TYPE_CHECK_INSTANCE_CAST (self, gtk_grid_get_type (), GtkGrid));
	return;
}


gdouble labeled_spin_button_get_value (LabeledSpinButton* self) {
	gdouble result;
	gdouble _tmp0_ = 0.0;
	g_return_val_if_fail (self != NULL, 0.0);
	_tmp0_ = self->priv->_value;
	result = _tmp0_;
	return result;
}


void labeled_spin_button_set_value (LabeledSpinButton* self, gdouble value) {
	gdouble _tmp0_ = 0.0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_value = _tmp0_;
	g_object_notify ((GObject *) self, "value");
}


static void labeled_spin_button_class_init (LabeledSpinButtonClass * klass) {
	labeled_spin_button_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (LabeledSpinButtonPrivate));
	((GtkWidgetClass *) klass)->show = labeled_spin_button_real_show;
	G_OBJECT_CLASS (klass)->get_property = _vala_labeled_spin_button_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_labeled_spin_button_set_property;
	G_OBJECT_CLASS (klass)->finalize = labeled_spin_button_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), LABELED_SPIN_BUTTON_VALUE, g_param_spec_double ("value", "value", "value", -G_MAXDOUBLE, G_MAXDOUBLE, 0.0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void labeled_spin_button_instance_init (LabeledSpinButton * self) {
	self->priv = LABELED_SPIN_BUTTON_GET_PRIVATE (self);
	self->priv->_value = 0.0;
}


static void labeled_spin_button_finalize (GObject* obj) {
	LabeledSpinButton * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_LABELED_SPIN_BUTTON, LabeledSpinButton);
	_g_object_unref0 (self->priv->label);
	_g_object_unref0 (self->priv->spin);
	G_OBJECT_CLASS (labeled_spin_button_parent_class)->finalize (obj);
}


GType labeled_spin_button_get_type (void) {
	static volatile gsize labeled_spin_button_type_id__volatile = 0;
	if (g_once_init_enter (&labeled_spin_button_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (LabeledSpinButtonClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) labeled_spin_button_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (LabeledSpinButton), 0, (GInstanceInitFunc) labeled_spin_button_instance_init, NULL };
		GType labeled_spin_button_type_id;
		labeled_spin_button_type_id = g_type_register_static (gtk_grid_get_type (), "LabeledSpinButton", &g_define_type_info, 0);
		g_once_init_leave (&labeled_spin_button_type_id__volatile, labeled_spin_button_type_id);
	}
	return labeled_spin_button_type_id__volatile;
}


static void _vala_labeled_spin_button_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	LabeledSpinButton * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TYPE_LABELED_SPIN_BUTTON, LabeledSpinButton);
	switch (property_id) {
		case LABELED_SPIN_BUTTON_VALUE:
		g_value_set_double (value, labeled_spin_button_get_value (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_labeled_spin_button_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	LabeledSpinButton * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, TYPE_LABELED_SPIN_BUTTON, LabeledSpinButton);
	switch (property_id) {
		case LABELED_SPIN_BUTTON_VALUE:
		labeled_spin_button_set_value (self, g_value_get_double (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



