/* TextPreview.c generated by valac 0.26.1, the Vala compiler
 * generated from TextPreview.vala, do not modify */

/* TextPreview.vala
 *
 * Copyright (C) 2009 - 2015 Jerry Casiano
 *
 * This file is part of Font Manager.
 *
 * Font Manager is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Font Manager is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Font Manager.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Author:
 *        Jerry Casiano <JerryCasiano@gmail.com>
*/

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <float.h>
#include <math.h>
#include <pango/pango.h>
#include <stdlib.h>
#include <string.h>


#define FONT_MANAGER_TYPE_ADJUSTABLE_PREVIEW (font_manager_adjustable_preview_get_type ())
#define FONT_MANAGER_ADJUSTABLE_PREVIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FONT_MANAGER_TYPE_ADJUSTABLE_PREVIEW, FontManagerAdjustablePreview))
#define FONT_MANAGER_ADJUSTABLE_PREVIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FONT_MANAGER_TYPE_ADJUSTABLE_PREVIEW, FontManagerAdjustablePreviewClass))
#define FONT_MANAGER_IS_ADJUSTABLE_PREVIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FONT_MANAGER_TYPE_ADJUSTABLE_PREVIEW))
#define FONT_MANAGER_IS_ADJUSTABLE_PREVIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FONT_MANAGER_TYPE_ADJUSTABLE_PREVIEW))
#define FONT_MANAGER_ADJUSTABLE_PREVIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FONT_MANAGER_TYPE_ADJUSTABLE_PREVIEW, FontManagerAdjustablePreviewClass))

typedef struct _FontManagerAdjustablePreview FontManagerAdjustablePreview;
typedef struct _FontManagerAdjustablePreviewClass FontManagerAdjustablePreviewClass;
typedef struct _FontManagerAdjustablePreviewPrivate FontManagerAdjustablePreviewPrivate;

#define FONT_MANAGER_TYPE_FONT_SCALE (font_manager_font_scale_get_type ())
#define FONT_MANAGER_FONT_SCALE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FONT_MANAGER_TYPE_FONT_SCALE, FontManagerFontScale))
#define FONT_MANAGER_FONT_SCALE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FONT_MANAGER_TYPE_FONT_SCALE, FontManagerFontScaleClass))
#define FONT_MANAGER_IS_FONT_SCALE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FONT_MANAGER_TYPE_FONT_SCALE))
#define FONT_MANAGER_IS_FONT_SCALE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FONT_MANAGER_TYPE_FONT_SCALE))
#define FONT_MANAGER_FONT_SCALE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FONT_MANAGER_TYPE_FONT_SCALE, FontManagerFontScaleClass))

typedef struct _FontManagerFontScale FontManagerFontScale;
typedef struct _FontManagerFontScaleClass FontManagerFontScaleClass;

#define FONT_MANAGER_TYPE_TEXT_PREVIEW (font_manager_text_preview_get_type ())
#define FONT_MANAGER_TEXT_PREVIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FONT_MANAGER_TYPE_TEXT_PREVIEW, FontManagerTextPreview))
#define FONT_MANAGER_TEXT_PREVIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FONT_MANAGER_TYPE_TEXT_PREVIEW, FontManagerTextPreviewClass))
#define FONT_MANAGER_IS_TEXT_PREVIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FONT_MANAGER_TYPE_TEXT_PREVIEW))
#define FONT_MANAGER_IS_TEXT_PREVIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FONT_MANAGER_TYPE_TEXT_PREVIEW))
#define FONT_MANAGER_TEXT_PREVIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FONT_MANAGER_TYPE_TEXT_PREVIEW, FontManagerTextPreviewClass))

typedef struct _FontManagerTextPreview FontManagerTextPreview;
typedef struct _FontManagerTextPreviewClass FontManagerTextPreviewClass;
typedef struct _FontManagerTextPreviewPrivate FontManagerTextPreviewPrivate;

#define FONT_MANAGER_TYPE_STANDARD_TEXT_VIEW (font_manager_standard_text_view_get_type ())
#define FONT_MANAGER_STANDARD_TEXT_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FONT_MANAGER_TYPE_STANDARD_TEXT_VIEW, FontManagerStandardTextView))
#define FONT_MANAGER_STANDARD_TEXT_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FONT_MANAGER_TYPE_STANDARD_TEXT_VIEW, FontManagerStandardTextViewClass))
#define FONT_MANAGER_IS_STANDARD_TEXT_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FONT_MANAGER_TYPE_STANDARD_TEXT_VIEW))
#define FONT_MANAGER_IS_STANDARD_TEXT_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FONT_MANAGER_TYPE_STANDARD_TEXT_VIEW))
#define FONT_MANAGER_STANDARD_TEXT_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FONT_MANAGER_TYPE_STANDARD_TEXT_VIEW, FontManagerStandardTextViewClass))

typedef struct _FontManagerStandardTextView FontManagerStandardTextView;
typedef struct _FontManagerStandardTextViewClass FontManagerStandardTextViewClass;

#define FONT_MANAGER_TYPE_STATIC_TEXT_VIEW (font_manager_static_text_view_get_type ())
#define FONT_MANAGER_STATIC_TEXT_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FONT_MANAGER_TYPE_STATIC_TEXT_VIEW, FontManagerStaticTextView))
#define FONT_MANAGER_STATIC_TEXT_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FONT_MANAGER_TYPE_STATIC_TEXT_VIEW, FontManagerStaticTextViewClass))
#define FONT_MANAGER_IS_STATIC_TEXT_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FONT_MANAGER_TYPE_STATIC_TEXT_VIEW))
#define FONT_MANAGER_IS_STATIC_TEXT_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FONT_MANAGER_TYPE_STATIC_TEXT_VIEW))
#define FONT_MANAGER_STATIC_TEXT_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FONT_MANAGER_TYPE_STATIC_TEXT_VIEW, FontManagerStaticTextViewClass))

typedef struct _FontManagerStaticTextView FontManagerStaticTextView;
typedef struct _FontManagerStaticTextViewClass FontManagerStaticTextViewClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define __vala_PangoFontDescription_free0(var) ((var == NULL) ? NULL : (var = (_vala_PangoFontDescription_free (var), NULL)))

#define FONT_MANAGER_TYPE_STANDARD_TEXT_TAG_TABLE (font_manager_standard_text_tag_table_get_type ())
#define FONT_MANAGER_STANDARD_TEXT_TAG_TABLE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FONT_MANAGER_TYPE_STANDARD_TEXT_TAG_TABLE, FontManagerStandardTextTagTable))
#define FONT_MANAGER_STANDARD_TEXT_TAG_TABLE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FONT_MANAGER_TYPE_STANDARD_TEXT_TAG_TABLE, FontManagerStandardTextTagTableClass))
#define FONT_MANAGER_IS_STANDARD_TEXT_TAG_TABLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FONT_MANAGER_TYPE_STANDARD_TEXT_TAG_TABLE))
#define FONT_MANAGER_IS_STANDARD_TEXT_TAG_TABLE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FONT_MANAGER_TYPE_STANDARD_TEXT_TAG_TABLE))
#define FONT_MANAGER_STANDARD_TEXT_TAG_TABLE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FONT_MANAGER_TYPE_STANDARD_TEXT_TAG_TABLE, FontManagerStandardTextTagTableClass))

typedef struct _FontManagerStandardTextTagTable FontManagerStandardTextTagTable;
typedef struct _FontManagerStandardTextTagTableClass FontManagerStandardTextTagTableClass;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _FontManagerAdjustablePreview {
	GtkBox parent_instance;
	FontManagerAdjustablePreviewPrivate * priv;
	gdouble _preview_size;
	FontManagerFontScale* fontscale;
};

struct _FontManagerAdjustablePreviewClass {
	GtkBoxClass parent_class;
	void (*set_preview_size_internal) (FontManagerAdjustablePreview* self, gdouble new_size);
	void (*init) (FontManagerAdjustablePreview* self);
};

struct _FontManagerTextPreview {
	FontManagerAdjustablePreview parent_instance;
	FontManagerTextPreviewPrivate * priv;
};

struct _FontManagerTextPreviewClass {
	FontManagerAdjustablePreviewClass parent_class;
};

struct _FontManagerTextPreviewPrivate {
	FontManagerStaticTextView* _preview;
	PangoFontDescription* _font_desc;
};


static gpointer font_manager_text_preview_parent_class = NULL;

GType font_manager_adjustable_preview_get_type (void) G_GNUC_CONST;
GType font_manager_font_scale_get_type (void) G_GNUC_CONST;
GType font_manager_text_preview_get_type (void) G_GNUC_CONST;
GType font_manager_standard_text_view_get_type (void) G_GNUC_CONST;
GType font_manager_static_text_view_get_type (void) G_GNUC_CONST;
#define FONT_MANAGER_TEXT_PREVIEW_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), FONT_MANAGER_TYPE_TEXT_PREVIEW, FontManagerTextPreviewPrivate))
enum  {
	FONT_MANAGER_TEXT_PREVIEW_DUMMY_PROPERTY,
	FONT_MANAGER_TEXT_PREVIEW_PREVIEW,
	FONT_MANAGER_TEXT_PREVIEW_FONT_DESC
};
static void _vala_PangoFontDescription_free (PangoFontDescription* self);
GType font_manager_standard_text_tag_table_get_type (void) G_GNUC_CONST;
FontManagerTextPreview* font_manager_text_preview_new (FontManagerStandardTextTagTable* tag_table);
FontManagerTextPreview* font_manager_text_preview_construct (GType object_type, FontManagerStandardTextTagTable* tag_table);
FontManagerAdjustablePreview* font_manager_adjustable_preview_construct (GType object_type);
void font_manager_adjustable_preview_init (FontManagerAdjustablePreview* self);
void font_manager_font_scale_add_style_class (FontManagerFontScale* self, const gchar* gtk_style_class);
FontManagerStaticTextView* font_manager_static_text_view_new (FontManagerStandardTextTagTable* tag_table);
FontManagerStaticTextView* font_manager_static_text_view_construct (GType object_type, FontManagerStandardTextTagTable* tag_table);
static void font_manager_text_preview_set_preview (FontManagerTextPreview* self, FontManagerStaticTextView* value);
FontManagerStaticTextView* font_manager_text_preview_get_preview (FontManagerTextPreview* self);
GtkTextView* font_manager_standard_text_view_get_view (FontManagerStandardTextView* self);
void font_manager_text_preview_set_preview_text (FontManagerTextPreview* self, const gchar* preview_text);
#define FONT_MANAGER_LOREM_IPSUM "\n" \
"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent sed " \
"tristique nunc. Sed augue dolor, posuere a auctor quis, dignissim sed " \
"est. Aliquam convallis, orci nec posuere lacinia, risus libero mattis " \
"velit, a consectetur orci felis venenatis neque. Praesent id lacinia m" \
"assa. Nam risus diam, faucibus vitae pulvinar eget, scelerisque nec ni" \
"sl. Integer dolor ligula, placerat id elementum id, venenatis sed mass" \
"a. Vestibulum at convallis libero. Curabitur at molestie justo.\n" \
"\n" \
"Mauris convallis odio rutrum elit aliquet quis fermentum velit tempus." \
" Ut porttitor lectus at dui iaculis in vestibulum eros tristique. Vest" \
"ibulum ante ipsum primis in faucibus orci luctus et ultrices posuere c" \
"ubilia Curae; Donec ut dui massa, at aliquet leo. Cras sagittis pulvin" \
"ar nunc. Fusce eget felis ut dolor blandit scelerisque non eget risus." \
" Nunc elementum ipsum id lacus porttitor accumsan. Suspendisse at quam" \
" ligula, ultrices bibendum massa.\n" \
"\n" \
"Mauris feugiat, orci non fermentum congue, libero est rutrum sem, non " \
"dignissim justo urna at turpis. Donec non varius augue. Fusce id enim " \
"ligula, sit amet mattis urna. Ut sodales augue tristique tortor lobort" \
"is vestibulum. Maecenas quis tortor lacus. Etiam varius hendrerit bibe" \
"ndum. Nullam pretium nulla in sem blandit vel facilisis felis fermentu" \
"m. Integer aliquet leo nec nunc sollicitudin congue. In hac habitasse " \
"platea dictumst. Curabitur mattis nibh ac velit euismod condimentum. P" \
"ellentesque volutpat, neque ac congue fermentum, turpis metus posuere " \
"turpis, ac facilisis velit lectus sed diam. Etiam dui diam, tempus vit" \
"ae fringilla quis, tincidunt ac libero.\n" \
"\n" \
"Quisque sollicitudin eros sit amet lorem semper nec imperdiet ante veh" \
"icula. Proin a vulputate sem. Aliquam erat volutpat. Vestibulum congue" \
" pulvinar eros eu vestibulum. Phasellus metus mauris, suscipit tristiq" \
"ue ullamcorper laoreet, viverra eget libero. Donec id nibh justo. Aliq" \
"uam sagittis ultricies erat. Integer sed purus felis. Pellentesque leo" \
" nisi, sagittis non tincidunt vitae, porta quis eros. Pellentesque ut " \
"ornare erat. Vivamus semper sodales suscipit. Praesent placerat eleife" \
"nd nibh quis tristique. Aenean ullamcorper pellentesque ultrices. Nunc" \
" eu risus turpis, in condimentum dui. Aliquam erat volutpat. Phasellus" \
" sagittis mattis diam, sit amet pharetra lacus cursus non.\n" \
"\n" \
"Vestibulum sed est id velit rhoncus imperdiet. Aliquam dictum, arcu at" \
" tincidunt condimentum, metus ligula molestie lorem, eget congue torto" \
"r est ut massa. Duis ut pulvinar nisl. Aenean sodales purus id risus h" \
"endrerit sit amet mattis sem blandit. Aenean feugiat dapibus mattis. P" \
"raesent non nibh magna. Nulla facilisi. Nam elementum malesuada sagitt" \
"is. Cras et tellus augue, non rhoncus libero. Suspendisse ut nulla mau" \
"ris.\n" \
"\n" \
"Suspendisse potenti. Nulla neque leo, condimentum nec posuere non, ele" \
"mentum sit amet lorem. Integer ut ante libero, a tristique quam. Nulla" \
" libero nibh, bibendum eget blandit non, viverra in velit. Duis sit am" \
"et ipsum in massa imperdiet interdum. Phasellus venenatis consequat le" \
"ctus eget facilisis. Quisque ullamcorper rutrum erat at egestas. Integ" \
"er pharetra pulvinar odio, sagittis imperdiet ligula aliquam suscipit." \
" Aenean rutrum convallis felis, at rhoncus lectus tincidunt et. Morbi " \
"mattis risus eu quam suscipit ut tempus nunc pellentesque. Ut adipisci" \
"ng, nibh nec pharetra fringilla, diam diam hendrerit neque, quis preti" \
"um tellus ligula ut dolor. Nullam dictum, libero in molestie convallis" \
", nunc arcu imperdiet risus, vitae laoreet risus ipsum in ligula. Clas" \
"s aptent taciti sociosqu ad litora torquent per conubia nostra, per in" \
"ceptos himenaeos. Donec molestie, quam ut adipiscing consequat, risus " \
"sem facilisis nisi, ut aliquet sapien est a sapien. Quisque sed enim j" \
"usto, sit amet volutpat urna.\n" \
"\n" \
"Integer faucibus, velit sit amet aliquam fermentum, turpis massa facil" \
"isis nunc, eu vulputate lorem sapien at sapien. Quisque sed lacus non " \
"massa varius fermentum. Fusce non consectetur odio. Integer tincidunt " \
"tincidunt ullamcorper. In hac habitasse platea dictumst. Donec tellus " \
"est, feugiat in auctor sed, sodales non urna. Curabitur semper cursus " \
"eros, id hendrerit tortor pulvinar at. Mauris gravida odio vel lorem m" \
"attis varius. Donec vulputate aliquam dui et dignissim. Pellentesque c" \
"onsectetur nisi sit amet libero consectetur quis imperdiet libero tris" \
"tique. Praesent nec enim ante. Proin quam mauris, vehicula vel loborti" \
"s at, tempor vitae augue. Sed ut urna vel eros facilisis mollis vulput" \
"ate at nisl. Integer lobortis magna vitae urna varius tristique. In ha" \
"c habitasse platea dictumst.\n" \
"\n" \
"Sed ac molestie ante. Fusce ultrices laoreet felis ac lobortis. Curabi" \
"tur a vulputate risus. Suspendisse auctor pulvinar semper. Mauris nec " \
"ipsum vitae justo malesuada tincidunt. In suscipit porttitor nibh, at " \
"convallis justo ultrices ac. Sed vitae turpis vel quam malesuada gravi" \
"da a non ante.\n" \
"\n" \
"Suspendisse sit amet felis sit amet nisl lacinia ultrices ut vitae tel" \
"lus. In hac habitasse platea dictumst. In hac habitasse platea dictums" \
"t. Sed interdum porta dui, in placerat arcu porttitor vel. Nullam just" \
"o velit, blandit ut accumsan id, ullamcorper sed lacus. Nullam sceleri" \
"sque tellus vitae nisi placerat sollicitudin. Integer massa erat, faci" \
"lisis sed porta eu, porttitor at leo. Praesent mauris mi, tincidunt id" \
" cursus et, consequat sit amet arcu. Sed posuere erat nec nunc hendrer" \
"it id semper quam facilisis. Curabitur pretium placerat neque at sodal" \
"es.\n" \
"\n" \
"Etiam augue eros, dictum eu adipiscing in, aliquam quis dui. Pellentes" \
"que auctor sem mattis magna faucibus vulputate. Nam arcu purus, eleife" \
"nd eget sagittis ac, posuere a lorem. Aenean urna magna, viverra quis " \
"commodo vitae, gravida eget arcu. Maecenas ut turpis magna, mattis gra" \
"vida risus. Cum sociis natoque penatibus et magnis dis parturient mont" \
"es, nascetur ridiculus mus. Donec eu libero sem. Donec eget nibh id tu" \
"rpis convallis tincidunt. Fusce vulputate tempor tempor.\n" \
"\n" \
"Nunc eleifend metus in augue rhoncus sodales. Nam vel enim at neque tr" \
"istique accumsan. Nunc ac venenatis massa. Morbi gravida facilisis odi" \
"o sit amet venenatis. Maecenas sodales euismod nisi eu bibendum. Duis " \
"tempor pulvinar diam, nec mollis risus viverra quis. Nullam ipsum maur" \
"is, fringilla eget vulputate a, euismod ac urna. Nam eu eros sapien. P" \
"hasellus et eros lorem. Quisque varius porta pharetra. Donec vel liber" \
"o euismod arcu pharetra tincidunt. Sed sit amet neque erat. Mauris dic" \
"tum nisi quis risus tincidunt pellentesque. Maecenas accumsan elit rho" \
"ncus tortor elementum pretium. Donec dictum convallis lectus in fermen" \
"tum. Mauris accumsan, turpis ac consectetur varius, lacus metus sagitt" \
"is neque, in tincidunt dui enim id diam.\n" \
"\n" \
"Aenean lacinia eros nec enim cursus at porttitor quam suscipit. Nam qu" \
"am turpis, iaculis et congue non, dignissim nec neque. Mauris nec erat" \
" erat, vitae ornare velit. Aenean suscipit, eros eu cursus imperdiet, " \
"felis lacus lobortis metus, ac laoreet tellus nunc id arcu. Etiam libe" \
"ro mi, pellentesque in feugiat nec, tincidunt in sapien. Fusce eu mi s" \
"ed libero ullamcorper congue. Suspendisse eu sem sed arcu pulvinar ves" \
"tibulum vel in lorem. Phasellus aliquam elementum iaculis. Etiam dictu" \
"m luctus nisi sit amet mattis. Mauris mollis placerat varius.\n" \
"\n" \
"Cras ultricies elit eget lectus sagittis sit amet rutrum enim tempus. " \
"Vivamus a risus pharetra nibh dapibus volutpat vitae sed arcu. Class a" \
"ptent taciti sociosqu ad litora torquent per conubia nostra, per incep" \
"tos himenaeos. Quisque a augue nibh, nec congue metus. Integer element" \
"um, purus sit amet vehicula gravida, mi magna hendrerit turpis, at ali" \
"quam purus velit eget tortor. Integer suscipit posuere massa, quis cur" \
"sus massa tincidunt id. Integer placerat quam quis massa dapibus egest" \
"as at eu lorem. Aenean quis nunc sed massa lobortis tincidunt. Phasell" \
"us quis sem dolor. Phasellus auctor ipsum at ligula euismod eu sagitti" \
"s justo dapibus. Pellentesque pulvinar, magna eget interdum eleifend, " \
"urna lectus adipiscing dui, eu cursus nulla tellus in lacus. Vivamus q" \
"uis urna magna, a placerat est. Nullam justo tellus, elementum at vive" \
"rra at, posuere quis magna.\n" \
"\n" \
"Sed non est sed nibh blandit tincidunt. Fusce nec sem a mi mollis cond" \
"imentum. Nulla ut lacinia tellus. Vestibulum iaculis fermentum risus, " \
"vel lobortis lorem posuere quis. Donec consequat ligula et arcu faucib" \
"us sed tempor sem ullamcorper. Curabitur sapien odio, egestas non cong" \
"ue id, dapibus non nisl. Nam euismod, massa eu laoreet tincidunt, veli" \
"t mi pharetra dolor, laoreet suscipit quam erat vel felis. Praesent vu" \
"lputate ipsum et elit scelerisque rhoncus. Nam ligula magna, gravida a" \
"c varius at, facilisis vitae ipsum. Praesent eleifend eleifend massa, " \
"tincidunt pharetra felis tincidunt nec. Etiam eu sapien lorem. Donec e" \
"uismod faucibus erat a semper. Duis pharetra nulla at libero sollicitu" \
"din sed vestibulum diam egestas. Nam dignissim quam et massa placerat " \
"ac tincidunt nulla dapibus. Curabitur mi mi, sagittis id pharetra sed," \
" semper eu ligula. Phasellus eu venenatis elit.\n" \
"\n" \
"Ut mi libero, pharetra in vestibulum et, blandit ac purus. Donec sit a" \
"met scelerisque massa. Morbi commodo nisi non mi rhoncus vel pharetra " \
"lorem rutrum. Nulla eget arcu augue. Nunc ullamcorper, sapien ut imper" \
"diet imperdiet, lorem mauris commodo justo, sit amet sodales nisl sem " \
"id turpis. Sed interdum sem dictum neque ullamcorper varius. Nulla ele" \
"mentum pharetra scelerisque. Fusce ut augue non mauris suscipit consec" \
"tetur id vel justo. Vestibulum ante ipsum primis in faucibus orci luct" \
"us et ultrices posuere cubilia Curae; Phasellus metus nulla, tempus fa" \
"cilisis pharetra ut, aliquam a arcu.\n" \
"\n" \
"Morbi porttitor posuere rutrum. Nulla facilisi. Nam risus lorem, variu" \
"s at fermentum id, euismod eget tellus. Quisque ut interdum leo. Etiam" \
" eget neque urna, vitae iaculis ante. Curabitur semper nisl vel orci h" \
"endrerit accumsan. Phasellus vel mi ac tellus rhoncus viverra sit amet" \
" lobortis mauris. Vestibulum pharetra tristique enim, a mattis dolor c" \
"onsequat quis. Aenean auctor, mi quis rhoncus iaculis, urna ante condi" \
"mentum ligula, ac feugiat ipsum diam sit amet libero. Donec ac sapien " \
"ut quam ultrices pellentesque. Aenean venenatis ornare enim sed congue" \
". Integer nec est massa. Pellentesque tincidunt justo at magna dictum " \
"blandit. Maecenas ipsum velit, condimentum ut pharetra quis, aliquet c" \
"onsequat tellus.\n" \
"\n" \
"Mauris faucibus augue ut massa faucibus id hendrerit justo rutrum. Don" \
"ec accumsan odio vel turpis dignissim mattis. Suspendisse magna eros, " \
"tempus vel commodo eu, aliquet sed libero. Ut fermentum dui quis lorem" \
" scelerisque lobortis. Aliquam volutpat odio id velit malesuada condim" \
"entum. Nulla facilisi. Donec sed nisi eget risus adipiscing rutrum. Du" \
"is egestas scelerisque eleifend. Mauris neque ligula, ullamcorper sed " \
"tincidunt aliquet, facilisis non dolor. Mauris eget elit leo. Donec su" \
"scipit, felis sed auctor tincidunt, arcu velit posuere elit, malesuada" \
" molestie libero quam nec mauris.\n" \
"\n" \
"Morbi non nunc faucibus sem rutrum aliquam eget nec nisi. Donec iaculi" \
"s, arcu at elementum sollicitudin, libero enim dictum tellus, et pelle" \
"ntesque turpis erat aliquet dolor. Etiam et magna in nisi pharetra con" \
"sectetur. Phasellus accumsan volutpat nibh non dictum. Pellentesque pr" \
"etium tellus id neque ultricies iaculis. Ut a libero eget dolor portti" \
"tor hendrerit. Integer eleifend elit quis turpis lacinia vitae sceleri" \
"sque leo gravida.\n" \
"\n" \
"Curabitur tempor eros vitae velit ultrices ornare. Class aptent taciti" \
" sociosqu ad litora torquent per conubia nostra, per inceptos himenaeo" \
"s. Mauris tristique erat ac arcu gravida non dictum magna aliquam. Pha" \
"sellus eu velit quis est ullamcorper pharetra. Aenean vestibulum gravi" \
"da urna, vitae posuere libero dapibus ac. Etiam a massa eget felis tin" \
"cidunt pellentesque. Nulla facilisi. Nullam odio dui, commodo eu vulpu" \
"tate quis, feugiat in ipsum. Sed sed viverra sapien.\n" \
"\n" \
"Mauris consectetur neque ut mauris feugiat et rhoncus purus gravida. N" \
"am nibh sem, iaculis at lacinia vitae, faucibus lobortis mauris. Maece" \
"nas ornare urna sit amet eros blandit pulvinar. Suspendisse nisi massa" \
", ornare vitae vestibulum eget, dictum nec leo. Phasellus et risus ris" \
"us. Suspendisse potenti. Donec imperdiet eleifend dui tincidunt sodale" \
"s.\n" \
"\n" \
"Morbi ac erat nisi. Maecenas mi ante, rutrum at rhoncus viverra, facil" \
"isis quis turpis. Ut in lacus diam, ac euismod quam. Etiam auctor ultr" \
"icies consectetur. Vivamus semper, sem nec posuere eleifend, tortor lo" \
"rem sagittis urna, eu iaculis tortor leo et ligula. Nam vitae libero t" \
"ellus, vitae rutrum nulla. Phasellus suscipit massa eget mauris pharet" \
"ra adipiscing. Donec mattis sem in leo sollicitudin vitae tempus lorem" \
" tincidunt. Fusce sagittis metus sit amet ante scelerisque ut vulputat" \
"e felis venenatis. Cum sociis natoque penatibus et magnis dis parturie" \
"nt montes, nascetur ridiculus mus. Nulla dictum arcu eget metus sagitt" \
"is faucibus. Nulla eget mauris a tellus ornare dictum ac eu massa. Ves" \
"tibulum dapibus, turpis non adipiscing convallis, nisi turpis pharetra" \
" elit, ac tincidunt sem dui sit amet lacus. Pellentesque ac mi lacus, " \
"volutpat cursus leo. Ut ac sollicitudin nibh.\n" \
"\n" \
"Phasellus et porta risus. Ut a neque quam. Aliquam euismod diam vitae " \
"felis sodales pellentesque non sit amet ipsum. In lorem arcu, posuere " \
"at elementum at, malesuada in mauris. In viverra adipiscing adipiscing" \
". Cum sociis natoque penatibus et magnis dis parturient montes, nascet" \
"ur ridiculus mus. Sed ut lacus purus, non egestas quam. Curabitur conv" \
"allis, ipsum quis egestas varius, odio tellus accumsan ipsum, et inter" \
"dum eros felis posuere lorem. Fusce congue viverra quam, sed ullamcorp" \
"er orci euismod non. Vestibulum semper turpis eu turpis mollis eget al" \
"iquam turpis dapibus. Praesent volutpat justo eget ligula facilisis no" \
"n fermentum lorem consequat. Phasellus ac diam erat. Phasellus nisi le" \
"o, aliquet posuere facilisis eu, mattis non tellus. Pellentesque eros " \
"metus, pretium venenatis pharetra vel, ullamcorper ac est. Sed massa a" \
"nte, fermentum in tincidunt ac, eleifend eget turpis.\n" \
"\n" \
"Nullam commodo dui at quam pulvinar a luctus sapien pretium. In hendre" \
"rit pretium consectetur. Class aptent taciti sociosqu ad litora torque" \
"nt per conubia nostra, per inceptos himenaeos. Nam aliquet erat vel lo" \
"rem feugiat tincidunt. Ut eget magna lectus. Aliquam augue eros, gravi" \
"da vel commodo vel, interdum sit amet sapien. Sed nec turpis enim, a f" \
"aucibus orci. Nullam non lectus risus, vitae laoreet metus. Praesent i" \
"n erat dui. Ut ac laoreet nibh. Sed tortor eros, ultrices eu dapibus e" \
"t, tristique in quam. Vivamus id lacinia lacus. Sed et elit mi. Nullam" \
" erat purus, posuere at mollis in, tempor ut risus. Vivamus sollicitud" \
"in scelerisque vehicula.\n" \
"\n" \
"Morbi nec volutpat nulla. Sed venenatis ligula nec magna luctus sagitt" \
"is. Ut faucibus diam in lorem vulputate id porta turpis venenatis. Dui" \
"s tempus cursus erat, sit amet sollicitudin erat faucibus sit amet. Do" \
"nec facilisis, orci eget ultricies semper, elit ante euismod purus, at" \
" pretium turpis metus ac sapien. Pellentesque quis sem eget ante congu" \
"e gravida at sit amet erat. Nam condimentum arcu ut urna scelerisque e" \
"t fermentum mauris sagittis. In mauris lectus, accumsan eu malesuada e" \
"u, congue at nulla. Nulla dui elit, sodales non fermentum eget, iaculi" \
"s vitae est. Lorem ipsum dolor sit amet, consectetur adipiscing elit. " \
"Morbi arcu eros, ultricies a hendrerit a, faucibus in nibh. Vestibulum" \
" diam sapien, facilisis et placerat a, sodales ut leo. In luctus ligul" \
"a quis purus scelerisque varius ac id eros. Mauris consequat pulvinar " \
"diam at commodo.\n" \
"\n" \
"Vestibulum lobortis viverra quam, quis posuere est tincidunt nec. Vest" \
"ibulum ac elit non ligula faucibus pretium laoreet vel erat. Fusce sod" \
"ales, erat et condimentum luctus, justo lorem gravida tortor, eget con" \
"sequat orci risus ac metus. Sed pulvinar pretium felis et porta. Aliqu" \
"am erat volutpat. Integer pellentesque aliquam odio eu facilisis. Aene" \
"an ultrices felis eget risus tempus pulvinar. Pellentesque eros mi, gr" \
"avida vel condimentum nec, ornare ac neque. Phasellus risus ligula, ve" \
"hicula non varius non, tincidunt at arcu. Quisque at quam a lorem aliq" \
"uet tempus vel non sapien.\n"
static void font_manager_text_preview_real_show (GtkWidget* base);
gchar* font_manager_text_preview_get_buffer_text (FontManagerTextPreview* self);
gchar* font_manager_standard_text_view_get_buffer_text (FontManagerStandardTextView* self);
GtkTextBuffer* font_manager_standard_text_view_get_buffer (FontManagerStandardTextView* self);
void font_manager_text_preview_update (FontManagerTextPreview* self);
GtkTextTagTable* font_manager_standard_text_view_get_tag_table (FontManagerStandardTextView* self);
static void font_manager_text_preview_real_set_preview_size_internal (FontManagerAdjustablePreview* base, gdouble new_size);
PangoFontDescription* font_manager_text_preview_get_font_desc (FontManagerTextPreview* self);
void font_manager_text_preview_set_font_desc (FontManagerTextPreview* self, PangoFontDescription* value);
static PangoFontDescription* _vala_PangoFontDescription_copy (PangoFontDescription* self);
static void font_manager_text_preview_finalize (GObject* obj);
static void _vala_font_manager_text_preview_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_font_manager_text_preview_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


static void _vala_PangoFontDescription_free (PangoFontDescription* self) {
	g_boxed_free (pango_font_description_get_type (), self);
}


FontManagerTextPreview* font_manager_text_preview_construct (GType object_type, FontManagerStandardTextTagTable* tag_table) {
	FontManagerTextPreview * self = NULL;
	FontManagerFontScale* _tmp0_ = NULL;
	FontManagerStandardTextTagTable* _tmp1_ = NULL;
	FontManagerStaticTextView* _tmp2_ = NULL;
	FontManagerStaticTextView* _tmp3_ = NULL;
	FontManagerStaticTextView* _tmp4_ = NULL;
	GtkTextView* _tmp5_ = NULL;
	GtkTextView* _tmp6_ = NULL;
	FontManagerStaticTextView* _tmp7_ = NULL;
	GtkTextView* _tmp8_ = NULL;
	GtkTextView* _tmp9_ = NULL;
	FontManagerStaticTextView* _tmp10_ = NULL;
	GtkTextView* _tmp11_ = NULL;
	GtkTextView* _tmp12_ = NULL;
	FontManagerStaticTextView* _tmp13_ = NULL;
	FontManagerFontScale* _tmp14_ = NULL;
	g_return_val_if_fail (tag_table != NULL, NULL);
	self = (FontManagerTextPreview*) font_manager_adjustable_preview_construct (object_type);
	FONT_MANAGER_ADJUSTABLE_PREVIEW_CLASS (font_manager_text_preview_parent_class)->init (G_TYPE_CHECK_INSTANCE_CAST (self, FONT_MANAGER_TYPE_ADJUSTABLE_PREVIEW, FontManagerAdjustablePreview));
	gtk_orientable_set_orientation ((GtkOrientable*) self, GTK_ORIENTATION_VERTICAL);
	_tmp0_ = ((FontManagerAdjustablePreview*) self)->fontscale;
	font_manager_font_scale_add_style_class (_tmp0_, GTK_STYLE_CLASS_VIEW);
	_tmp1_ = tag_table;
	_tmp2_ = font_manager_static_text_view_new (_tmp1_);
	g_object_ref_sink (_tmp2_);
	_tmp3_ = _tmp2_;
	font_manager_text_preview_set_preview (self, _tmp3_);
	_g_object_unref0 (_tmp3_);
	_tmp4_ = self->priv->_preview;
	_tmp5_ = font_manager_standard_text_view_get_view ((FontManagerStandardTextView*) _tmp4_);
	_tmp6_ = _tmp5_;
	gtk_text_view_set_left_margin (_tmp6_, 12);
	_tmp7_ = self->priv->_preview;
	_tmp8_ = font_manager_standard_text_view_get_view ((FontManagerStandardTextView*) _tmp7_);
	_tmp9_ = _tmp8_;
	gtk_text_view_set_right_margin (_tmp9_, 12);
	_tmp10_ = self->priv->_preview;
	_tmp11_ = font_manager_standard_text_view_get_view ((FontManagerStandardTextView*) _tmp10_);
	_tmp12_ = _tmp11_;
	gtk_text_view_set_justification (_tmp12_, GTK_JUSTIFY_FILL);
	font_manager_text_preview_set_preview_text (self, FONT_MANAGER_LOREM_IPSUM);
	_tmp13_ = self->priv->_preview;
	gtk_box_pack_start ((GtkBox*) self, (GtkWidget*) _tmp13_, TRUE, TRUE, (guint) 0);
	_tmp14_ = ((FontManagerAdjustablePreview*) self)->fontscale;
	gtk_box_pack_end ((GtkBox*) self, (GtkWidget*) _tmp14_, FALSE, TRUE, (guint) 0);
	return self;
}


FontManagerTextPreview* font_manager_text_preview_new (FontManagerStandardTextTagTable* tag_table) {
	return font_manager_text_preview_construct (FONT_MANAGER_TYPE_TEXT_PREVIEW, tag_table);
}


static void font_manager_text_preview_real_show (GtkWidget* base) {
	FontManagerTextPreview * self;
	FontManagerStaticTextView* _tmp0_ = NULL;
	FontManagerFontScale* _tmp1_ = NULL;
	self = (FontManagerTextPreview*) base;
	_tmp0_ = self->priv->_preview;
	gtk_widget_show ((GtkWidget*) _tmp0_);
	_tmp1_ = ((FontManagerAdjustablePreview*) self)->fontscale;
	gtk_widget_show ((GtkWidget*) _tmp1_);
	GTK_WIDGET_CLASS (font_manager_text_preview_parent_class)->show ((GtkWidget*) G_TYPE_CHECK_INSTANCE_CAST (self, FONT_MANAGER_TYPE_ADJUSTABLE_PREVIEW, FontManagerAdjustablePreview));
	return;
}


gchar* font_manager_text_preview_get_buffer_text (FontManagerTextPreview* self) {
	gchar* result = NULL;
	FontManagerStaticTextView* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_preview;
	_tmp1_ = font_manager_standard_text_view_get_buffer_text ((FontManagerStandardTextView*) _tmp0_);
	result = _tmp1_;
	return result;
}


void font_manager_text_preview_set_preview_text (FontManagerTextPreview* self, const gchar* preview_text) {
	FontManagerStaticTextView* _tmp0_ = NULL;
	GtkTextBuffer* _tmp1_ = NULL;
	GtkTextBuffer* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (preview_text != NULL);
	_tmp0_ = self->priv->_preview;
	_tmp1_ = font_manager_standard_text_view_get_buffer ((FontManagerStandardTextView*) _tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = preview_text;
	gtk_text_buffer_set_text (_tmp2_, _tmp3_, -1);
	return;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


void font_manager_text_preview_update (FontManagerTextPreview* self) {
	GtkTextBuffer* buffer = NULL;
	FontManagerStaticTextView* _tmp0_ = NULL;
	GtkTextBuffer* _tmp1_ = NULL;
	GtkTextBuffer* _tmp2_ = NULL;
	GtkTextBuffer* _tmp3_ = NULL;
	GtkTextIter start = {0};
	GtkTextIter end = {0};
	GtkTextIter _tmp4_ = {0};
	GtkTextIter _tmp5_ = {0};
	FontManagerStaticTextView* _tmp6_ = NULL;
	GtkTextTagTable* _tmp7_ = NULL;
	GtkTextTagTable* _tmp8_ = NULL;
	GtkTextTag* _tmp9_ = NULL;
	GtkTextIter _tmp10_ = {0};
	GtkTextIter _tmp11_ = {0};
	FontManagerStaticTextView* _tmp12_ = NULL;
	GtkTextTagTable* _tmp13_ = NULL;
	GtkTextTagTable* _tmp14_ = NULL;
	GtkTextTag* _tmp15_ = NULL;
	GtkTextIter _tmp16_ = {0};
	GtkTextIter _tmp17_ = {0};
	FontManagerStaticTextView* _tmp18_ = NULL;
	GtkTextView* _tmp19_ = NULL;
	GtkTextView* _tmp20_ = NULL;
	PangoFontDescription* _tmp21_ = NULL;
	gchar* _tmp22_ = NULL;
	gchar* _tmp23_ = NULL;
	FontManagerStaticTextView* _tmp24_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->_preview;
	_tmp1_ = font_manager_standard_text_view_get_buffer ((FontManagerStandardTextView*) _tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = _g_object_ref0 (_tmp2_);
	buffer = _tmp3_;
	gtk_text_buffer_get_bounds (buffer, &_tmp4_, &_tmp5_);
	start = _tmp4_;
	end = _tmp5_;
	_tmp6_ = self->priv->_preview;
	_tmp7_ = font_manager_standard_text_view_get_tag_table ((FontManagerStandardTextView*) _tmp6_);
	_tmp8_ = _tmp7_;
	_tmp9_ = gtk_text_tag_table_lookup (_tmp8_, "FontDescription");
	_tmp10_ = start;
	_tmp11_ = end;
	gtk_text_buffer_apply_tag (buffer, _tmp9_, &_tmp10_, &_tmp11_);
	_tmp12_ = self->priv->_preview;
	_tmp13_ = font_manager_standard_text_view_get_tag_table ((FontManagerStandardTextView*) _tmp12_);
	_tmp14_ = _tmp13_;
	_tmp15_ = gtk_text_tag_table_lookup (_tmp14_, "FontSize");
	_tmp16_ = start;
	_tmp17_ = end;
	gtk_text_buffer_apply_tag (buffer, _tmp15_, &_tmp16_, &_tmp17_);
	_tmp18_ = self->priv->_preview;
	_tmp19_ = font_manager_standard_text_view_get_view ((FontManagerStandardTextView*) _tmp18_);
	_tmp20_ = _tmp19_;
	_tmp21_ = self->priv->_font_desc;
	_tmp22_ = pango_font_description_to_string (_tmp21_);
	_tmp23_ = _tmp22_;
	gtk_widget_set_tooltip_text ((GtkWidget*) _tmp20_, _tmp23_);
	_g_free0 (_tmp23_);
	_tmp24_ = self->priv->_preview;
	gtk_widget_queue_draw ((GtkWidget*) _tmp24_);
	_g_object_unref0 (buffer);
	return;
}


static void font_manager_text_preview_real_set_preview_size_internal (FontManagerAdjustablePreview* base, gdouble new_size) {
	FontManagerTextPreview * self;
	FontManagerStaticTextView* _tmp0_ = NULL;
	GtkTextTagTable* _tmp1_ = NULL;
	GtkTextTagTable* _tmp2_ = NULL;
	GtkTextTag* _tmp3_ = NULL;
	gdouble _tmp4_ = 0.0;
	self = (FontManagerTextPreview*) base;
	_tmp0_ = self->priv->_preview;
	_tmp1_ = font_manager_standard_text_view_get_tag_table ((FontManagerStandardTextView*) _tmp0_);
	_tmp2_ = _tmp1_;
	_tmp3_ = gtk_text_tag_table_lookup (_tmp2_, "FontSize");
	_tmp4_ = new_size;
	g_object_set (_tmp3_, "size-points", _tmp4_, NULL);
	font_manager_text_preview_update (self);
	return;
}


FontManagerStaticTextView* font_manager_text_preview_get_preview (FontManagerTextPreview* self) {
	FontManagerStaticTextView* result;
	FontManagerStaticTextView* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_preview;
	result = _tmp0_;
	return result;
}


static void font_manager_text_preview_set_preview (FontManagerTextPreview* self, FontManagerStaticTextView* value) {
	FontManagerStaticTextView* _tmp0_ = NULL;
	FontManagerStaticTextView* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_preview);
	self->priv->_preview = _tmp1_;
	g_object_notify ((GObject *) self, "preview");
}


PangoFontDescription* font_manager_text_preview_get_font_desc (FontManagerTextPreview* self) {
	PangoFontDescription* result;
	PangoFontDescription* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_font_desc;
	result = _tmp0_;
	return result;
}


static PangoFontDescription* _vala_PangoFontDescription_copy (PangoFontDescription* self) {
	return g_boxed_copy (pango_font_description_get_type (), self);
}


static gpointer __vala_PangoFontDescription_copy0 (gpointer self) {
	return self ? _vala_PangoFontDescription_copy (self) : NULL;
}


void font_manager_text_preview_set_font_desc (FontManagerTextPreview* self, PangoFontDescription* value) {
	PangoFontDescription* _tmp0_ = NULL;
	PangoFontDescription* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = __vala_PangoFontDescription_copy0 (_tmp0_);
	__vala_PangoFontDescription_free0 (self->priv->_font_desc);
	self->priv->_font_desc = _tmp1_;
	font_manager_text_preview_update (self);
	g_object_notify ((GObject *) self, "font-desc");
}


static void font_manager_text_preview_class_init (FontManagerTextPreviewClass * klass) {
	font_manager_text_preview_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (FontManagerTextPreviewPrivate));
	((GtkWidgetClass *) klass)->show = font_manager_text_preview_real_show;
	((FontManagerAdjustablePreviewClass *) klass)->set_preview_size_internal = font_manager_text_preview_real_set_preview_size_internal;
	G_OBJECT_CLASS (klass)->get_property = _vala_font_manager_text_preview_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_font_manager_text_preview_set_property;
	G_OBJECT_CLASS (klass)->finalize = font_manager_text_preview_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), FONT_MANAGER_TEXT_PREVIEW_PREVIEW, g_param_spec_object ("preview", "preview", "preview", FONT_MANAGER_TYPE_STATIC_TEXT_VIEW, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), FONT_MANAGER_TEXT_PREVIEW_FONT_DESC, g_param_spec_boxed ("font-desc", "font-desc", "font-desc", pango_font_description_get_type (), G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void font_manager_text_preview_instance_init (FontManagerTextPreview * self) {
	self->priv = FONT_MANAGER_TEXT_PREVIEW_GET_PRIVATE (self);
}


static void font_manager_text_preview_finalize (GObject* obj) {
	FontManagerTextPreview * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, FONT_MANAGER_TYPE_TEXT_PREVIEW, FontManagerTextPreview);
	_g_object_unref0 (self->priv->_preview);
	__vala_PangoFontDescription_free0 (self->priv->_font_desc);
	G_OBJECT_CLASS (font_manager_text_preview_parent_class)->finalize (obj);
}


GType font_manager_text_preview_get_type (void) {
	static volatile gsize font_manager_text_preview_type_id__volatile = 0;
	if (g_once_init_enter (&font_manager_text_preview_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (FontManagerTextPreviewClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) font_manager_text_preview_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (FontManagerTextPreview), 0, (GInstanceInitFunc) font_manager_text_preview_instance_init, NULL };
		GType font_manager_text_preview_type_id;
		font_manager_text_preview_type_id = g_type_register_static (FONT_MANAGER_TYPE_ADJUSTABLE_PREVIEW, "FontManagerTextPreview", &g_define_type_info, 0);
		g_once_init_leave (&font_manager_text_preview_type_id__volatile, font_manager_text_preview_type_id);
	}
	return font_manager_text_preview_type_id__volatile;
}


static void _vala_font_manager_text_preview_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	FontManagerTextPreview * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, FONT_MANAGER_TYPE_TEXT_PREVIEW, FontManagerTextPreview);
	switch (property_id) {
		case FONT_MANAGER_TEXT_PREVIEW_PREVIEW:
		g_value_set_object (value, font_manager_text_preview_get_preview (self));
		break;
		case FONT_MANAGER_TEXT_PREVIEW_FONT_DESC:
		g_value_set_boxed (value, font_manager_text_preview_get_font_desc (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_font_manager_text_preview_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	FontManagerTextPreview * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, FONT_MANAGER_TYPE_TEXT_PREVIEW, FontManagerTextPreview);
	switch (property_id) {
		case FONT_MANAGER_TEXT_PREVIEW_PREVIEW:
		font_manager_text_preview_set_preview (self, g_value_get_object (value));
		break;
		case FONT_MANAGER_TEXT_PREVIEW_FONT_DESC:
		font_manager_text_preview_set_font_desc (self, g_value_get_boxed (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



