/* Directories.c generated by valac 0.26.1, the Vala compiler
 * generated from Directories.vala, do not modify */

/* Directories.vala
 *
 * Copyright (C) 2009 - 2015 Jerry Casiano
 *
 * This file is part of Font Manager.
 *
 * Font Manager is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Font Manager is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Font Manager.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Author:
 *        Jerry Casiano <JerryCasiano@gmail.com>
*/

#include <glib.h>
#include <glib-object.h>
#include <gee.h>
#include <libxml/tree.h>
#include <libxml/xmlwriter.h>
#include <stdlib.h>
#include <string.h>


#define FONT_CONFIG_TYPE_SELECTIONS (font_config_selections_get_type ())
#define FONT_CONFIG_SELECTIONS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FONT_CONFIG_TYPE_SELECTIONS, FontConfigSelections))
#define FONT_CONFIG_SELECTIONS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FONT_CONFIG_TYPE_SELECTIONS, FontConfigSelectionsClass))
#define FONT_CONFIG_IS_SELECTIONS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FONT_CONFIG_TYPE_SELECTIONS))
#define FONT_CONFIG_IS_SELECTIONS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FONT_CONFIG_TYPE_SELECTIONS))
#define FONT_CONFIG_SELECTIONS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FONT_CONFIG_TYPE_SELECTIONS, FontConfigSelectionsClass))

typedef struct _FontConfigSelections FontConfigSelections;
typedef struct _FontConfigSelectionsClass FontConfigSelectionsClass;
typedef struct _FontConfigSelectionsPrivate FontConfigSelectionsPrivate;
typedef xmlTextWriter FontConfigXmlWriter;

#define FONT_CONFIG_TYPE_DIRECTORIES (font_config_directories_get_type ())
#define FONT_CONFIG_DIRECTORIES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FONT_CONFIG_TYPE_DIRECTORIES, FontConfigDirectories))
#define FONT_CONFIG_DIRECTORIES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FONT_CONFIG_TYPE_DIRECTORIES, FontConfigDirectoriesClass))
#define FONT_CONFIG_IS_DIRECTORIES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FONT_CONFIG_TYPE_DIRECTORIES))
#define FONT_CONFIG_IS_DIRECTORIES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FONT_CONFIG_TYPE_DIRECTORIES))
#define FONT_CONFIG_DIRECTORIES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FONT_CONFIG_TYPE_DIRECTORIES, FontConfigDirectoriesClass))

typedef struct _FontConfigDirectories FontConfigDirectories;
typedef struct _FontConfigDirectoriesClass FontConfigDirectoriesClass;
typedef struct _FontConfigDirectoriesPrivate FontConfigDirectoriesPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _FontConfigSelections {
	GeeHashSet parent_instance;
	FontConfigSelectionsPrivate * priv;
};

struct _FontConfigSelectionsClass {
	GeeHashSetClass parent_class;
	void (*save) (FontConfigSelections* self);
	gboolean (*init) (FontConfigSelections* self);
	void (*parse) (FontConfigSelections* self, xmlNode* root);
	void (*write_node) (FontConfigSelections* self, FontConfigXmlWriter* writer);
	void (*parse_node) (FontConfigSelections* self, xmlNode* node);
};

struct _FontConfigDirectories {
	FontConfigSelections parent_instance;
	FontConfigDirectoriesPrivate * priv;
};

struct _FontConfigDirectoriesClass {
	FontConfigSelectionsClass parent_class;
};


static gpointer font_config_directories_parent_class = NULL;

GType font_config_selections_get_type (void) G_GNUC_CONST;
GType font_config_directories_get_type (void) G_GNUC_CONST;
enum  {
	FONT_CONFIG_DIRECTORIES_DUMMY_PROPERTY
};
FontConfigDirectories* font_config_directories_new (void);
FontConfigDirectories* font_config_directories_construct (GType object_type);
FontConfigSelections* font_config_selections_construct (GType object_type);
void font_config_selections_set_target_element (FontConfigSelections* self, const gchar* value);
void font_config_selections_set_target_file (FontConfigSelections* self, const gchar* value);
static void font_config_directories_real_parse (FontConfigSelections* base, xmlNode* root);
void font_config_selections_parse_node (FontConfigSelections* self, xmlNode* node);
static void font_config_directories_real_write_node (FontConfigSelections* base, FontConfigXmlWriter* writer);
const gchar* font_config_selections_get_target_element (FontConfigSelections* self);


FontConfigDirectories* font_config_directories_construct (GType object_type) {
	FontConfigDirectories * self = NULL;
	self = (FontConfigDirectories*) font_config_selections_construct (object_type);
	font_config_selections_set_target_element ((FontConfigSelections*) self, "dir");
	font_config_selections_set_target_file ((FontConfigSelections*) self, "09-Directories.conf");
	return self;
}


FontConfigDirectories* font_config_directories_new (void) {
	return font_config_directories_construct (FONT_CONFIG_TYPE_DIRECTORIES);
}


static void font_config_directories_real_parse (FontConfigSelections* base, xmlNode* root) {
	FontConfigDirectories * self;
	xmlNode* _tmp0_ = NULL;
	xmlNode* _tmp1_ = NULL;
	self = (FontConfigDirectories*) base;
	_tmp0_ = root;
	_tmp1_ = _tmp0_->children;
	font_config_selections_parse_node ((FontConfigSelections*) self, _tmp1_);
}


static gchar* string_strip (const gchar* self) {
	gchar* result = NULL;
	gchar* _result_ = NULL;
	gchar* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = g_strdup (self);
	_result_ = _tmp0_;
	_tmp1_ = _result_;
	g_strstrip (_tmp1_);
	result = _result_;
	return result;
}


static void font_config_directories_real_write_node (FontConfigSelections* base, FontConfigXmlWriter* writer) {
	FontConfigDirectories * self;
	self = (FontConfigDirectories*) base;
	g_return_if_fail (writer != NULL);
	{
		GeeIterator* _path_it = NULL;
		GeeIterator* _tmp0_ = NULL;
		_tmp0_ = gee_abstract_collection_iterator ((GeeAbstractCollection*) self);
		_path_it = _tmp0_;
		while (TRUE) {
			GeeIterator* _tmp1_ = NULL;
			gboolean _tmp2_ = FALSE;
			gchar* path = NULL;
			GeeIterator* _tmp3_ = NULL;
			gpointer _tmp4_ = NULL;
			FontConfigXmlWriter* _tmp5_ = NULL;
			const gchar* _tmp6_ = NULL;
			const gchar* _tmp7_ = NULL;
			const gchar* _tmp8_ = NULL;
			gchar* _tmp9_ = NULL;
			gchar* _tmp10_ = NULL;
			gchar* _tmp11_ = NULL;
			gchar* _tmp12_ = NULL;
			_tmp1_ = _path_it;
			_tmp2_ = gee_iterator_next (_tmp1_);
			if (!_tmp2_) {
				break;
			}
			_tmp3_ = _path_it;
			_tmp4_ = gee_iterator_get (_tmp3_);
			path = (gchar*) _tmp4_;
			_tmp5_ = writer;
			_tmp6_ = font_config_selections_get_target_element ((FontConfigSelections*) self);
			_tmp7_ = _tmp6_;
			_tmp8_ = path;
			_tmp9_ = string_strip (_tmp8_);
			_tmp10_ = _tmp9_;
			_tmp11_ = g_markup_escape_text (_tmp10_, (gssize) (-1));
			_tmp12_ = _tmp11_;
			xmlTextWriterWriteElement ((xmlTextWriter*) _tmp5_, (xmlChar*) _tmp7_, (xmlChar*) _tmp12_);
			_g_free0 (_tmp12_);
			_g_free0 (_tmp10_);
			_g_free0 (path);
		}
		_g_object_unref0 (_path_it);
	}
	return;
}


static void font_config_directories_class_init (FontConfigDirectoriesClass * klass) {
	font_config_directories_parent_class = g_type_class_peek_parent (klass);
	((FontConfigSelectionsClass *) klass)->parse = font_config_directories_real_parse;
	((FontConfigSelectionsClass *) klass)->write_node = font_config_directories_real_write_node;
}


static void font_config_directories_instance_init (FontConfigDirectories * self) {
}


GType font_config_directories_get_type (void) {
	static volatile gsize font_config_directories_type_id__volatile = 0;
	if (g_once_init_enter (&font_config_directories_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (FontConfigDirectoriesClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) font_config_directories_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (FontConfigDirectories), 0, (GInstanceInitFunc) font_config_directories_instance_init, NULL };
		GType font_config_directories_type_id;
		font_config_directories_type_id = g_type_register_static (FONT_CONFIG_TYPE_SELECTIONS, "FontConfigDirectories", &g_define_type_info, 0);
		g_once_init_leave (&font_config_directories_type_id__volatile, font_config_directories_type_id);
	}
	return font_config_directories_type_id__volatile;
}



