/* PropertiesEditor.c generated by valac 0.26.1, the Vala compiler
 * generated from PropertiesEditor.vala, do not modify */

/* PropertiesEditor.vala
 *
 * Copyright (C) 2009 - 2015 Jerry Casiano
 *
 * This file is part of Font Manager.
 *
 * Font Manager is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Font Manager is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Font Manager.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Author:
 *        Jerry Casiano <JerryCasiano@gmail.com>
*/

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <glib/gi18n-lib.h>
#include <stdlib.h>
#include <string.h>
#include <gdk/gdk.h>


#define FONT_CONFIG_TYPE_PROPERTIES_EDITOR (font_config_properties_editor_get_type ())
#define FONT_CONFIG_PROPERTIES_EDITOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FONT_CONFIG_TYPE_PROPERTIES_EDITOR, FontConfigPropertiesEditor))
#define FONT_CONFIG_PROPERTIES_EDITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FONT_CONFIG_TYPE_PROPERTIES_EDITOR, FontConfigPropertiesEditorClass))
#define FONT_CONFIG_IS_PROPERTIES_EDITOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FONT_CONFIG_TYPE_PROPERTIES_EDITOR))
#define FONT_CONFIG_IS_PROPERTIES_EDITOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FONT_CONFIG_TYPE_PROPERTIES_EDITOR))
#define FONT_CONFIG_PROPERTIES_EDITOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FONT_CONFIG_TYPE_PROPERTIES_EDITOR, FontConfigPropertiesEditorClass))

typedef struct _FontConfigPropertiesEditor FontConfigPropertiesEditor;
typedef struct _FontConfigPropertiesEditorClass FontConfigPropertiesEditorClass;
typedef struct _FontConfigPropertiesEditorPrivate FontConfigPropertiesEditorPrivate;

#define FONT_CONFIG_TYPE_FONT_PROPERTIES_PANE (font_config_font_properties_pane_get_type ())
#define FONT_CONFIG_FONT_PROPERTIES_PANE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FONT_CONFIG_TYPE_FONT_PROPERTIES_PANE, FontConfigFontPropertiesPane))
#define FONT_CONFIG_FONT_PROPERTIES_PANE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FONT_CONFIG_TYPE_FONT_PROPERTIES_PANE, FontConfigFontPropertiesPaneClass))
#define FONT_CONFIG_IS_FONT_PROPERTIES_PANE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FONT_CONFIG_TYPE_FONT_PROPERTIES_PANE))
#define FONT_CONFIG_IS_FONT_PROPERTIES_PANE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FONT_CONFIG_TYPE_FONT_PROPERTIES_PANE))
#define FONT_CONFIG_FONT_PROPERTIES_PANE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FONT_CONFIG_TYPE_FONT_PROPERTIES_PANE, FontConfigFontPropertiesPaneClass))

typedef struct _FontConfigFontPropertiesPane FontConfigFontPropertiesPane;
typedef struct _FontConfigFontPropertiesPaneClass FontConfigFontPropertiesPaneClass;

#define FONT_CONFIG_TYPE_DISPLAY_PROPERTIES_PANE (font_config_display_properties_pane_get_type ())
#define FONT_CONFIG_DISPLAY_PROPERTIES_PANE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FONT_CONFIG_TYPE_DISPLAY_PROPERTIES_PANE, FontConfigDisplayPropertiesPane))
#define FONT_CONFIG_DISPLAY_PROPERTIES_PANE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FONT_CONFIG_TYPE_DISPLAY_PROPERTIES_PANE, FontConfigDisplayPropertiesPaneClass))
#define FONT_CONFIG_IS_DISPLAY_PROPERTIES_PANE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FONT_CONFIG_TYPE_DISPLAY_PROPERTIES_PANE))
#define FONT_CONFIG_IS_DISPLAY_PROPERTIES_PANE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FONT_CONFIG_TYPE_DISPLAY_PROPERTIES_PANE))
#define FONT_CONFIG_DISPLAY_PROPERTIES_PANE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FONT_CONFIG_TYPE_DISPLAY_PROPERTIES_PANE, FontConfigDisplayPropertiesPaneClass))

typedef struct _FontConfigDisplayPropertiesPane FontConfigDisplayPropertiesPane;
typedef struct _FontConfigDisplayPropertiesPaneClass FontConfigDisplayPropertiesPaneClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define FONT_CONFIG_TYPE_PROPERTIES (font_config_properties_get_type ())
#define FONT_CONFIG_PROPERTIES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FONT_CONFIG_TYPE_PROPERTIES, FontConfigProperties))
#define FONT_CONFIG_PROPERTIES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FONT_CONFIG_TYPE_PROPERTIES, FontConfigPropertiesClass))
#define FONT_CONFIG_IS_PROPERTIES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FONT_CONFIG_TYPE_PROPERTIES))
#define FONT_CONFIG_IS_PROPERTIES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FONT_CONFIG_TYPE_PROPERTIES))
#define FONT_CONFIG_PROPERTIES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FONT_CONFIG_TYPE_PROPERTIES, FontConfigPropertiesClass))

typedef struct _FontConfigProperties FontConfigProperties;
typedef struct _FontConfigPropertiesClass FontConfigPropertiesClass;

#define FONT_CONFIG_TYPE_DEFAULT_PROPERTIES (font_config_default_properties_get_type ())
#define FONT_CONFIG_DEFAULT_PROPERTIES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FONT_CONFIG_TYPE_DEFAULT_PROPERTIES, FontConfigDefaultProperties))
#define FONT_CONFIG_DEFAULT_PROPERTIES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FONT_CONFIG_TYPE_DEFAULT_PROPERTIES, FontConfigDefaultPropertiesClass))
#define FONT_CONFIG_IS_DEFAULT_PROPERTIES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FONT_CONFIG_TYPE_DEFAULT_PROPERTIES))
#define FONT_CONFIG_IS_DEFAULT_PROPERTIES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FONT_CONFIG_TYPE_DEFAULT_PROPERTIES))
#define FONT_CONFIG_DEFAULT_PROPERTIES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FONT_CONFIG_TYPE_DEFAULT_PROPERTIES, FontConfigDefaultPropertiesClass))

typedef struct _FontConfigDefaultProperties FontConfigDefaultProperties;
typedef struct _FontConfigDefaultPropertiesClass FontConfigDefaultPropertiesClass;

#define FONT_CONFIG_TYPE_FONT_PROPERTIES (font_config_font_properties_get_type ())
#define FONT_CONFIG_FONT_PROPERTIES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FONT_CONFIG_TYPE_FONT_PROPERTIES, FontConfigFontProperties))
#define FONT_CONFIG_FONT_PROPERTIES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FONT_CONFIG_TYPE_FONT_PROPERTIES, FontConfigFontPropertiesClass))
#define FONT_CONFIG_IS_FONT_PROPERTIES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FONT_CONFIG_TYPE_FONT_PROPERTIES))
#define FONT_CONFIG_IS_FONT_PROPERTIES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FONT_CONFIG_TYPE_FONT_PROPERTIES))
#define FONT_CONFIG_FONT_PROPERTIES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FONT_CONFIG_TYPE_FONT_PROPERTIES, FontConfigFontPropertiesClass))

typedef struct _FontConfigFontProperties FontConfigFontProperties;
typedef struct _FontConfigFontPropertiesClass FontConfigFontPropertiesClass;

#define FONT_CONFIG_TYPE_DISPLAY_PROPERTIES (font_config_display_properties_get_type ())
#define FONT_CONFIG_DISPLAY_PROPERTIES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FONT_CONFIG_TYPE_DISPLAY_PROPERTIES, FontConfigDisplayProperties))
#define FONT_CONFIG_DISPLAY_PROPERTIES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FONT_CONFIG_TYPE_DISPLAY_PROPERTIES, FontConfigDisplayPropertiesClass))
#define FONT_CONFIG_IS_DISPLAY_PROPERTIES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FONT_CONFIG_TYPE_DISPLAY_PROPERTIES))
#define FONT_CONFIG_IS_DISPLAY_PROPERTIES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FONT_CONFIG_TYPE_DISPLAY_PROPERTIES))
#define FONT_CONFIG_DISPLAY_PROPERTIES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FONT_CONFIG_TYPE_DISPLAY_PROPERTIES, FontConfigDisplayPropertiesClass))

typedef struct _FontConfigDisplayProperties FontConfigDisplayProperties;
typedef struct _FontConfigDisplayPropertiesClass FontConfigDisplayPropertiesClass;

struct _FontConfigPropertiesEditor {
	GtkDialog parent_instance;
	FontConfigPropertiesEditorPrivate * priv;
};

struct _FontConfigPropertiesEditorClass {
	GtkDialogClass parent_class;
};

struct _FontConfigPropertiesEditorPrivate {
	FontConfigFontPropertiesPane* general_pane;
	FontConfigDisplayPropertiesPane* display_pane;
	GtkStack* stack;
	GtkStackSwitcher* switcher;
	GtkHeaderBar* header;
	GtkButton* discard;
};


static gpointer font_config_properties_editor_parent_class = NULL;
extern gboolean font_config_properties_skip_save;

GType font_config_properties_editor_get_type (void) G_GNUC_CONST;
GType font_config_font_properties_pane_get_type (void) G_GNUC_CONST;
GType font_config_display_properties_pane_get_type (void) G_GNUC_CONST;
#define FONT_CONFIG_PROPERTIES_EDITOR_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), FONT_CONFIG_TYPE_PROPERTIES_EDITOR, FontConfigPropertiesEditorPrivate))
enum  {
	FONT_CONFIG_PROPERTIES_EDITOR_DUMMY_PROPERTY
};
FontConfigPropertiesEditor* font_config_properties_editor_new (GtkWindow* parent);
FontConfigPropertiesEditor* font_config_properties_editor_construct (GType object_type, GtkWindow* parent);
FontConfigFontPropertiesPane* font_config_font_properties_pane_new (void);
FontConfigFontPropertiesPane* font_config_font_properties_pane_construct (GType object_type);
FontConfigDisplayPropertiesPane* font_config_display_properties_pane_new (void);
FontConfigDisplayPropertiesPane* font_config_display_properties_pane_construct (GType object_type);
static void __lambda144_ (FontConfigPropertiesEditor* self, GtkButton* w);
GType font_config_properties_get_type (void) G_GNUC_CONST;
GType font_config_default_properties_get_type (void) G_GNUC_CONST;
GType font_config_font_properties_get_type (void) G_GNUC_CONST;
FontConfigFontProperties* font_config_font_properties_pane_get_properties (FontConfigFontPropertiesPane* self);
gboolean font_config_properties_discard (FontConfigProperties* self);
GType font_config_display_properties_get_type (void) G_GNUC_CONST;
FontConfigDisplayProperties* font_config_display_properties_pane_get_properties (FontConfigDisplayPropertiesPane* self);
gboolean font_config_properties_load (FontConfigProperties* self, const gchar* target);
static void ___lambda144__gtk_button_clicked (GtkButton* _sender, gpointer self);
static gboolean __lambda145_ (FontConfigPropertiesEditor* self, GdkEventAny* ev);
static gboolean ___lambda145__gtk_widget_delete_event (GtkWidget* _sender, GdkEventAny* event, gpointer self);
static void __lambda146_ (FontConfigPropertiesEditor* self, GParamSpec* pspec);
gboolean font_config_properties_save (FontConfigProperties* self);
static void ___lambda146__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
static void __lambda147_ (FontConfigPropertiesEditor* self, GParamSpec* pspec);
static void ___lambda147__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
static void font_config_properties_editor_real_show (GtkWidget* base);
static GObject * font_config_properties_editor_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void font_config_properties_editor_finalize (GObject* obj);


static void __lambda144_ (FontConfigPropertiesEditor* self, GtkButton* w) {
	FontConfigFontPropertiesPane* _tmp0_ = NULL;
	FontConfigFontProperties* _tmp1_ = NULL;
	FontConfigFontProperties* _tmp2_ = NULL;
	FontConfigDisplayPropertiesPane* _tmp3_ = NULL;
	FontConfigDisplayProperties* _tmp4_ = NULL;
	FontConfigDisplayProperties* _tmp5_ = NULL;
	FontConfigFontPropertiesPane* _tmp6_ = NULL;
	FontConfigFontProperties* _tmp7_ = NULL;
	FontConfigFontProperties* _tmp8_ = NULL;
	FontConfigDisplayPropertiesPane* _tmp9_ = NULL;
	FontConfigDisplayProperties* _tmp10_ = NULL;
	FontConfigDisplayProperties* _tmp11_ = NULL;
	g_return_if_fail (w != NULL);
	font_config_properties_skip_save = TRUE;
	_tmp0_ = self->priv->general_pane;
	_tmp1_ = font_config_font_properties_pane_get_properties (_tmp0_);
	_tmp2_ = _tmp1_;
	font_config_properties_discard ((FontConfigProperties*) _tmp2_);
	_tmp3_ = self->priv->display_pane;
	_tmp4_ = font_config_display_properties_pane_get_properties (_tmp3_);
	_tmp5_ = _tmp4_;
	font_config_properties_discard ((FontConfigProperties*) _tmp5_);
	_tmp6_ = self->priv->general_pane;
	_tmp7_ = font_config_font_properties_pane_get_properties (_tmp6_);
	_tmp8_ = _tmp7_;
	font_config_properties_load ((FontConfigProperties*) _tmp8_, NULL);
	_tmp9_ = self->priv->display_pane;
	_tmp10_ = font_config_display_properties_pane_get_properties (_tmp9_);
	_tmp11_ = _tmp10_;
	font_config_properties_load ((FontConfigProperties*) _tmp11_, NULL);
	font_config_properties_skip_save = FALSE;
}


static void ___lambda144__gtk_button_clicked (GtkButton* _sender, gpointer self) {
	__lambda144_ ((FontConfigPropertiesEditor*) self, _sender);
}


static gboolean __lambda145_ (FontConfigPropertiesEditor* self, GdkEventAny* ev) {
	gboolean result = FALSE;
	gboolean _tmp0_ = FALSE;
	g_return_val_if_fail (ev != NULL, FALSE);
	_tmp0_ = gtk_widget_hide_on_delete ((GtkWidget*) self);
	result = _tmp0_;
	return result;
}


static gboolean ___lambda145__gtk_widget_delete_event (GtkWidget* _sender, GdkEventAny* event, gpointer self) {
	gboolean result;
	result = __lambda145_ ((FontConfigPropertiesEditor*) self, event);
	return result;
}


static void __lambda146_ (FontConfigPropertiesEditor* self, GParamSpec* pspec) {
	FontConfigFontPropertiesPane* _tmp0_ = NULL;
	FontConfigFontProperties* _tmp1_ = NULL;
	FontConfigFontProperties* _tmp2_ = NULL;
	g_return_if_fail (pspec != NULL);
	_tmp0_ = self->priv->general_pane;
	_tmp1_ = font_config_font_properties_pane_get_properties (_tmp0_);
	_tmp2_ = _tmp1_;
	font_config_properties_save ((FontConfigProperties*) _tmp2_);
}


static void ___lambda146__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
	__lambda146_ ((FontConfigPropertiesEditor*) self, pspec);
}


static void __lambda147_ (FontConfigPropertiesEditor* self, GParamSpec* pspec) {
	FontConfigDisplayPropertiesPane* _tmp0_ = NULL;
	FontConfigDisplayProperties* _tmp1_ = NULL;
	FontConfigDisplayProperties* _tmp2_ = NULL;
	g_return_if_fail (pspec != NULL);
	_tmp0_ = self->priv->display_pane;
	_tmp1_ = font_config_display_properties_pane_get_properties (_tmp0_);
	_tmp2_ = _tmp1_;
	font_config_properties_save ((FontConfigProperties*) _tmp2_);
}


static void ___lambda147__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
	__lambda147_ ((FontConfigPropertiesEditor*) self, pspec);
}


FontConfigPropertiesEditor* font_config_properties_editor_construct (GType object_type, GtkWindow* parent) {
	FontConfigPropertiesEditor * self = NULL;
	GtkWindow* _tmp0_ = NULL;
	FontConfigFontPropertiesPane* _tmp1_ = NULL;
	FontConfigFontPropertiesPane* _tmp2_ = NULL;
	FontConfigDisplayPropertiesPane* _tmp3_ = NULL;
	FontConfigDisplayPropertiesPane* _tmp4_ = NULL;
	GtkStack* _tmp5_ = NULL;
	GtkStack* _tmp6_ = NULL;
	FontConfigFontPropertiesPane* _tmp7_ = NULL;
	const gchar* _tmp8_ = NULL;
	GtkStack* _tmp9_ = NULL;
	FontConfigDisplayPropertiesPane* _tmp10_ = NULL;
	const gchar* _tmp11_ = NULL;
	GtkStack* _tmp12_ = NULL;
	GtkStackSwitcher* _tmp13_ = NULL;
	GtkStackSwitcher* _tmp14_ = NULL;
	GtkStack* _tmp15_ = NULL;
	GtkHeaderBar* _tmp16_ = NULL;
	GtkHeaderBar* _tmp17_ = NULL;
	const gchar* _tmp18_ = NULL;
	GtkHeaderBar* _tmp19_ = NULL;
	GtkStackSwitcher* _tmp20_ = NULL;
	GtkHeaderBar* _tmp21_ = NULL;
	GtkButton* _tmp22_ = NULL;
	GtkButton* _tmp23_ = NULL;
	const gchar* _tmp24_ = NULL;
	GtkButton* _tmp25_ = NULL;
	GtkHeaderBar* _tmp26_ = NULL;
	GtkButton* _tmp27_ = NULL;
	GtkHeaderBar* _tmp28_ = NULL;
	GtkBox* _tmp29_ = NULL;
	GtkStack* _tmp30_ = NULL;
	FontConfigFontPropertiesPane* _tmp31_ = NULL;
	FontConfigFontProperties* _tmp32_ = NULL;
	FontConfigFontProperties* _tmp33_ = NULL;
	FontConfigDisplayPropertiesPane* _tmp34_ = NULL;
	FontConfigDisplayProperties* _tmp35_ = NULL;
	FontConfigDisplayProperties* _tmp36_ = NULL;
	self = (FontConfigPropertiesEditor*) g_object_new (object_type, NULL);
	_tmp0_ = parent;
	gtk_window_set_transient_for ((GtkWindow*) self, _tmp0_);
	_tmp1_ = font_config_font_properties_pane_new ();
	g_object_ref_sink (_tmp1_);
	_g_object_unref0 (self->priv->general_pane);
	self->priv->general_pane = _tmp1_;
	_tmp2_ = self->priv->general_pane;
	g_object_set ((GtkWidget*) _tmp2_, "expand", TRUE, NULL);
	_tmp3_ = font_config_display_properties_pane_new ();
	g_object_ref_sink (_tmp3_);
	_g_object_unref0 (self->priv->display_pane);
	self->priv->display_pane = _tmp3_;
	_tmp4_ = self->priv->display_pane;
	g_object_set ((GtkWidget*) _tmp4_, "expand", TRUE, NULL);
	_tmp5_ = (GtkStack*) gtk_stack_new ();
	g_object_ref_sink (_tmp5_);
	_g_object_unref0 (self->priv->stack);
	self->priv->stack = _tmp5_;
	_tmp6_ = self->priv->stack;
	_tmp7_ = self->priv->general_pane;
	_tmp8_ = _ ("General");
	gtk_stack_add_titled (_tmp6_, (GtkWidget*) _tmp7_, "General", _tmp8_);
	_tmp9_ = self->priv->stack;
	_tmp10_ = self->priv->display_pane;
	_tmp11_ = _ ("Display");
	gtk_stack_add_titled (_tmp9_, (GtkWidget*) _tmp10_, "Display", _tmp11_);
	_tmp12_ = self->priv->stack;
	gtk_stack_set_transition_type (_tmp12_, GTK_STACK_TRANSITION_TYPE_CROSSFADE);
	_tmp13_ = (GtkStackSwitcher*) gtk_stack_switcher_new ();
	g_object_ref_sink (_tmp13_);
	_g_object_unref0 (self->priv->switcher);
	self->priv->switcher = _tmp13_;
	_tmp14_ = self->priv->switcher;
	_tmp15_ = self->priv->stack;
	gtk_stack_switcher_set_stack (_tmp14_, _tmp15_);
	_tmp16_ = (GtkHeaderBar*) gtk_header_bar_new ();
	g_object_ref_sink (_tmp16_);
	_g_object_unref0 (self->priv->header);
	self->priv->header = _tmp16_;
	_tmp17_ = self->priv->header;
	_tmp18_ = _ ("FontConfig Properties");
	gtk_header_bar_set_title (_tmp17_, _tmp18_);
	_tmp19_ = self->priv->header;
	_tmp20_ = self->priv->switcher;
	gtk_header_bar_set_custom_title (_tmp19_, (GtkWidget*) _tmp20_);
	_tmp21_ = self->priv->header;
	gtk_header_bar_set_show_close_button (_tmp21_, TRUE);
	_tmp22_ = (GtkButton*) gtk_button_new_from_icon_name ("user-trash-symbolic", GTK_ICON_SIZE_SMALL_TOOLBAR);
	g_object_ref_sink (_tmp22_);
	_g_object_unref0 (self->priv->discard);
	self->priv->discard = _tmp22_;
	_tmp23_ = self->priv->discard;
	_tmp24_ = _ ("Discard configuration");
	gtk_widget_set_tooltip_text ((GtkWidget*) _tmp23_, _tmp24_);
	_tmp25_ = self->priv->discard;
	g_signal_connect_object (_tmp25_, "clicked", (GCallback) ___lambda144__gtk_button_clicked, self, 0);
	_tmp26_ = self->priv->header;
	_tmp27_ = self->priv->discard;
	gtk_header_bar_pack_start (_tmp26_, (GtkWidget*) _tmp27_);
	_tmp28_ = self->priv->header;
	gtk_window_set_titlebar ((GtkWindow*) self, (GtkWidget*) _tmp28_);
	_tmp29_ = (GtkBox*) gtk_dialog_get_content_area ((GtkDialog*) self);
	_tmp30_ = self->priv->stack;
	gtk_container_add ((GtkContainer*) _tmp29_, (GtkWidget*) _tmp30_);
	g_signal_connect_object ((GtkWidget*) self, "delete-event", (GCallback) ___lambda145__gtk_widget_delete_event, self, 0);
	_tmp31_ = self->priv->general_pane;
	_tmp32_ = font_config_font_properties_pane_get_properties (_tmp31_);
	_tmp33_ = _tmp32_;
	g_signal_connect_object ((GObject*) _tmp33_, "notify", (GCallback) ___lambda146__g_object_notify, self, 0);
	_tmp34_ = self->priv->display_pane;
	_tmp35_ = font_config_display_properties_pane_get_properties (_tmp34_);
	_tmp36_ = _tmp35_;
	g_signal_connect_object ((GObject*) _tmp36_, "notify", (GCallback) ___lambda147__g_object_notify, self, 0);
	return self;
}


FontConfigPropertiesEditor* font_config_properties_editor_new (GtkWindow* parent) {
	return font_config_properties_editor_construct (FONT_CONFIG_TYPE_PROPERTIES_EDITOR, parent);
}


static void font_config_properties_editor_real_show (GtkWidget* base) {
	FontConfigPropertiesEditor * self;
	FontConfigFontPropertiesPane* _tmp0_ = NULL;
	FontConfigDisplayPropertiesPane* _tmp1_ = NULL;
	GtkStack* _tmp2_ = NULL;
	GtkHeaderBar* _tmp3_ = NULL;
	self = (FontConfigPropertiesEditor*) base;
	_tmp0_ = self->priv->general_pane;
	gtk_widget_show ((GtkWidget*) _tmp0_);
	_tmp1_ = self->priv->display_pane;
	gtk_widget_show ((GtkWidget*) _tmp1_);
	_tmp2_ = self->priv->stack;
	gtk_widget_show ((GtkWidget*) _tmp2_);
	_tmp3_ = self->priv->header;
	gtk_widget_show_all ((GtkWidget*) _tmp3_);
	GTK_WIDGET_CLASS (font_config_properties_editor_parent_class)->show ((GtkWidget*) G_TYPE_CHECK_INSTANCE_CAST (self, gtk_dialog_get_type (), GtkDialog));
	return;
}


static GObject * font_config_properties_editor_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	FontConfigPropertiesEditor * self;
	parent_class = G_OBJECT_CLASS (font_config_properties_editor_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, FONT_CONFIG_TYPE_PROPERTIES_EDITOR, FontConfigPropertiesEditor);
	gtk_window_set_modal ((GtkWindow*) self, TRUE);
	gtk_window_set_destroy_with_parent ((GtkWindow*) self, TRUE);
	return obj;
}


static void font_config_properties_editor_class_init (FontConfigPropertiesEditorClass * klass) {
	font_config_properties_editor_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (FontConfigPropertiesEditorPrivate));
	((GtkWidgetClass *) klass)->show = font_config_properties_editor_real_show;
	G_OBJECT_CLASS (klass)->constructor = font_config_properties_editor_constructor;
	G_OBJECT_CLASS (klass)->finalize = font_config_properties_editor_finalize;
}


static void font_config_properties_editor_instance_init (FontConfigPropertiesEditor * self) {
	self->priv = FONT_CONFIG_PROPERTIES_EDITOR_GET_PRIVATE (self);
}


static void font_config_properties_editor_finalize (GObject* obj) {
	FontConfigPropertiesEditor * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, FONT_CONFIG_TYPE_PROPERTIES_EDITOR, FontConfigPropertiesEditor);
	_g_object_unref0 (self->priv->general_pane);
	_g_object_unref0 (self->priv->display_pane);
	_g_object_unref0 (self->priv->stack);
	_g_object_unref0 (self->priv->switcher);
	_g_object_unref0 (self->priv->header);
	_g_object_unref0 (self->priv->discard);
	G_OBJECT_CLASS (font_config_properties_editor_parent_class)->finalize (obj);
}


GType font_config_properties_editor_get_type (void) {
	static volatile gsize font_config_properties_editor_type_id__volatile = 0;
	if (g_once_init_enter (&font_config_properties_editor_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (FontConfigPropertiesEditorClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) font_config_properties_editor_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (FontConfigPropertiesEditor), 0, (GInstanceInitFunc) font_config_properties_editor_instance_init, NULL };
		GType font_config_properties_editor_type_id;
		font_config_properties_editor_type_id = g_type_register_static (gtk_dialog_get_type (), "FontConfigPropertiesEditor", &g_define_type_info, 0);
		g_once_init_leave (&font_config_properties_editor_type_id__volatile, font_config_properties_editor_type_id);
	}
	return font_config_properties_editor_type_id__volatile;
}



