/* SubpixelGeometry.c generated by valac 0.26.1, the Vala compiler
 * generated from SubpixelGeometry.vala, do not modify */

/* SubpixelGeometry.vala
 *
 * Copyright (C) 2009 - 2015 Jerry Casiano
 *
 * This file is part of Font Manager.
 *
 * Font Manager is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Font Manager is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Font Manager.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Author:
 *        Jerry Casiano <JerryCasiano@gmail.com>
*/

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gee.h>
#include <glib/gi18n-lib.h>
#include <stdlib.h>
#include <string.h>
#include <gdk/gdk.h>


#define FONT_CONFIG_TYPE_SUBPIXEL_GEOMETRY (font_config_subpixel_geometry_get_type ())
#define FONT_CONFIG_SUBPIXEL_GEOMETRY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FONT_CONFIG_TYPE_SUBPIXEL_GEOMETRY, FontConfigSubpixelGeometry))
#define FONT_CONFIG_SUBPIXEL_GEOMETRY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FONT_CONFIG_TYPE_SUBPIXEL_GEOMETRY, FontConfigSubpixelGeometryClass))
#define FONT_CONFIG_IS_SUBPIXEL_GEOMETRY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FONT_CONFIG_TYPE_SUBPIXEL_GEOMETRY))
#define FONT_CONFIG_IS_SUBPIXEL_GEOMETRY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FONT_CONFIG_TYPE_SUBPIXEL_GEOMETRY))
#define FONT_CONFIG_SUBPIXEL_GEOMETRY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FONT_CONFIG_TYPE_SUBPIXEL_GEOMETRY, FontConfigSubpixelGeometryClass))

typedef struct _FontConfigSubpixelGeometry FontConfigSubpixelGeometry;
typedef struct _FontConfigSubpixelGeometryClass FontConfigSubpixelGeometryClass;
typedef struct _FontConfigSubpixelGeometryPrivate FontConfigSubpixelGeometryPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define FONT_CONFIG_TYPE_SUBPIXEL_ORDER (font_config_subpixel_order_get_type ())
typedef struct _Block12Data Block12Data;

#define FONT_CONFIG_SUBPIXEL_GEOMETRY_TYPE_SUBPIXEL_GEOMETRY_ICON (font_config_subpixel_geometry_subpixel_geometry_icon_get_type ())
#define FONT_CONFIG_SUBPIXEL_GEOMETRY_SUBPIXEL_GEOMETRY_ICON(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), FONT_CONFIG_SUBPIXEL_GEOMETRY_TYPE_SUBPIXEL_GEOMETRY_ICON, FontConfigSubpixelGeometrySubpixelGeometryIcon))
#define FONT_CONFIG_SUBPIXEL_GEOMETRY_SUBPIXEL_GEOMETRY_ICON_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), FONT_CONFIG_SUBPIXEL_GEOMETRY_TYPE_SUBPIXEL_GEOMETRY_ICON, FontConfigSubpixelGeometrySubpixelGeometryIconClass))
#define FONT_CONFIG_SUBPIXEL_GEOMETRY_IS_SUBPIXEL_GEOMETRY_ICON(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), FONT_CONFIG_SUBPIXEL_GEOMETRY_TYPE_SUBPIXEL_GEOMETRY_ICON))
#define FONT_CONFIG_SUBPIXEL_GEOMETRY_IS_SUBPIXEL_GEOMETRY_ICON_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), FONT_CONFIG_SUBPIXEL_GEOMETRY_TYPE_SUBPIXEL_GEOMETRY_ICON))
#define FONT_CONFIG_SUBPIXEL_GEOMETRY_SUBPIXEL_GEOMETRY_ICON_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), FONT_CONFIG_SUBPIXEL_GEOMETRY_TYPE_SUBPIXEL_GEOMETRY_ICON, FontConfigSubpixelGeometrySubpixelGeometryIconClass))

typedef struct _FontConfigSubpixelGeometrySubpixelGeometryIcon FontConfigSubpixelGeometrySubpixelGeometryIcon;
typedef struct _FontConfigSubpixelGeometrySubpixelGeometryIconClass FontConfigSubpixelGeometrySubpixelGeometryIconClass;
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _FontConfigSubpixelGeometrySubpixelGeometryIconPrivate FontConfigSubpixelGeometrySubpixelGeometryIconPrivate;

struct _FontConfigSubpixelGeometry {
	GtkBox parent_instance;
	FontConfigSubpixelGeometryPrivate * priv;
};

struct _FontConfigSubpixelGeometryClass {
	GtkBoxClass parent_class;
};

struct _FontConfigSubpixelGeometryPrivate {
	gint _rgba;
	GtkLabel* label;
	GtkButtonBox* box;
	GeeArrayList* options;
};

typedef enum  {
	FONT_CONFIG_SUBPIXEL_ORDER_UNKNOWN,
	FONT_CONFIG_SUBPIXEL_ORDER_RGB,
	FONT_CONFIG_SUBPIXEL_ORDER_BGR,
	FONT_CONFIG_SUBPIXEL_ORDER_VRGB,
	FONT_CONFIG_SUBPIXEL_ORDER_VBGR,
	FONT_CONFIG_SUBPIXEL_ORDER_NONE
} FontConfigSubpixelOrder;

struct _Block12Data {
	int _ref_count_;
	FontConfigSubpixelGeometry* self;
	GtkRadioButton* button;
	FontConfigSubpixelOrder val;
};

struct _FontConfigSubpixelGeometrySubpixelGeometryIcon {
	GtkBox parent_instance;
	FontConfigSubpixelGeometrySubpixelGeometryIconPrivate * priv;
};

struct _FontConfigSubpixelGeometrySubpixelGeometryIconClass {
	GtkBoxClass parent_class;
};

struct _FontConfigSubpixelGeometrySubpixelGeometryIconPrivate {
	gint _size;
	GtkLabel* c1;
	GtkLabel* c2;
	GtkLabel* c3;
	GtkLabel** labels;
	gint labels_length1;
	gint _labels_size_;
	GdkRGBA r;
	GdkRGBA g;
	GdkRGBA b;
	GdkRGBA n;
};


static gpointer font_config_subpixel_geometry_parent_class = NULL;
static gpointer font_config_subpixel_geometry_subpixel_geometry_icon_parent_class = NULL;

GType font_config_subpixel_geometry_get_type (void) G_GNUC_CONST;
#define FONT_CONFIG_SUBPIXEL_GEOMETRY_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), FONT_CONFIG_TYPE_SUBPIXEL_GEOMETRY, FontConfigSubpixelGeometryPrivate))
enum  {
	FONT_CONFIG_SUBPIXEL_GEOMETRY_DUMMY_PROPERTY,
	FONT_CONFIG_SUBPIXEL_GEOMETRY_RGBA
};
FontConfigSubpixelGeometry* font_config_subpixel_geometry_new (void);
FontConfigSubpixelGeometry* font_config_subpixel_geometry_construct (GType object_type);
GType font_config_subpixel_order_get_type (void) G_GNUC_CONST;
static Block12Data* block12_data_ref (Block12Data* _data12_);
static void block12_data_unref (void * _userdata_);
static GType font_config_subpixel_geometry_subpixel_geometry_icon_get_type (void) G_GNUC_CONST G_GNUC_UNUSED;
static FontConfigSubpixelGeometrySubpixelGeometryIcon* font_config_subpixel_geometry_subpixel_geometry_icon_new (FontConfigSubpixelOrder rgba, gint size);
static FontConfigSubpixelGeometrySubpixelGeometryIcon* font_config_subpixel_geometry_subpixel_geometry_icon_construct (GType object_type, FontConfigSubpixelOrder rgba, gint size);
gchar* font_config_subpixel_order_to_string (FontConfigSubpixelOrder self);
static void _____lambda138_ (Block12Data* _data12_);
void font_config_subpixel_geometry_set_rgba (FontConfigSubpixelGeometry* self, gint value);
static void ______lambda138__gtk_toggle_button_toggled (GtkToggleButton* _sender, gpointer self);
static void font_config_subpixel_geometry_real_show (GtkWidget* base);
gint font_config_subpixel_geometry_get_rgba (FontConfigSubpixelGeometry* self);
#define FONT_CONFIG_SUBPIXEL_GEOMETRY_SUBPIXEL_GEOMETRY_ICON_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), FONT_CONFIG_SUBPIXEL_GEOMETRY_TYPE_SUBPIXEL_GEOMETRY_ICON, FontConfigSubpixelGeometrySubpixelGeometryIconPrivate))
enum  {
	FONT_CONFIG_SUBPIXEL_GEOMETRY_SUBPIXEL_GEOMETRY_ICON_DUMMY_PROPERTY
};
static void font_config_subpixel_geometry_subpixel_geometry_icon_real_show (GtkWidget* base);
static void font_config_subpixel_geometry_subpixel_geometry_icon_real_get_preferred_width (GtkWidget* base, gint* minimum_size, gint* natural_size);
static void font_config_subpixel_geometry_subpixel_geometry_icon_real_get_preferred_height (GtkWidget* base, gint* minimum_size, gint* natural_size);
static void font_config_subpixel_geometry_subpixel_geometry_icon_real_get_preferred_height_for_width (GtkWidget* base, gint width, gint* minimum_height, gint* natural_height);
static void font_config_subpixel_geometry_subpixel_geometry_icon_real_get_preferred_width_for_height (GtkWidget* base, gint height, gint* minimum_width, gint* natural_width);
static GObject * font_config_subpixel_geometry_subpixel_geometry_icon_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void font_config_subpixel_geometry_subpixel_geometry_icon_finalize (GObject* obj);
static void font_config_subpixel_geometry_finalize (GObject* obj);
static void _vala_font_config_subpixel_geometry_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_font_config_subpixel_geometry_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


static Block12Data* block12_data_ref (Block12Data* _data12_) {
	g_atomic_int_inc (&_data12_->_ref_count_);
	return _data12_;
}


static void block12_data_unref (void * _userdata_) {
	Block12Data* _data12_;
	_data12_ = (Block12Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data12_->_ref_count_)) {
		FontConfigSubpixelGeometry* self;
		self = _data12_->self;
		_g_object_unref0 (_data12_->button);
		_g_object_unref0 (self);
		g_slice_free (Block12Data, _data12_);
	}
}


static void _____lambda138_ (Block12Data* _data12_) {
	FontConfigSubpixelGeometry* self;
	GtkRadioButton* _tmp0_ = NULL;
	gboolean _tmp1_ = FALSE;
	gboolean _tmp2_ = FALSE;
	self = _data12_->self;
	_tmp0_ = _data12_->button;
	_tmp1_ = gtk_toggle_button_get_active ((GtkToggleButton*) _tmp0_);
	_tmp2_ = _tmp1_;
	if (_tmp2_) {
		FontConfigSubpixelOrder _tmp3_ = 0;
		_tmp3_ = _data12_->val;
		font_config_subpixel_geometry_set_rgba (self, (gint) _tmp3_);
	}
}


static void ______lambda138__gtk_toggle_button_toggled (GtkToggleButton* _sender, gpointer self) {
	_____lambda138_ (self);
}


FontConfigSubpixelGeometry* font_config_subpixel_geometry_construct (GType object_type) {
	FontConfigSubpixelGeometry * self = NULL;
	const gchar* _tmp0_ = NULL;
	GtkLabel* _tmp1_ = NULL;
	GtkLabel* _tmp2_ = NULL;
	GtkLabel* _tmp3_ = NULL;
	GtkLabel* _tmp4_ = NULL;
	GeeArrayList* _tmp5_ = NULL;
	GtkButtonBox* _tmp6_ = NULL;
	GtkButtonBox* _tmp36_ = NULL;
	self = (FontConfigSubpixelGeometry*) g_object_new (object_type, NULL);
	gtk_widget_set_margin_top ((GtkWidget*) self, 12);
	gtk_orientable_set_orientation ((GtkOrientable*) self, GTK_ORIENTATION_VERTICAL);
	_tmp0_ = _ ("Subpixel Geometry");
	_tmp1_ = (GtkLabel*) gtk_label_new (_tmp0_);
	g_object_ref_sink (_tmp1_);
	_g_object_unref0 (self->priv->label);
	self->priv->label = _tmp1_;
	_tmp2_ = self->priv->label;
	gtk_widget_set_halign ((GtkWidget*) _tmp2_, GTK_ALIGN_CENTER);
	_tmp3_ = self->priv->label;
	g_object_set ((GtkWidget*) _tmp3_, "margin", 12, NULL);
	_tmp4_ = self->priv->label;
	gtk_box_pack_start ((GtkBox*) self, (GtkWidget*) _tmp4_, FALSE, TRUE, (guint) 6);
	_tmp5_ = gee_array_list_new (gtk_radio_button_get_type (), (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL);
	_g_object_unref0 (self->priv->options);
	self->priv->options = _tmp5_;
	_tmp6_ = (GtkButtonBox*) gtk_button_box_new (GTK_ORIENTATION_HORIZONTAL);
	g_object_ref_sink (_tmp6_);
	_g_object_unref0 (self->priv->box);
	self->priv->box = _tmp6_;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp7_ = FALSE;
			_tmp7_ = TRUE;
			while (TRUE) {
				Block12Data* _data12_;
				gint _tmp9_ = 0;
				gint _tmp10_ = 0;
				GeeArrayList* _tmp20_ = NULL;
				gint _tmp21_ = 0;
				gpointer _tmp22_ = NULL;
				gint _tmp23_ = 0;
				FontConfigSubpixelGeometrySubpixelGeometryIcon* icon = NULL;
				FontConfigSubpixelOrder _tmp24_ = 0;
				FontConfigSubpixelGeometrySubpixelGeometryIcon* _tmp25_ = NULL;
				GtkRadioButton* _tmp26_ = NULL;
				FontConfigSubpixelGeometrySubpixelGeometryIcon* _tmp27_ = NULL;
				FontConfigSubpixelGeometrySubpixelGeometryIcon* _tmp28_ = NULL;
				GtkRadioButton* _tmp29_ = NULL;
				FontConfigSubpixelOrder _tmp30_ = 0;
				gchar* _tmp31_ = NULL;
				gchar* _tmp32_ = NULL;
				GtkRadioButton* _tmp33_ = NULL;
				GtkButtonBox* _tmp34_ = NULL;
				GtkRadioButton* _tmp35_ = NULL;
				_data12_ = g_slice_new0 (Block12Data);
				_data12_->_ref_count_ = 1;
				_data12_->self = g_object_ref (self);
				if (!_tmp7_) {
					gint _tmp8_ = 0;
					_tmp8_ = i;
					i = _tmp8_ + 1;
				}
				_tmp7_ = FALSE;
				_tmp9_ = i;
				if (!(_tmp9_ < 5)) {
					block12_data_unref (_data12_);
					_data12_ = NULL;
					break;
				}
				_tmp10_ = i;
				if (_tmp10_ == 0) {
					GeeArrayList* _tmp11_ = NULL;
					GtkRadioButton* _tmp12_ = NULL;
					GtkRadioButton* _tmp13_ = NULL;
					_tmp11_ = self->priv->options;
					_tmp12_ = (GtkRadioButton*) gtk_radio_button_new (NULL);
					g_object_ref_sink (_tmp12_);
					_tmp13_ = _tmp12_;
					gee_abstract_collection_add ((GeeAbstractCollection*) _tmp11_, _tmp13_);
					_g_object_unref0 (_tmp13_);
				} else {
					GeeArrayList* _tmp14_ = NULL;
					GeeArrayList* _tmp15_ = NULL;
					gpointer _tmp16_ = NULL;
					GtkRadioButton* _tmp17_ = NULL;
					GtkRadioButton* _tmp18_ = NULL;
					GtkRadioButton* _tmp19_ = NULL;
					_tmp14_ = self->priv->options;
					_tmp15_ = self->priv->options;
					_tmp16_ = gee_abstract_list_get ((GeeAbstractList*) _tmp15_, 0);
					_tmp17_ = (GtkRadioButton*) _tmp16_;
					_tmp18_ = (GtkRadioButton*) gtk_radio_button_new_from_widget (_tmp17_);
					g_object_ref_sink (_tmp18_);
					_tmp19_ = _tmp18_;
					gee_abstract_collection_add ((GeeAbstractCollection*) _tmp14_, _tmp19_);
					_g_object_unref0 (_tmp19_);
					_g_object_unref0 (_tmp17_);
				}
				_tmp20_ = self->priv->options;
				_tmp21_ = i;
				_tmp22_ = gee_abstract_list_get ((GeeAbstractList*) _tmp20_, _tmp21_);
				_data12_->button = (GtkRadioButton*) _tmp22_;
				_tmp23_ = i;
				_data12_->val = (FontConfigSubpixelOrder) _tmp23_;
				_tmp24_ = _data12_->val;
				_tmp25_ = font_config_subpixel_geometry_subpixel_geometry_icon_new (_tmp24_, 36);
				g_object_ref_sink (_tmp25_);
				icon = _tmp25_;
				_tmp26_ = _data12_->button;
				_tmp27_ = icon;
				gtk_container_add ((GtkContainer*) _tmp26_, (GtkWidget*) _tmp27_);
				_tmp28_ = icon;
				gtk_widget_show ((GtkWidget*) _tmp28_);
				_tmp29_ = _data12_->button;
				_tmp30_ = _data12_->val;
				_tmp31_ = font_config_subpixel_order_to_string (_tmp30_);
				_tmp32_ = _tmp31_;
				gtk_widget_set_tooltip_text ((GtkWidget*) _tmp29_, _tmp32_);
				_g_free0 (_tmp32_);
				_tmp33_ = _data12_->button;
				g_signal_connect_data ((GtkToggleButton*) _tmp33_, "toggled", (GCallback) ______lambda138__gtk_toggle_button_toggled, block12_data_ref (_data12_), (GClosureNotify) block12_data_unref, 0);
				_tmp34_ = self->priv->box;
				_tmp35_ = _data12_->button;
				gtk_box_pack_start ((GtkBox*) _tmp34_, (GtkWidget*) _tmp35_, TRUE, TRUE, (guint) 0);
				_g_object_unref0 (icon);
				block12_data_unref (_data12_);
				_data12_ = NULL;
			}
		}
	}
	_tmp36_ = self->priv->box;
	gtk_box_pack_start ((GtkBox*) self, (GtkWidget*) _tmp36_, TRUE, TRUE, (guint) 6);
	return self;
}


FontConfigSubpixelGeometry* font_config_subpixel_geometry_new (void) {
	return font_config_subpixel_geometry_construct (FONT_CONFIG_TYPE_SUBPIXEL_GEOMETRY);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void font_config_subpixel_geometry_real_show (GtkWidget* base) {
	FontConfigSubpixelGeometry * self;
	GtkLabel* _tmp12_ = NULL;
	GtkButtonBox* _tmp13_ = NULL;
	self = (FontConfigSubpixelGeometry*) base;
	{
		GeeArrayList* _widget_list = NULL;
		GeeArrayList* _tmp0_ = NULL;
		GeeArrayList* _tmp1_ = NULL;
		gint _widget_size = 0;
		GeeArrayList* _tmp2_ = NULL;
		gint _tmp3_ = 0;
		gint _tmp4_ = 0;
		gint _widget_index = 0;
		_tmp0_ = self->priv->options;
		_tmp1_ = _g_object_ref0 (_tmp0_);
		_widget_list = _tmp1_;
		_tmp2_ = _widget_list;
		_tmp3_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp2_);
		_tmp4_ = _tmp3_;
		_widget_size = _tmp4_;
		_widget_index = -1;
		while (TRUE) {
			gint _tmp5_ = 0;
			gint _tmp6_ = 0;
			gint _tmp7_ = 0;
			GtkRadioButton* widget = NULL;
			GeeArrayList* _tmp8_ = NULL;
			gint _tmp9_ = 0;
			gpointer _tmp10_ = NULL;
			GtkRadioButton* _tmp11_ = NULL;
			_tmp5_ = _widget_index;
			_widget_index = _tmp5_ + 1;
			_tmp6_ = _widget_index;
			_tmp7_ = _widget_size;
			if (!(_tmp6_ < _tmp7_)) {
				break;
			}
			_tmp8_ = _widget_list;
			_tmp9_ = _widget_index;
			_tmp10_ = gee_abstract_list_get ((GeeAbstractList*) _tmp8_, _tmp9_);
			widget = (GtkRadioButton*) _tmp10_;
			_tmp11_ = widget;
			gtk_widget_show ((GtkWidget*) _tmp11_);
			_g_object_unref0 (widget);
		}
		_g_object_unref0 (_widget_list);
	}
	_tmp12_ = self->priv->label;
	gtk_widget_show ((GtkWidget*) _tmp12_);
	_tmp13_ = self->priv->box;
	gtk_widget_show ((GtkWidget*) _tmp13_);
	GTK_WIDGET_CLASS (font_config_subpixel_geometry_parent_class)->show ((GtkWidget*) G_TYPE_CHECK_INSTANCE_CAST (self, gtk_box_get_type (), GtkBox));
	return;
}


gint font_config_subpixel_geometry_get_rgba (FontConfigSubpixelGeometry* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_rgba;
	result = _tmp0_;
	return result;
}


void font_config_subpixel_geometry_set_rgba (FontConfigSubpixelGeometry* self, gint value) {
	gboolean _tmp0_ = FALSE;
	gint _tmp1_ = 0;
	gint _tmp6_ = 0;
	GeeArrayList* _tmp7_ = NULL;
	gint _tmp8_ = 0;
	gpointer _tmp9_ = NULL;
	GtkRadioButton* _tmp10_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp1_ = value;
	if (_tmp1_ < 0) {
		_tmp0_ = TRUE;
	} else {
		gint _tmp2_ = 0;
		GeeArrayList* _tmp3_ = NULL;
		gint _tmp4_ = 0;
		gint _tmp5_ = 0;
		_tmp2_ = value;
		_tmp3_ = self->priv->options;
		_tmp4_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp3_);
		_tmp5_ = _tmp4_;
		_tmp0_ = _tmp2_ >= _tmp5_;
	}
	if (_tmp0_) {
		return;
	}
	_tmp6_ = value;
	self->priv->_rgba = _tmp6_;
	_tmp7_ = self->priv->options;
	_tmp8_ = self->priv->_rgba;
	_tmp9_ = gee_abstract_list_get ((GeeAbstractList*) _tmp7_, _tmp8_);
	_tmp10_ = (GtkRadioButton*) _tmp9_;
	gtk_toggle_button_set_active ((GtkToggleButton*) _tmp10_, TRUE);
	_g_object_unref0 (_tmp10_);
	g_object_notify ((GObject *) self, "rgba");
}


static FontConfigSubpixelGeometrySubpixelGeometryIcon* font_config_subpixel_geometry_subpixel_geometry_icon_construct (GType object_type, FontConfigSubpixelOrder rgba, gint size) {
	FontConfigSubpixelGeometrySubpixelGeometryIcon * self = NULL;
	gint _tmp0_ = 0;
	GdkRGBA* order = NULL;
	gint order_length1 = 0;
	gint _order_size_ = 0;
	gboolean _tmp1_ = FALSE;
	FontConfigSubpixelOrder _tmp2_ = 0;
	gboolean _tmp19_ = FALSE;
	FontConfigSubpixelOrder _tmp20_ = 0;
	self = (FontConfigSubpixelGeometrySubpixelGeometryIcon*) g_object_new (object_type, NULL);
	_tmp0_ = size;
	self->priv->_size = _tmp0_;
	order = NULL;
	order_length1 = 0;
	_order_size_ = order_length1;
	_tmp2_ = rgba;
	if (_tmp2_ == FONT_CONFIG_SUBPIXEL_ORDER_RGB) {
		_tmp1_ = TRUE;
	} else {
		FontConfigSubpixelOrder _tmp3_ = 0;
		_tmp3_ = rgba;
		_tmp1_ = _tmp3_ == FONT_CONFIG_SUBPIXEL_ORDER_VRGB;
	}
	if (_tmp1_) {
		GdkRGBA _tmp4_ = {0};
		GdkRGBA _tmp5_ = {0};
		GdkRGBA _tmp6_ = {0};
		GdkRGBA* _tmp7_ = NULL;
		_tmp4_ = self->priv->r;
		_tmp5_ = self->priv->g;
		_tmp6_ = self->priv->b;
		_tmp7_ = g_new0 (GdkRGBA, 3);
		_tmp7_[0] = _tmp4_;
		_tmp7_[1] = _tmp5_;
		_tmp7_[2] = _tmp6_;
		order = (g_free (order), NULL);
		order = _tmp7_;
		order_length1 = 3;
		_order_size_ = order_length1;
	} else {
		gboolean _tmp8_ = FALSE;
		FontConfigSubpixelOrder _tmp9_ = 0;
		_tmp9_ = rgba;
		if (_tmp9_ == FONT_CONFIG_SUBPIXEL_ORDER_BGR) {
			_tmp8_ = TRUE;
		} else {
			FontConfigSubpixelOrder _tmp10_ = 0;
			_tmp10_ = rgba;
			_tmp8_ = _tmp10_ == FONT_CONFIG_SUBPIXEL_ORDER_VBGR;
		}
		if (_tmp8_) {
			GdkRGBA _tmp11_ = {0};
			GdkRGBA _tmp12_ = {0};
			GdkRGBA _tmp13_ = {0};
			GdkRGBA* _tmp14_ = NULL;
			_tmp11_ = self->priv->b;
			_tmp12_ = self->priv->g;
			_tmp13_ = self->priv->r;
			_tmp14_ = g_new0 (GdkRGBA, 3);
			_tmp14_[0] = _tmp11_;
			_tmp14_[1] = _tmp12_;
			_tmp14_[2] = _tmp13_;
			order = (g_free (order), NULL);
			order = _tmp14_;
			order_length1 = 3;
			_order_size_ = order_length1;
		} else {
			GdkRGBA _tmp15_ = {0};
			GdkRGBA _tmp16_ = {0};
			GdkRGBA _tmp17_ = {0};
			GdkRGBA* _tmp18_ = NULL;
			_tmp15_ = self->priv->n;
			_tmp16_ = self->priv->n;
			_tmp17_ = self->priv->n;
			_tmp18_ = g_new0 (GdkRGBA, 3);
			_tmp18_[0] = _tmp15_;
			_tmp18_[1] = _tmp16_;
			_tmp18_[2] = _tmp17_;
			order = (g_free (order), NULL);
			order = _tmp18_;
			order_length1 = 3;
			_order_size_ = order_length1;
		}
	}
	_tmp20_ = rgba;
	if (_tmp20_ == FONT_CONFIG_SUBPIXEL_ORDER_VRGB) {
		_tmp19_ = TRUE;
	} else {
		FontConfigSubpixelOrder _tmp21_ = 0;
		_tmp21_ = rgba;
		_tmp19_ = _tmp21_ == FONT_CONFIG_SUBPIXEL_ORDER_VBGR;
	}
	if (_tmp19_) {
		gtk_orientable_set_orientation ((GtkOrientable*) self, GTK_ORIENTATION_VERTICAL);
	}
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp22_ = FALSE;
			_tmp22_ = TRUE;
			while (TRUE) {
				gint _tmp24_ = 0;
				GtkLabel** _tmp25_ = NULL;
				gint _tmp25__length1 = 0;
				GtkLabel** _tmp26_ = NULL;
				gint _tmp26__length1 = 0;
				gint _tmp27_ = 0;
				GtkLabel* _tmp28_ = NULL;
				GdkRGBA* _tmp29_ = NULL;
				gint _tmp29__length1 = 0;
				gint _tmp30_ = 0;
				GdkRGBA _tmp31_ = {0};
				GtkLabel** _tmp32_ = NULL;
				gint _tmp32__length1 = 0;
				gint _tmp33_ = 0;
				GtkLabel* _tmp34_ = NULL;
				if (!_tmp22_) {
					gint _tmp23_ = 0;
					_tmp23_ = i;
					i = _tmp23_ + 1;
				}
				_tmp22_ = FALSE;
				_tmp24_ = i;
				_tmp25_ = self->priv->labels;
				_tmp25__length1 = self->priv->labels_length1;
				if (!(_tmp24_ < _tmp25__length1)) {
					break;
				}
				_tmp26_ = self->priv->labels;
				_tmp26__length1 = self->priv->labels_length1;
				_tmp27_ = i;
				_tmp28_ = _tmp26_[_tmp27_];
				_tmp29_ = order;
				_tmp29__length1 = order_length1;
				_tmp30_ = i;
				_tmp31_ = _tmp29_[_tmp30_];
				gtk_widget_override_background_color ((GtkWidget*) _tmp28_, GTK_STATE_FLAG_NORMAL, &_tmp31_);
				_tmp32_ = self->priv->labels;
				_tmp32__length1 = self->priv->labels_length1;
				_tmp33_ = i;
				_tmp34_ = _tmp32_[_tmp33_];
				gtk_box_pack_start ((GtkBox*) self, (GtkWidget*) _tmp34_, TRUE, TRUE, (guint) 0);
			}
		}
	}
	order = (g_free (order), NULL);
	return self;
}


static FontConfigSubpixelGeometrySubpixelGeometryIcon* font_config_subpixel_geometry_subpixel_geometry_icon_new (FontConfigSubpixelOrder rgba, gint size) {
	return font_config_subpixel_geometry_subpixel_geometry_icon_construct (FONT_CONFIG_SUBPIXEL_GEOMETRY_TYPE_SUBPIXEL_GEOMETRY_ICON, rgba, size);
}


static void font_config_subpixel_geometry_subpixel_geometry_icon_real_show (GtkWidget* base) {
	FontConfigSubpixelGeometrySubpixelGeometryIcon * self;
	GtkLabel** _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	self = (FontConfigSubpixelGeometrySubpixelGeometryIcon*) base;
	_tmp0_ = self->priv->labels;
	_tmp0__length1 = self->priv->labels_length1;
	{
		GtkLabel** label_collection = NULL;
		gint label_collection_length1 = 0;
		gint _label_collection_size_ = 0;
		gint label_it = 0;
		label_collection = _tmp0_;
		label_collection_length1 = _tmp0__length1;
		for (label_it = 0; label_it < _tmp0__length1; label_it = label_it + 1) {
			GtkLabel* _tmp1_ = NULL;
			GtkLabel* label = NULL;
			_tmp1_ = _g_object_ref0 (label_collection[label_it]);
			label = _tmp1_;
			{
				GtkLabel* _tmp2_ = NULL;
				_tmp2_ = label;
				gtk_widget_show ((GtkWidget*) _tmp2_);
				_g_object_unref0 (label);
			}
		}
	}
	GTK_WIDGET_CLASS (font_config_subpixel_geometry_subpixel_geometry_icon_parent_class)->show ((GtkWidget*) G_TYPE_CHECK_INSTANCE_CAST (self, gtk_box_get_type (), GtkBox));
}


static void font_config_subpixel_geometry_subpixel_geometry_icon_real_get_preferred_width (GtkWidget* base, gint* minimum_size, gint* natural_size) {
	FontConfigSubpixelGeometrySubpixelGeometryIcon * self;
	gint _vala_minimum_size = 0;
	gint _vala_natural_size = 0;
	gint _tmp0_ = 0;
	self = (FontConfigSubpixelGeometrySubpixelGeometryIcon*) base;
	_tmp0_ = self->priv->_size;
	_vala_natural_size = _tmp0_;
	_vala_minimum_size = _vala_natural_size;
	if (minimum_size) {
		*minimum_size = _vala_minimum_size;
	}
	if (natural_size) {
		*natural_size = _vala_natural_size;
	}
	return;
}


static void font_config_subpixel_geometry_subpixel_geometry_icon_real_get_preferred_height (GtkWidget* base, gint* minimum_size, gint* natural_size) {
	FontConfigSubpixelGeometrySubpixelGeometryIcon * self;
	gint _vala_minimum_size = 0;
	gint _vala_natural_size = 0;
	gint _tmp0_ = 0;
	self = (FontConfigSubpixelGeometrySubpixelGeometryIcon*) base;
	_tmp0_ = self->priv->_size;
	_vala_natural_size = _tmp0_;
	_vala_minimum_size = _vala_natural_size;
	if (minimum_size) {
		*minimum_size = _vala_minimum_size;
	}
	if (natural_size) {
		*natural_size = _vala_natural_size;
	}
	return;
}


static void font_config_subpixel_geometry_subpixel_geometry_icon_real_get_preferred_height_for_width (GtkWidget* base, gint width, gint* minimum_height, gint* natural_height) {
	FontConfigSubpixelGeometrySubpixelGeometryIcon * self;
	gint _vala_minimum_height = 0;
	gint _vala_natural_height = 0;
	gint _tmp0_ = 0;
	self = (FontConfigSubpixelGeometrySubpixelGeometryIcon*) base;
	_tmp0_ = width;
	_vala_natural_height = _tmp0_;
	_vala_minimum_height = _vala_natural_height;
	if (minimum_height) {
		*minimum_height = _vala_minimum_height;
	}
	if (natural_height) {
		*natural_height = _vala_natural_height;
	}
	return;
}


static void font_config_subpixel_geometry_subpixel_geometry_icon_real_get_preferred_width_for_height (GtkWidget* base, gint height, gint* minimum_width, gint* natural_width) {
	FontConfigSubpixelGeometrySubpixelGeometryIcon * self;
	gint _vala_minimum_width = 0;
	gint _vala_natural_width = 0;
	gint _tmp0_ = 0;
	self = (FontConfigSubpixelGeometrySubpixelGeometryIcon*) base;
	_tmp0_ = height;
	_vala_natural_width = _tmp0_;
	_vala_minimum_width = _vala_natural_width;
	if (minimum_width) {
		*minimum_width = _vala_minimum_width;
	}
	if (natural_width) {
		*natural_width = _vala_natural_width;
	}
	return;
}


static GObject * font_config_subpixel_geometry_subpixel_geometry_icon_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	FontConfigSubpixelGeometrySubpixelGeometryIcon * self;
	GtkLabel* _tmp0_ = NULL;
	GtkLabel* _tmp1_ = NULL;
	GtkLabel* _tmp2_ = NULL;
	GtkLabel* _tmp3_ = NULL;
	GtkLabel* _tmp4_ = NULL;
	GtkLabel* _tmp5_ = NULL;
	GtkLabel** _tmp6_ = NULL;
	parent_class = G_OBJECT_CLASS (font_config_subpixel_geometry_subpixel_geometry_icon_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, FONT_CONFIG_SUBPIXEL_GEOMETRY_TYPE_SUBPIXEL_GEOMETRY_ICON, FontConfigSubpixelGeometrySubpixelGeometryIcon);
	gtk_box_set_homogeneous ((GtkBox*) self, TRUE);
	gtk_widget_set_valign ((GtkWidget*) self, GTK_ALIGN_CENTER);
	gtk_widget_set_halign ((GtkWidget*) self, GTK_ALIGN_CENTER);
	gtk_orientable_set_orientation ((GtkOrientable*) self, GTK_ORIENTATION_HORIZONTAL);
	_tmp0_ = self->priv->c1;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_tmp2_ = self->priv->c2;
	_tmp3_ = _g_object_ref0 (_tmp2_);
	_tmp4_ = self->priv->c3;
	_tmp5_ = _g_object_ref0 (_tmp4_);
	_tmp6_ = g_new0 (GtkLabel*, 3 + 1);
	_tmp6_[0] = _tmp1_;
	_tmp6_[1] = _tmp3_;
	_tmp6_[2] = _tmp5_;
	self->priv->labels = (_vala_array_free (self->priv->labels, self->priv->labels_length1, (GDestroyNotify) g_object_unref), NULL);
	self->priv->labels = _tmp6_;
	self->priv->labels_length1 = 3;
	self->priv->_labels_size_ = self->priv->labels_length1;
	gdk_rgba_parse (&self->priv->r, "Red");
	gdk_rgba_parse (&self->priv->g, "Green");
	gdk_rgba_parse (&self->priv->b, "Blue");
	gdk_rgba_parse (&self->priv->n, "Gray");
	return obj;
}


static void font_config_subpixel_geometry_subpixel_geometry_icon_class_init (FontConfigSubpixelGeometrySubpixelGeometryIconClass * klass) {
	font_config_subpixel_geometry_subpixel_geometry_icon_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (FontConfigSubpixelGeometrySubpixelGeometryIconPrivate));
	((GtkWidgetClass *) klass)->show = font_config_subpixel_geometry_subpixel_geometry_icon_real_show;
	((GtkWidgetClass *) klass)->get_preferred_width = font_config_subpixel_geometry_subpixel_geometry_icon_real_get_preferred_width;
	((GtkWidgetClass *) klass)->get_preferred_height = font_config_subpixel_geometry_subpixel_geometry_icon_real_get_preferred_height;
	((GtkWidgetClass *) klass)->get_preferred_height_for_width = font_config_subpixel_geometry_subpixel_geometry_icon_real_get_preferred_height_for_width;
	((GtkWidgetClass *) klass)->get_preferred_width_for_height = font_config_subpixel_geometry_subpixel_geometry_icon_real_get_preferred_width_for_height;
	G_OBJECT_CLASS (klass)->constructor = font_config_subpixel_geometry_subpixel_geometry_icon_constructor;
	G_OBJECT_CLASS (klass)->finalize = font_config_subpixel_geometry_subpixel_geometry_icon_finalize;
}


static void font_config_subpixel_geometry_subpixel_geometry_icon_instance_init (FontConfigSubpixelGeometrySubpixelGeometryIcon * self) {
	GtkLabel* _tmp0_ = NULL;
	GtkLabel* _tmp1_ = NULL;
	GtkLabel* _tmp2_ = NULL;
	self->priv = FONT_CONFIG_SUBPIXEL_GEOMETRY_SUBPIXEL_GEOMETRY_ICON_GET_PRIVATE (self);
	_tmp0_ = (GtkLabel*) gtk_label_new (NULL);
	g_object_ref_sink (_tmp0_);
	self->priv->c1 = _tmp0_;
	_tmp1_ = (GtkLabel*) gtk_label_new (NULL);
	g_object_ref_sink (_tmp1_);
	self->priv->c2 = _tmp1_;
	_tmp2_ = (GtkLabel*) gtk_label_new (NULL);
	g_object_ref_sink (_tmp2_);
	self->priv->c3 = _tmp2_;
	memset (&self->priv->r, 0, sizeof (GdkRGBA));
	memset (&self->priv->g, 0, sizeof (GdkRGBA));
	memset (&self->priv->b, 0, sizeof (GdkRGBA));
	memset (&self->priv->n, 0, sizeof (GdkRGBA));
}


static void font_config_subpixel_geometry_subpixel_geometry_icon_finalize (GObject* obj) {
	FontConfigSubpixelGeometrySubpixelGeometryIcon * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, FONT_CONFIG_SUBPIXEL_GEOMETRY_TYPE_SUBPIXEL_GEOMETRY_ICON, FontConfigSubpixelGeometrySubpixelGeometryIcon);
	_g_object_unref0 (self->priv->c1);
	_g_object_unref0 (self->priv->c2);
	_g_object_unref0 (self->priv->c3);
	self->priv->labels = (_vala_array_free (self->priv->labels, self->priv->labels_length1, (GDestroyNotify) g_object_unref), NULL);
	G_OBJECT_CLASS (font_config_subpixel_geometry_subpixel_geometry_icon_parent_class)->finalize (obj);
}


static GType font_config_subpixel_geometry_subpixel_geometry_icon_get_type (void) {
	static volatile gsize font_config_subpixel_geometry_subpixel_geometry_icon_type_id__volatile = 0;
	if (g_once_init_enter (&font_config_subpixel_geometry_subpixel_geometry_icon_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (FontConfigSubpixelGeometrySubpixelGeometryIconClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) font_config_subpixel_geometry_subpixel_geometry_icon_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (FontConfigSubpixelGeometrySubpixelGeometryIcon), 0, (GInstanceInitFunc) font_config_subpixel_geometry_subpixel_geometry_icon_instance_init, NULL };
		GType font_config_subpixel_geometry_subpixel_geometry_icon_type_id;
		font_config_subpixel_geometry_subpixel_geometry_icon_type_id = g_type_register_static (gtk_box_get_type (), "FontConfigSubpixelGeometrySubpixelGeometryIcon", &g_define_type_info, 0);
		g_once_init_leave (&font_config_subpixel_geometry_subpixel_geometry_icon_type_id__volatile, font_config_subpixel_geometry_subpixel_geometry_icon_type_id);
	}
	return font_config_subpixel_geometry_subpixel_geometry_icon_type_id__volatile;
}


static void font_config_subpixel_geometry_class_init (FontConfigSubpixelGeometryClass * klass) {
	font_config_subpixel_geometry_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (FontConfigSubpixelGeometryPrivate));
	((GtkWidgetClass *) klass)->show = font_config_subpixel_geometry_real_show;
	G_OBJECT_CLASS (klass)->get_property = _vala_font_config_subpixel_geometry_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_font_config_subpixel_geometry_set_property;
	G_OBJECT_CLASS (klass)->finalize = font_config_subpixel_geometry_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), FONT_CONFIG_SUBPIXEL_GEOMETRY_RGBA, g_param_spec_int ("rgba", "rgba", "rgba", G_MININT, G_MAXINT, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
}


static void font_config_subpixel_geometry_instance_init (FontConfigSubpixelGeometry * self) {
	self->priv = FONT_CONFIG_SUBPIXEL_GEOMETRY_GET_PRIVATE (self);
}


static void font_config_subpixel_geometry_finalize (GObject* obj) {
	FontConfigSubpixelGeometry * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, FONT_CONFIG_TYPE_SUBPIXEL_GEOMETRY, FontConfigSubpixelGeometry);
	_g_object_unref0 (self->priv->label);
	_g_object_unref0 (self->priv->box);
	_g_object_unref0 (self->priv->options);
	G_OBJECT_CLASS (font_config_subpixel_geometry_parent_class)->finalize (obj);
}


GType font_config_subpixel_geometry_get_type (void) {
	static volatile gsize font_config_subpixel_geometry_type_id__volatile = 0;
	if (g_once_init_enter (&font_config_subpixel_geometry_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (FontConfigSubpixelGeometryClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) font_config_subpixel_geometry_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (FontConfigSubpixelGeometry), 0, (GInstanceInitFunc) font_config_subpixel_geometry_instance_init, NULL };
		GType font_config_subpixel_geometry_type_id;
		font_config_subpixel_geometry_type_id = g_type_register_static (gtk_box_get_type (), "FontConfigSubpixelGeometry", &g_define_type_info, 0);
		g_once_init_leave (&font_config_subpixel_geometry_type_id__volatile, font_config_subpixel_geometry_type_id);
	}
	return font_config_subpixel_geometry_type_id__volatile;
}


static void _vala_font_config_subpixel_geometry_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	FontConfigSubpixelGeometry * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, FONT_CONFIG_TYPE_SUBPIXEL_GEOMETRY, FontConfigSubpixelGeometry);
	switch (property_id) {
		case FONT_CONFIG_SUBPIXEL_GEOMETRY_RGBA:
		g_value_set_int (value, font_config_subpixel_geometry_get_rgba (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_font_config_subpixel_geometry_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	FontConfigSubpixelGeometry * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, FONT_CONFIG_TYPE_SUBPIXEL_GEOMETRY, FontConfigSubpixelGeometry);
	switch (property_id) {
		case FONT_CONFIG_SUBPIXEL_GEOMETRY_RGBA:
		font_config_subpixel_geometry_set_rgba (self, g_value_get_int (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



